- README.md
- hack/get-server.sh
Lots of folks get antsy when curl | bash'ing. To the extent we can not use root thats great. So if a user has $HOME/bin or $HOME/.local/bin on their PATH we can use those. Otherwise we can use /usr/local/bin or /opt/bin. But the user needs to use us with sudo explicitly. Rather then us escalating to it.
Also made the code more idomatic bash.
The docs will also need to be updated:
curl -sf -L https://download.daytona.io/daytona/get-server.sh | sudo bash
> Reworking the get-server.sh to install as non root.

- go.mod
- go.sum
- pkg/provider/manager/manager.go
- pkg/server/api/server.go
- pkg/server/server.go
This PR addresses #129. With these changes, the server will kill all orphaned provider processes before initializing them again.
Closes #129
> fix: kill orphaned provider processes on server start

- hack/get-server.sh
Given the concerns folks have about curl | bash we are not going to create the directory automatically. We will check and fail the script prompting the user to create the directory.
We also moved both the check for directory and sudo above the download so we can fail fast.
NA
NA
Fixes @nkkko's issue from slack.
> Check that the DESTINATION dir exists.

- pkg/views/workspace/create/view.go
Skip repo URL prompt during single project workspace creation, as repository URL has already been selected in the previous step. 
This PR addresses issue #132 
/claim #132
> fix: skip repo url on single project workspace creation

- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
Added -all flag for start, stop and delete cmd
This PR addresses issue #116 
/claim #116
> feat: added all flag

- pkg/cmd/autocomplete.go
- pkg/cmd/cmd.go
Automate Shell Completion Configuration
Adds automatic injection of the autocomplete script into the appropriate shell profile and then instructing the user on how to source the file (or instruct to open a new terminal).
This PR addresses issue #49 
Closes #49 
/claim #49 
> feat: auto inject completions

- pkg/server/providers.go
This PR prevents the server from downloading already present default providers.
Closes #78
> fix: prevent downloading of already present providers

- pkg/provider/manager/installer.go
- pkg/server/providers.go
With this PR, the server will check for provider updates on startup and notify the user if any registered providers have updates available. Additionally, it will instruct the user to use `daytona provider update` to update them.
Closes #164
> feat: check for provider updates on server start

- pkg/cmd/gitprovider/gitprovider.go
- pkg/cmd/provider/list.go
- pkg/cmd/target/list.go
Missing format flag outputs (json, yaml) for git provider, provider and target lists
> feat: add missing json/yaml outputs

- README.md
- hack/get-server.sh
As there were some concerns on need to run `get-server.sh` script with sudo privileges we decided to better document it inside the script and also provide the ability for users to change the binary installation path.
If script is run with current default:
```
curl -sf -L https://download.daytona.io/daytona/get-server.sh | bash
```
...it wont interrupt user and binary will be installed on the default `\usr\local\bin` path.  But we will present info on the option how user can adjust the installation path. Also that could be the one without need of sudo privileges.
```
Default installation directory: /usr/local/bin
You can override this by setting the DAYTONA_PATH environment variable (ie. `| DAYTONA_PATH=/home/user/bin bash`)
```
Also script will check if destination directory exists. If …
> chore: enable to set binary install path

- .github/workflows/support_stale_and_close.yaml
GitHub Action that first labels with `stale` and then closes issues and PRs that have had no activity for a specified amount of time. Currently it is 14d to label them as stale, then another 7d to close.
If an update/comment occur on stale issues or pull requests, the stale label will be removed and the timer will restart.
Also if PR or Issue takes longer intentionally labelling it with `on-hold` will skip this check.
N/A
N/A
N/A
> chore: add cleanup gha for inactive issues and PRs

- README.md
- cmd/daytona/config/const.go
- internal/jetbrains/ides.go
- internal/jetbrains/types.go
- internal/util/remote_os.go
- pkg/cmd/workspace/code.go
- pkg/ide/browser.go
- pkg/ide/jetbrains.go
- pkg/ide/vscode.go
- pkg/views/ide/view.go
This PR introduces support for opening projects in JetBrains IDEs.
The user can now select any JetBrains IDE with the `daytona ide` command.
Opening a JetBrains IDE includes downloading the appropriate IDE into the project and opening it with the JetBrains Gateway SSH plugin.
Closes #179
> feat: support opening projects in JetBrains IDEs

- CONTRIBUTING.md
- CONTRIBUTORS.md
- PREPARING_YOUR_CHANGES.md
- README.md
We were using a contributors file to track acceptance of the Apache license by contributors. It was adding a lot of friction for first time contributors. So we're going to move to the DCO v1.1 which only requires that contributors sign or signoff on their commits.
For the contributions up until now, we will leave the contributors file intact. From this commit forward, we will enforce the DCO and all commits will be signed.
> Move to the DCO v1.1.

- internal/util/time.go
- pkg/views/styles.go
- pkg/views/workspace/list/view.go
- pkg/views/workspace/selection/view.go
- pkg/views/workspace/selection/workspace.go
This PR addresses issue #134 
/claim #134
> feat: add more workspace info on prompting screen

- .github/CODEOWNERS
This will setup daytona-oss team to automatically be set as `Reviewers` on any new PR created in the repo
N/A
N/A
More on CODEWONERS functionality if needed [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)
> chore: set codeowners for automatic PR reviewer assignment

- pkg/ide/browser.go
- pkg/ports/ports.go
`CheckPortReady` checks if a service is ready on the specified port by making an HTTP GET request.
closes #68
> fix: check if the port is ready to serve

- pkg/views/ide/view.go
The IDE selection was inconsistent and incomplete, with options being cut off . This has been fixed to ensure a complete and consistent selection experience across the TUI. 
closes #196
/claim #196 
> chore:making ide selection consistent with other TUI

- cmd/daytona/main.go
- pkg/server/logs/log_formater.go
This PR reduces server logging to the user. Before, with the excessive amount of logs, it was hard to track down issues with the server.
A comparison of before and after is presented below. 
Closes #205 
Before:
After:
> feat: reduce server logging

- pkg/cmd/workspace/create.go
- pkg/ide/jetbrains.go
Opening a JetBrains IDE properly logs what's happening to the user.
```bash
daytona ➜ /workspaces/daytona (jetbrains-logging ✗) $ daytona code
Opening the workspace project 'cpp-hello-world' in your preferred IDE.
Downloading the IDE into the project from https://download.jetbrains.com/webide/PhpStorm-2023.2.2-aarch64.tar.gz...
IDE downloaded. Opening...
```
Closes #206
> fix: jetbrains IDE logging

- pkg/cmd/workspace/info.go
- pkg/views/workspace/info/view.go
This PR solved the show workspace info exit failed.
Closed #187
> fix(cmd/workspace): show info exit failed

- internal/util/apiclient/websocket_url.go
- pkg/cmd/server/logs.go
- pkg/cmd/workspace/create.go
This PR fixes an issue with websocket requests when the API URL of the server used `https`. Now the CLI appropriately uses `wss` in that case and `ws` otherwise.
Closes #198
> fix: use wss for https API URLs

- pkg/server/logs/log_formater.go
This PR reduces FRPC log output by default. It also allows the user to control the FRP log by defining `FRP_LOG_OUTPUT` (which can be "console" or a file path) and `FRP_LOG_LEVEL` to control the log level.
> feat: more control over frp logs

- cmd/daytona/config/config.go
- pkg/cmd/workspace/code.go
This PR fixes an issue with the initial default IDE. It sets it to VS Code.
> fix: set vscode as initial default IDE

- cmd/daytona/config/const.go
With this PR, JetBrains IDEs are sorted in the `daytona ide` list to maintain consistent order across command calls.
Closes #220
> fix: sort JB IDEs for consistent ordering

- pkg/agent/ssh/server.go
Default the SSH connection to `$HOME` if the project directory is not present.
Closes #236
> fix: default ssh to HOME if project dir is not present

- README.md
- go.mod
- go.sum
- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/server/restart.go
- pkg/cmd/server/server.go
- pkg/cmd/server/stop.go
- pkg/server/config/config.go
- pkg/server/logs/log_formater.go
This PR introduces support for running the server in daemon mode by running `daytona server -d`.
It also adds `server stop` and `server restart` commands to control the daemon once it has been started.
> feat: support server in daemon mode

- pkg/server/config/config.go
- pkg/server/config/defaults.go
With this PR, the user will be able to override default configuration values for the server when starting it for the first time. This change is most relevant for using Daytona with Nix.
Closes #234
> feat: allow server defaults override via env

- README.md
- cmd/daytona/config/autocompletion.go
- cmd/daytona/config/config.go
- cmd/daytona/config/ssh_file.go
- pkg/cmd/cmd.go
- pkg/cmd/prune.go
- pkg/cmd/workspace/delete.go
- pkg/views/profile/switch_to_default.go
- pkg/views/prune/confirm.go
- pkg/views/prune/server_stopped.go
- pkg/views/util/globals.go
`daytona prune` clears all the data associated with Daytona from the machine:
- deletes all workspaces
- deletes the daytona ssh config file and unlinks it from the main ssh config file
- deletes the daytona autocomplete file and unlinks it from the "run command" (.rc) file
- deletes the daytona config directory after prompting the user to turn off the Daytona Server
When ran in a non-default profile, it prompts the user to switch to the default profile or abort
Confirmation prompt for pruning implemented (Y/n)
This PR addresses issue #200
> daytona prune

- pkg/provider/util/project_start_script.go
Added a util function that providers can use to get the project start script. This improves DX by removing the need for provider developers to know the details of what to run to start a project. Providers will be able to call `util.GetProjectStartScript`.
Closes #258
> feat: provider project start script util

- pkg/logger/project.go
- pkg/logger/workspace.go
- pkg/provider/manager/manager.go
- pkg/provider/types.go
- pkg/server/api/controllers/provider/install.go
- pkg/server/config/config.go
- pkg/server/providers.go
- pkg/server/provisioner/provisioner.go
Now providers will be able to call `logger.GetWorkspace/ProjectLogger`  and log to the same file as the server.
This can then give users more feedback into everything happening with their workspaces and improves DX when working on providers.
Closes #255
> refactor: workspace and project logger

- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/server/server.go
- pkg/server/api/controllers/log/websocket.go
- pkg/server/logs/log_formater.go
Adds server daemon foreground logs. Specifically, if the server starts successfully, the server information message is displayed and if the server fails to start, it outputs the logs of the server so the user is informed about the error. Check the Screenshot section for an example.
Closes #250
> fix: server daemon foreground logging

- pkg/server/api/controllers/binary/binaries.go
Minor fix for joining a URL. Uses `url.JoinPath` instead of `path.Join`.
> fix: download url join

- README.md
- hack/get-server.sh
Running the server removed from get-server.sh and moved to the command call - fixes having the command called as sudo instead of as user.
Lets the user use "get-server" to only install the binary without running the server
This PR addresses issue #276
> fix: quick start command

- pkg/views/workspace/selection/workspace.go
The workspace selection model was breaking due to recent API name changes. It failed to reference the correct name. So, the selection model was dysfunctional for `daytona code`, `daytona ssh`, and other commands.
> [urgent] fix: Workspace Selection Model

- pkg/ide/jetbrains.go
- pkg/views/ide/view.go
Implemented a progress bar using the [schollz/progressbar/v3](https://pkg.go.dev/github.com/schollz/progressbar/v3) library to show download progress to the user.
closes #219
/claim #219
The progress bar works well. There's an unrelated issue with opening the IDE that I need to investigate before filing a bug report.
> fix: add progress indicator to downloadIde 

- pkg/cmd/cmd.go
- pkg/cmd/purge.go
- pkg/views/purge/confirm.go
- pkg/views/purge/server_stopped.go
The "prune" word was used incorrectly as it usually means removing unused data/objects (e.g. docker prune, git prune) so we will be renaming it to `daytona purge`
> chore: rename prune to purge

- README.md
- hack/install.sh
- pkg/server/config/defaults.go
Renaming get-server.sh to install.sh as it is the clearer name for the script
get-server.sh is staying on download.daytona.io along with install.sh for some time
> chore: rename getserver to install

- pkg/cmd/server/server.go
- pkg/server/server.go
This PR adds a server healthcheck by checking if it's actually reachable
This PR addresses issue #254
/claim #254
> feat: add server healthcheck

- internal/util/log_reader.go
- pkg/server/api/controllers/log/websocket.go
Fixing server-side WebSocket errors
Improved code for WebSocket connection and removed the error of abnormal closure since it occurs when the client closes the connection abruptly and it is not an error.
This PR addresses issue #271 
/claim #271
> fix: server side websocket errors

- pkg/server/provisioner/provisioner.go
- pkg/types/workspace.go
Environment variables are now attached to a project by the provisioner when sending requests to a provider. This will improve DX when working on providers.
_Note:_ `DAYTONA_WS_DIR` is still required to be defined by the provider.
Closes #259
> refactor: attach env variables to projects

- pkg/cmd/server/server.go
This PR made the server started message more clear for local and remote usage. Check the screenshots for an example.
Closes #292
> fix: clearer server started message

- pkg/cmd/workspace/create.go
Throw an error if target name supplied is invalid on workspace create
This PR addresses issue #304 
/claim #304
> fix: throw error on workspace create if target name is invalid

- pkg/cmd/workspace/create.go
If there's just one target defined for the current setup, don't prompt the user.
This PR addresses issue #296
> feat: default to single target

- pkg/cmd/target/list.go
- pkg/views/target/list/view.go
Enhance the presentation of the `target list` command by displaying the output in a tabular format. See attached screenshot for details.
closes #269
/claim #269
Updated - 
> feat: improve the view of target list command

- pkg/cmd/server/apikey/generate.go
- pkg/views/server/apikey/create.go
Handle duplicate api key names gracefully instead of dumping database error
This PR addresses issue #295
> fix: handle duplicate api key

- README.md
- pkg/cmd/workspace/create.go
This PR replaces the --skip-ide flag, which skips IDE opening, with the --connect flag. If the --connect flag is not present in daytona create, the IDE is not opened automatically.
This PR addresses issue #315
/claim #315
> replace --skip-ide flag with --connect

- cmd/daytona/config/const.go
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/ssh.go
- pkg/ide/terminal.go
Adding SSH Terminal as an option in the IDE, enabling users to open their workspace directly in the terminal.
closes #252
/claim #252
> feat: add Terminal SSH as an IDE option

- hack/install.sh
- internal/constants/get_daytona_script.go
Update daytona server downloading message from Downloading server from -> Downloading Daytona binary from
This PR addresses issue #321
> fix: daytona server/binary download msg

- pkg/server/logs/log_formatter.go
Fix typo, some places used "formater" instead of "formatter"
> chore: formatter typo

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/postcreate.sh
Addresses #201.
This change pulls the devcontainer out of Daytona for two reasons:
- Prebuilding
- Reuse across all the provider plugins
This PR addresses issue #201
> Move to prebuilt devcontainer.

- pkg/server/workspaceservice/create.go
This pull request trims the -git suffix from project name when creating workspaces using a .git url.
This PR addresses issue #349 
/claim #349
> fix: workspace create with .git url appends -git to project

- pkg/views/workspace/create/view.go
This PR trims `git` suffix being appended to suggested workspace names when using a .git url
This PR addresses issue #354 
/claim #354
> fix: workspace name suggestion

- pkg/cmd/workspace/create.go
- pkg/views/util/spinner.go
- pkg/views/workspace/create/view.go
Implemented a spinner for the git provider functions to address the issue of TUI flashing, which occurs due to delays in data retrieval from the git_provider. The spinner indicates loading state improving user experience.
closes #131 
/claim #131 
https://github.com/daytonaio/daytona/assets/71957674/13d2e5ef-c3a6-4468-b280-6beab4fc32e2
> feat: add spinner to git provider functions, fixing the Tui flashing

- cmd/daytona/config/ssh_file.go
This PR fixes SSH agent forwarding when connecting to projects. The `ForwardAgent yes` line was missing from the SSH config entry.
Closes #369
> fix: ssh agent forwarding

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/server/defaults.go
- pkg/server/types.go
- pkg/serverapiclient/api/openapi.yaml
- pkg/serverapiclient/docs/ServerConfig.md
- pkg/serverapiclient/model_server_config.go
- pkg/views/server/configure.go
Add `defaultProjectImage` as a server config property. Currently, it is part of the Docker provider as well. That will need to be removed.
Closes #388
> feat: added default project image to server config

- internal/testing/agent/mocks/gitservice.go
- internal/testing/agent/mocks/tailscaleserver.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/config/config.go
- pkg/agent/tailscale/server.go
- pkg/cmd/agent/agent.go
This PR adds support for agent host mode. Running the agent in host mode will skip project initialization (git config, repo clone, etc.)
The agent is run in host mode with the `--host` flag.
Closes #385.
> feat: agent host mode

- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
Noticed that using the TUI to select a workspace for starting/stopping (`daytona start`, `daytona stop`) still displays the workspace ID instead of the workspace name in message on success.
First command shows the issue, second and third command show it working correctly when passing argument:
> fix: workspace start stop message to user

- cmd/daytona/config/config.go
- pkg/cmd/profile/add.go
- pkg/cmd/server/server.go
This PR fixes an issue where the user was unable to add a new profile before running `daytona server` for the first time.
Closes #398
> fix: adding profile when config does not exist

- pkg/cmd/agent/agent.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/ssh-proxy.go
- pkg/ports/ports.go
- pkg/workspace/workspace.go
Hostnames are now a 64-bit encoded string of workspaceId-projectName. This ensures that the hostname does not exceed the 63-character limit of the tailscale hostname
Closes #394.
> fix: shorter tailscale hostnames

- internal/apikeys/functions.go
- pkg/cmd/server/apikey/revoke.go
- pkg/server/apikeys/apikeys.go
- pkg/server/apikeys/validate.go
- pkg/views/server/apikey/list.go
This PR adds a confirmation prompt when revoking API keys. Additionally, if the key being revoked is attached to the users active profile, the user will receive a warning message as shown in the screenshot below.
Closes #399
> feat: add warning when revoking api keys

- internal/testing/agent/mocks/apiserver.go
- internal/util/apiclient/server/api_client.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
This PR fixes construction of the API client in the agent. The agent now passes its API URL and key to the helper method. Before this PR, the agent was not testable outside of the development environment.
> fix: get agent api client from config

- pkg/agent/git/service.go
This PR fixes an issue in the agent that caused it to always clone the main branch of a project.
Closes #413
Closes #326
> fix: repo branch clone

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/server.go
- pkg/api/validator.go
- pkg/cmd/workspace/create.go
- pkg/server/workspaces/dto/workspace.go
- pkg/server/workspaces/service_test.go
- pkg/serverapiclient/api/openapi.yaml
- pkg/serverapiclient/docs/CreateWorkspaceRequest.md
- pkg/serverapiclient/docs/CreateWorkspaceRequestProject.md
- pkg/serverapiclient/docs/WorkspaceAPI.md
- pkg/serverapiclient/model_create_workspace_request.go
- pkg/serverapiclient/model_create_workspace_request_project.go
Makes project name required and non-empty when creating a workspace.
This is done by implementing an api level validator which will be used in the future
After consideration, ID is unnecessary as a part of the project request DTO so it has been removed.
> fix: required project name

- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/views/util/globals.go
- pkg/views/workspace/create/summary.go
- pkg/views/workspace/create/view.go
Refactored/changed the process of defining additional projects to keep prompting the user instead of having them define the project count in advance.
This doesn't negatively impact the UX and is in preparation for additional project configuration screens
Also added summary screen when multi project workspace is done being configured
> feat: multi project creation ux

- pkg/views/workspace/list/view.go
When workspace projects' properties are malformed, `daytona list` panics due to a missing check for the "Info" and "Info.Projects" pointer checks. We should avoid panics in any case.
> fix: daytona list panic

- internal/util/apiclient/server/conversion/project.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/cmd/server/server.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/db/dto/project.go
- pkg/server/defaults.go
- pkg/server/types.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/dto/workspace.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
- pkg/serverapiclient/api/openapi.yaml
- pkg/serverapiclient/docs/CreateWorkspaceRequestProject.md
- pkg/serverapiclient/docs/Project.md
- pkg/serverapiclient/docs/ServerConfig.md
- pkg/serverapiclient/model_create_workspace_request_project.go
- pkg/serverapiclient/model_project.go
- pkg/serverapiclient/model_server_config.go
- pkg/views/server/configure.go
- pkg/workspace/workspace.go
This PR introduces the `PostStartCommands` property into the project model. This property holds commands that the agent inside the project once it has been started.
This change will require users to run `daytona server configure` and add `sudo dockerd` as a default start command once the Docker Provider is updated to not include starting dockerd by itself.
> feat: project post start commands

- pkg/cmd/server/containerregistry/containerregistry.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/db/dto/project.go
- pkg/views/server/configure.go
- pkg/views/util/commands.go
- pkg/views/workspace/create/configuration.go
- pkg/views/workspace/create/summary.go
- pkg/views/workspace/create/view.go
- pkg/views/workspace/create/workspacedata.go
- pkg/views/workspace/selection/projectrequest.go
- pkg/views/workspace/selection/view.go
Adds an additional project configuration screen 
- for single project workspaces it can be opened by pressing "f10" during workspace name form
- for multi project workspaces it can be opened by pressing "f10" during summary screen
This PR closes issue #416 
Single project: 
Multi project:
> feat: advanced project configuration in cli 

- pkg/server/headscale/client.go
In #433, we updated the GRPC package to 1.63.0 which marked `DialContext` as deprecated and suggested to use `NewClient` instead. Unfortunately, `NewClient` does not work for us currently and would require more investigation into how to migrate successfully.
In the meantime, this PR reverts to `DialContext`.
More info on how to migrate should be available here [https://github.com/grpc/grpc-go/issues/7049](https://github.com/grpc/grpc-go/issues/7049).
> fix: headscale grpc regression

- internal/tailscale/connection.go
This PR is the first part of solving #427. It adds a 10 second timeout to attempting to establish a tailscale connection to the Daytona server. It prevents hanging indefinitely while establishing a connection.
This PR addresses issue #427.
> fix: add tailscale connection timeout

- pkg/cmd/server/configure.go
- pkg/views/server/configure.go
This follows up on a stale PR which had the same purpose.
Within this PR, other server properties are enabled for configuration through CLI.
This PR closes #238
> feat: enable configuration of other server properties

- internal/testing/agent/mocks/gitservice.go
- pkg/agent/agent.go
- pkg/agent/git/service.go
- pkg/agent/types.go
This PR introduces the use of the username property found in the GitProvider when cloning a repo. Before, we hardcoded the `daytona` username which might not work with all git providers.
> fix: use gitprovider username when cloning a repo

- pkg/api/controllers/log/websocket.go
- pkg/api/server.go
- pkg/cmd/workspace/create.go
- pkg/logger/logger.go
- pkg/logger/project.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/start.go
With this PR, project logs are no longer being written to the workspace logs. The create command now reads the workspace and all project logs in the creation flow.
Closes #461
> feat: remove project logs from workspace logs

- go.mod
- pkg/cmd/workspace/create.go
- pkg/workspace/workspace.go
This PR changes how workspace IDs are generated. They are now generated with the [stringid](https://github.com/moby/moby/blob/master/pkg/stringid/stringid.go) package from Docker that is also used to generate container names. The new workspace ID is 12 characters long.
Additionally, project hostnames are now generated as `Truncate(workspaceId-projectName, 63)`. Truncating is necessary to comply with the subdomain length limit.
Closes #474.
Breaking change: Because of the change to generating project hostnames, users will fail to connect to existing workspaces. We recommend that users remove all their workspaces before upgrading to a version with this update.
> feat: shorter workspace IDs

- pkg/cmd/server/stop.go
- pkg/views/server/started/view.go
Removing the border in the server started message to align with the rest of the TUI design
Also a minor fix to the "stopping server" message formatting
> feat: remove server border

- pkg/cmd/workspace/create.go
This PR adds retries to getting the workspace (and project) logs. It also removes a 2 second timeout before attempting to get the logs which brings an improvement into the overall experience as now the user will get updates sooner.
Closes #478
> fix: workspace logs retry

- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/views/workspace/create/view.go
This PR changes the format of the daytona create command to allow
`daytona create GIT_REPO_URL`
Removes multi-project workspace creation in the command line
Improves workspace name suggestion in TUI to not take into account used workspace names and instead append a number. The same logic is used in automatically setting the workspace name when it is not provided in the CLI
Closes #449 
Closes #476 
Closes #473
> feat: daytona create format

- pkg/views/workspace/create/summary.go
Changes the preselected value for `daytona create --multi-project` to be "Yes" instead of "Abort" in order to improve UX
> feat: default summary to yes

- pkg/views/server/started/view.go
Removing the word "locally" from the message that appears to the user when running `daytona serve` / `daytona server`
It is no longer necessary as the instructions to connect to the server remotely were moved to daytona server config
> feat: server started label update

- pkg/cmd/server/serve.go
This PR increases the health check timeout to 30 seconds and decreases the polling interval to 1 second. This should allow the server enough time to boot up while making the command more responsive.
Closes #494.
> fix: daemon server health check

- pkg/cmd/workspace/create.go
Fixing the `daytona create` command's short description from `create [WORKSPACE_NAME]` to `create [REPOSITORY_URL]`
> fix: daytona create help

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/pull_request_template.md
Updated the templates to be less of a chore. 
1. The bug issue template no longer includes a `Browser` field and the OS example was updated to `Ubuntu 22.04`.
2. The PR template was reduced because we enforce conventional commits which are self-explain the type of the change.
> chore: update issue and PR templates

- pkg/cmd/containerregistry/list.go
- pkg/views/containerregistry/list/view.go
This PR updates the container registry command styling to reflect the rest of the CLI/TUI list views
This PR addresses issue #501 
/claim #501
**Before:**
**After:**
> feat: update container registry list styling to match rest of TUI

- pkg/server/workspaces/stop.go
- pkg/views/workspace/list/view.go
- pkg/views/workspace/selection/workspace.go
This PR includes a fix for stopping a project. After the workspace is stopped, its uptime is reset to 0. Additionally, views that display the state are updated to display projects as stopped if the uptime is 0.
Closes #493
> fix: reset project uptime after stop

- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
This PR makes use of workspace names instead of IDs in CLI messages to improve UX.
Closes #515
> fix: use workspace names instead of id in CLI messages

- pkg/agent/tailscale/server.go
- pkg/cmd/agent/agent.go
This PR fixes running the agent in host mode inside a workspace instance. The agent tailscale server now uses the agent API client instead of relying on the CLI config.
Closes #528
> fix: use agent api client in tailscale server

- internal/testing/server/workspaces/mocks/api_key_service.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/middlewares/project.go
- pkg/apikey/apikey.go
- pkg/server/apikeys/service.go
- pkg/server/apikeys/validate.go
- pkg/server/apikeys/validate_test.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/remove.go
- pkg/server/workspaces/service_test.go
- pkg/serverapiclient/api/openapi.yaml
- pkg/serverapiclient/docs/ApikeyApiKeyType.md
- pkg/serverapiclient/model_apikey_api_key_type.go
- pkg/workspace/workspace.go
This PR introduces workspace API keys and exposes a function to get env variables. Both these changes are requirements for VM-based providers that will run the agent in host mode inside a workspace instance.
> feat: workspace API keys and env variables

- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/repository_wizard.go
- pkg/views/workspace/create/summary.go
- pkg/views/workspace/create/view.go
- pkg/views/workspace/selection/branch.go
- pkg/views/workspace/selection/checkout.go
- pkg/views/workspace/selection/namespace.go
- pkg/views/workspace/selection/provider.go
- pkg/views/workspace/selection/pullrequest.go
- pkg/views/workspace/selection/repository.go
Removes terms "primary" and "secondary" when referring to projects and changes it to simply be "first", "second", "third" etc.
The projects are all treated equally so there is no need for categorizing them.
Terms "initial" and "additional" projects are still kept for some variable/property names as they fit the way creation/display views currently work.
> feat: project naming

- pkg/views/workspace/info/view.go
Daytona info command would panic in some cases where certain workspace properties are not defined.
Adds checks to prevent panics
> fix: info panic

- internal/util/apiclient/server/api_client.go
This PR introduces a HEAD request to the Daytona Server API before constructing the API client. This ensures that API calls are heading towards a Daytona Server instance and not to a http server that might be holding the same port.
Closes #529
> fix: ensure API calls are heading towards a Daytona Server instance

- go.mod
- go.sum
- internal/cmd/tailscale/connection.go
- pkg/agent/ssh/server.go
- pkg/agent/ssh/unix_forward.go
- pkg/cmd/server/serve.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/ssh-proxy.go
- pkg/ide/jetbrains.go
- pkg/ports/ports.go
- pkg/provider/manager/manager.go
- pkg/provider/types.go
- pkg/server/server.go
- pkg/tailscale/connection.go
- pkg/tailscale/forward_unix.go
- pkg/tailscale/tunnel/endpoint.go
- pkg/tailscale/tunnel/forward.go
- pkg/tailscale/tunnel/tunnel.go
This PR is a small refactor to getting the Tailscale connection inside Daytona but the main contribution is the Tailscale SSH tunnel package that allows for forwarding tcp ports and unix sockets over ssh over Tailscale. This package will make it easier for VM-based provider (e.g. DigitalOcean) to forward the docker.sock from workspace instances. That forwarded sock is then used to create project containers inside VMs.
> feat: tailscale ssh tunnel package

- internal/util/workspace.go
- pkg/views/workspace/info/view.go
- pkg/views/workspace/list/view.go
- pkg/views/workspace/selection/workspace.go
Added ID to post-creation workspace info view
Workspace selection description row now shows the repository url for single project workspaces. Multi project workspaces still show just the project name
Closes #454 
^workspace `idagelic` has one project while workspace `idagelic2` has two
> feat: daytona info consistency

- pkg/cmd/server/daemon/daemon.go
This PR adds the user as an argument to the server service that is started with `daytona server`
Closes #537
> fix: run server service as user

- pkg/cmd/apikey/generate.go
- pkg/views/profile/create.go
- pkg/views/server/apikey/notify.go
Changed the `daytona api-key new` command response from 
to
Updated the profile adding form from
to
This lets the user know how to setup a remote profile when they run `daytona profile add` and suggests the "add" command instead of "edit" as it is the more likely goal when creating an API key
Closes #539 
Making the minor change in the api-key command response seemed cleaner than having the user run `daytona server config` and view the entire configuration model of the server
> feat: remote profile flow

- internal/jetbrains/ides.go
- internal/jetbrains/types.go
- pkg/ide/jetbrains.go
At the moment an outdated version of Jetbrains is used for the IDE's. The Jetbrains API now reads the latest product version based on the ID and then uses this when starting the IDE. 
[#545](https://github.com/daytonaio/daytona/issues/545)
> feat: Use always latest Jetbrains product version 

- pkg/git/service.go
This PR fixes cloning conditions in the git service. It will now correctly clone the repo in the following scenarios:
```jsonc
{
"branch": "BRANCH_NAME",
"sha": "commit_sha"
}
```
```jsonc
{
"branch": "commit_sha",
"sha": "commit_sha"
}
```
Closes #553
> fix: git service branch clone

- pkg/cmd/workspace/create.go
This PR fixes a small issue for stopping the reading of logs on workspace create.
Closes #552
> fix: stop reading logs on workspace create

- pkg/agent/tailscale/server.go
This PR fixes the agent tailscale server connection reestablishing. The server now performs a health check every 5 seconds and, if it fails, attempts to reconnect. The reconnection process involves getting a new network key and initializing a new tailscale connection.
Closes #522
To test this PR:
1. Create a workspace
2. Stop the Daytona Server for more than 5 minutes
3. Start the Daytona Server
4. Attempt to connect to the workspace project with `daytona ssh`
> fix: agent tailscale server reestablish connection

- .vscode/launch.json
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/server.go
- pkg/cmd/server/serve.go
- pkg/server/defaults.go
- pkg/server/workspaces/service_test.go
- pkg/serverapiclient/README.md
- pkg/serverapiclient/api/openapi.yaml
- pkg/serverapiclient/configuration.go
- pkg/serverapiclient/docs/ApiKeyAPI.md
- pkg/serverapiclient/docs/ContainerRegistryAPI.md
- pkg/serverapiclient/docs/GitProviderAPI.md
- pkg/serverapiclient/docs/ProfileAPI.md
- pkg/serverapiclient/docs/ProviderAPI.md
- pkg/serverapiclient/docs/ServerAPI.md
- pkg/serverapiclient/docs/TargetAPI.md
- pkg/serverapiclient/docs/WorkspaceAPI.md
This PR changes the default server API and Headscale ports to 3986 and 3987, respectively.
This change will not influence existing users who already have their configs stored.
Closes #530
> feat: change default server api and headscale ports

- pkg/views/server/apikey/notify.go
Adding a new API key using daytona api-key new no longer adds layout's padding on terminal widths less than 80 as that would cause the profile adding command to have incorrect format with spaces/new lines.
The command is now also split into separate lines with backslash to reduce the amount of needed space
Regular sized terminal:
Very narrow terminal:
> fix: api key notify format

- pkg/cmd/workspace/ssh.go
Added a prompt to users running `daytona ssh` and selecting a multi-project workspace for which project they want to ssh into instead of defaulting to first
> feat: daytona ssh project

- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
Minor UX fixes
- Changes  `daytona start` / `daytona stop` message from "Workspace started" to "Workspace start request submitted"
- Fixes single project `start/stop` commands response from "Workspace started" to "Project x from workspace y started"
- Fixed `daytona start --all` prompting the user for a workspace once they are all started
- `daytona start/stop -p projectName` now displays the help instead of prompting because of the incorrect command format
Closes #492 
> fix: start stop messages

- pkg/cmd/workspace/util/creation_data.go
fix `--multi-project` create not working
Closes #577
/claim #577
> fix: multi-project create not working

- cmd/daytona/config/const.go
- pkg/views/gitprovider/select.go
Adds required scopes help line to the `daytona git-provider add` view. Changes "More information on" label to green
Closes #565
> feat: git provider required scopes

- pkg/cmd/workspace/util/creation_data.go
Fixes regression with 2. project order number being 4.
The issue was the first additional project having the "#4" order number:
> fix: project order number

- pkg/cmd/target/remove.go
This feature enables automatic deletion of all workspaces within the target upon target removal.
This PR addresses issue #423 
/claim #423
> feat: ask user to remove workspaces when removing target

- internal/testing/docker/mocks/api_client.go
- pkg/agent/agent.go
- pkg/docker/client.go
- pkg/docker/create.go
- pkg/docker/create_test.go
- pkg/docker/destroy.go
- pkg/docker/destroy_test.go
- pkg/git/service.go
This PR adds a named volume to each project container created by the docker client.
Closes #582 
For the changes to take affect, providers will have to be updated as well.
> feat: mount volume to project container

- hack/project_image/.devcontainer/devcontainer.json
- hack/project_image/Dockerfile
Minor fixes for the default project image:
* `USER daytona` now correctly assumes the `daytona` user in the container
* Changed `CMD` to `ENTRYPOINT` to allow overrides
* Fixed devcontainer CLI install
> chore: workspace-project image fixes

- internal/testing/server/workspaces/mocks/container_registry_service.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/ServerConfig.md
- pkg/apiclient/model_server_config.go
- pkg/builder/builder.go
- pkg/builder/devcontainer.go
- pkg/builder/factory.go
- pkg/cmd/server/serve.go
- pkg/server/containerregistries/service.go
- pkg/server/containerregistries/service_test.go
- pkg/server/defaults.go
- pkg/server/types.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
- pkg/views/server/config.go
- pkg/views/server/configure.go
- pkg/workspace/project.go
This PR adds the `Builder Image` as a configuration option in `daytona server configure`. The user can now use any image as a builder image, including private images (this requires the user to add container registry credentials to the Daytona Server).
Closes #634
> feat: builder image configuration

- pkg/api/controllers/containerregistry/list.go
- pkg/views/containerregistry/list/view.go
Minor fix to completely hide the container registry password from the API response.
> fix: hide registry password from API response

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/ServerConfig.md
- pkg/apiclient/model_server_config.go
- pkg/builder/builder.go
- pkg/builder/devcontainer.go
- pkg/builder/factory.go
- pkg/cmd/server/configure.go
- pkg/cmd/server/serve.go
- pkg/containerregistry/container_registry.go
- pkg/server/defaults.go
- pkg/server/registry/service.go
- pkg/server/server.go
- pkg/server/types.go
- pkg/views/server/config.go
- pkg/views/server/configure.go
This PR introduces the option to choose a custom builder registry that was added to Daytona with `daytona cr set`. The registry will be used to store build images. Additionally, the `Build Image Namespace` option was introduced that is used when tagging and pushing build images.
Before starting the server, users will need to add 'localBuilderRegistryPort' and 'builderRegistryServer' properties to their server configuration.
The following properties should be added:
```
"localBuilderRegistryPort": 3988,
"builderRegistryServer": "local",
```
(Note: `"registryPort"` can be removed from the config file)
> **On Mac**
The file is located at: `~/Library/Application\ Support/daytona/server/config.json`.
> **On Linux**
The file is located at: `~/.config/daytona/server/config.json`
> **On Windows** …
> feat: custom builder registry configuration

- pkg/views/workspace/create/configuration.go
Just a minor fix for selecting the `Custom Image` builder in the advanced project view
> fix: custom image builder select

- docs/workspace_mode/daytona.md
- docs/workspace_mode/daytona_agent.md
- docs/workspace_mode/daytona_autocomplete.md
- docs/workspace_mode/daytona_docs.md
- docs/workspace_mode/daytona_forward.md
- docs/workspace_mode/daytona_info.md
- docs/workspace_mode/daytona_list.md
- docs/workspace_mode/daytona_start.md
- docs/workspace_mode/daytona_stop.md
- docs/workspace_mode/daytona_version.md
- hack/docs/workspace_mode/daytona.yaml
- hack/docs/workspace_mode/daytona_agent.yaml
- hack/docs/workspace_mode/daytona_autocomplete.yaml
- hack/docs/workspace_mode/daytona_docs.yaml
- hack/docs/workspace_mode/daytona_forward.yaml
- hack/docs/workspace_mode/daytona_info.yaml
- hack/docs/workspace_mode/daytona_list.yaml
- hack/docs/workspace_mode/daytona_start.yaml
- hack/docs/workspace_mode/daytona_stop.yaml
- hack/docs/workspace_mode/daytona_version.yaml
- pkg/cmd/workspacemode/workspace_mode.go
Changes the tagline for the CLI in workspace mode from
`Use the Daytona CLI to manage your project`
to
`Use the Daytona CLI to manage your workspace`
> chore: workspace mode tagline

- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/server/restart.go
- pkg/cmd/server/server.go
- pkg/server/config.go
This PR adds server log reading while its starting in daemon mode (with `daytona server`). This change aims to improve UX while starting in daemon mode to let the user know what went wrong in the process.
Closes #672 
`daytona server -y`
`daytona server restart`
`daytona server -y` (with fatal error from the server)
> feat: read server logs while starting as daemon

- go.sum
- internal/cmd/tailscale/connection.go
- internal/util/frpc.go
- pkg/api/controllers/binary/get_daytona.go
- pkg/cmd/server/serve.go
- pkg/docker/create.go
- pkg/docker/create_test.go
- pkg/provider/manager/manager.go
- pkg/provider/types.go
- pkg/server/headscale/config.go
- pkg/server/headscale/connect.go
- pkg/server/server.go
With this PR, projects that are running locally will be able to access the Server without going through FRP. This change massively improves the binary download and SSH connection for those projects.
Since the provider interface changed, installed providers will need to be updated (with `daytona provider update`)
Addresses #625 
This PR is one of 2 that will address #625. The second part of the solution will be allowing users to add a static IP address of the server and avoid FRP altogether.
> feat: direct api and headscale access

- pkg/cmd/workspace/util/creation_data.go
- pkg/views/workspace/create/configuration.go
- pkg/views/workspace/create/summary.go
- pkg/views/workspace/selection/projectrequest.go
On single project workspace creation summary is shown after the advanced configuration is opened.
On multi-project workspace creation summary is shown with detailed output after the advanced configuration is opened.
Closes #512
> fix: improve workspace creation summary view

- pkg/views/workspace/info/view.go
Adds pointer check for git status on `daytona info`
> fix: info panic on git status

- cmd/daytona/main.go
- internal/util/apiclient/api_client.go
- internal/util/apiclient/error.go
- internal/util/apiclient/error_handler.go
- pkg/api/middlewares/version.go
- pkg/api/server.go
- pkg/cmd/workspace/create.go
Expose server and client versions through response/request headers (`X-Server-Version` & `X-Client-Version`). If version mismatch is detected, user is warn of it.
Closes #666
> feat: expose server CLI version

- docs/daytona_create.md
- hack/docs/daytona_create.yaml
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/views/workspace/create/build_choice.go
- pkg/views/workspace/create/configuration.go
- pkg/views/workspace/create/summary.go
Added following single-project-only flags with short description:
`--custom-image` - create the project with the custom image passed as the flag value
this requires setting `--custom-image-user` and vice versa
`--devcontainer-path` - automatically assign the devcontainer builder with the path passed as the flag value
`--builder` - allows the user to specify the builder (currently Automatic/Devcontainer/None)
Closes #620
> feat: allow user to override workspace image at creation

- pkg/gitprovider/git_provider.go
- pkg/gitprovider/gitlab.go
Bug Fix: Using git providers hosted without HTTPS fails to clone repositories
Created another function that checks the http/https and validates it!
Closes #690
> fix: Using git providers hosted without HTTPS fails to clone repositories

- pkg/views/workspace/create/configuration.go
fix: devcontainer config file name validation issue
The Devcontainer CLI will fail if the config file is not named `.devcontainer.json` or `devcontainer.json`. Currently, our TUI allows for any path to be entered which will fail during the build process if the condition is not met.
`Error: Filename must be devcontainer.json or .devcontainer.json`
This PR addresses issue #694
> fix: devcontainer config file name validation

- pkg/docker/create_devcontainer.go
- pkg/ssh/env.go
Env variables are now passed from the host machine when reading the devcontainer config.
This change is applied to providers, not Daytona directly.
> fix: devcontainer read config environment variables

- pkg/server/defaults.go
- pkg/server/workspaces/service_test.go
bug fix: sudo dockerd removed
Atm. sudo dockerd is the default post-start command. This is no longer needed and should be removed.
Closes #716
> bug fix: sudo dockerd removed

- internal/util/path.go
Minor fix for opening a non-devcontainer project on Windows. Using `path` instead of `filepath` ensures that the path is constructed with slashes instead of backslashes.
Closes #679
> fix: project dir on windows

- pkg/gitprovider/github.go
Minor fix to list all users GitHub Orgs.
As per their API docs, the username needs to be left out if we want to list all users github orgs. If the username is provided, then only public org relations are listed.
Closes #728
> fix: list all user github orgs

- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/repository_wizard.go
- pkg/views/workspace/create/view.go
- pkg/views/workspace/selection/namespace.go
- pkg/views/workspace/selection/provider.go
- pkg/views/workspace/selection/repository.go
- pkg/views/workspace/selection/view.go
Related to --multi-project command
enhancement: frontend validation for duplicate repo entry in tui (#550)
related to --multi-project command
This PR addresses issue #550 
closes #550 
/claim #550 
> enhancement: frontend validation for duplicate repo entry in tui (#550)

- pkg/views/workspace/selection/view.go
fix: remove presence of leftover data from previous page in TUI (#592)
fix: filter input gets duplicated in full screen tui (#668)
1. consider height of other ui components ('title' header in this case) while setting window height for workspaces list.
2. set a max height for workspace selection view.
This PR addresses issue #592 and #668 
closes #592 
closes #668 
/claim #592
> fix: remove presence of leftover data from previous page in TUI (#592)

- internal/testing/git/mocks/gitservice.go
- pkg/docker/create.go
- pkg/docker/create_test.go
- pkg/git/service.go
This PR fixes a regression introduced when moving project building to the target machine. The repo is now correctly cloned on the given context (branch/commit).
Closes #740
> fix: clone repo from context

- pkg/docker/create_devcontainer.go
- pkg/docker/start_devcontainer.go
With this PR, devcontainer user commands are executed in the background when a project is started. This makes the creation process more efficient as it now skips non-blocking commands.
Closes #733
> fix: execute devcontainer user commands in the background

- pkg/builder/devcontainer/customizations.go
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/ssh.go
- pkg/ide/browser.go
- pkg/ide/vscode.go
With this PR, devcontainer vscode cusomizations (settings and extensions) are applied to relevant IDEs.
When the user uses VS Code Desktop, only `customizations["vscode"]` are used.
When the user uses VS Code Browser, `customizations["vscode", "browser", "codespaces"]` are used.
Closes #712
> feat: apply devcontainer customizations to relevant IDEs

- pkg/cmd/workspace/create.go
Removes the 3-minute workspace creation timeout.
Closes #759
> fix: remove workspace creation timeout

- pkg/cmd/workspace/code.go
This PR adds a workspace info nil check in order to fix the runtime error upon daytona code command workspace select
Closes #782
> fix: code command runtime error on select workspace

- hack/install.sh
The install.sh script contained an unnecessary continue statement that has now been removed to improve the script’s functionality.
This PR addresses issue #766
Closes #776
/claim #776
> fix: update install.sh by removing unnecessary "continue"

- pkg/cmd/apikey/list.go
`daytona api-key list -o json` works as expected
/claim #751
Closes #751
This PR addresses issue #751
> fix: api-key list -o json

- pkg/views/initial/view.go
Narrow the gradient in logo
/claim #619
Closes #619
This PR addresses issue #619
Attached below in comments
> fix: narrow the gradient in logo

- docs/daytona.md
- docs/daytona_profile.md
- docs/daytona_use.md
- hack/docs/daytona.yaml
- hack/docs/daytona_profile.yaml
- hack/docs/daytona_use.yaml
- pkg/cmd/profile/profile.go
- pkg/cmd/profile/use.go
`daytona profile` opens the help and `daytona profile use` open the TUI to switch the active profile when called without arguments or simply take the first argument -> `daytona profile use p1`
/claim #806 
Closes #806 
This PR addresses issue #806 
https://github.com/user-attachments/assets/2c19e7d7-952d-46ee-9acd-4ac24891d849
> fix: no TUI for daytona profile use

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/ServerConfig.md
- pkg/apiclient/model_server_config.go
- pkg/cmd/server/serve.go
- pkg/server/registry/service.go
- pkg/server/types.go
- pkg/views/server/config.go
- pkg/views/server/configure.go
In some use cases, users need to change the image of `library/registry`. For instance:
* In a private network, they cannot pull images from the ineternet
* The `docker hub` is blocked in some areas
So, I propose to add a config item to allow users to change the image of `library/registry`.
Users will need to set the `registryImage` property in their server `config.json` file manually.
> feat: support to set the registry image

- pkg/api/server.go
This is a fix for a bug issue raised https://github.com/daytonaio/daytona/issues/818 where the API version number in swagger document differs from Daytona version number. Version number is fixed to 0.1.0. The solution is to make it dynamic based on the github release tag
This PR addresses issue #818
> fix: update the swagger docs api version programatically

- pkg/server/workspaces/create.go
- pkg/workspace/project.go
> fix: wrong regex rules for repo names

- pkg/docker/create.go
- pkg/docker/create_image.go
- pkg/docker/create_test.go
This PR fixes the case where the user running Daytona does not have UID and GID set to 1000 and doesn't use a devcontainer project. Now the UID and GID is synced properly.
> fix: update container user uid and gid

- pkg/build/devcontainer/types.go
- pkg/docker/create_devcontainer.go
If the remote user is not set in the config, it is read from the devcontainer up result.
Closes #807 
This will require a provider update.
> fix: devcontainer remote user fallback

- pkg/server/gitproviders/gitprovider.go
If git credentials have "illegal" URL chars, relevant git operations will fail. This PR simply adds `url.QueryEscape` when getting the token and username.
Closes #837
> fix: escape git credentials

- pkg/cmd/workspace/create.go
fix: missing terminal cursor
Added a function that resets the terminal state
Closes #695
/closes #695
/claim #695
> fix: missing terminal cursor

- pkg/cmd/cmd.go
show help menu on unknown command
remove fatal crash and show help menu on unknown command
This PR addresses issue #616
closes #616
/claim #616
> feat: show help menu on unknown command

- pkg/cmd/cmd.go
Fixes regression introduced by #793. Before, if a user would run `daytona create REPO_URL -t local`, it would fail because it could not detected the appropriate command. This fix includes removing flags during the command check.
> fix: command validation for help

- docs/daytona_server_logs.md
- hack/docs/daytona_server_logs.yaml
- pkg/cmd/server/logs.go
Solution to [Allow daytona logs to read straight from the log file](https://github.com/daytonaio/daytona/issues/772#top)
/claim #772
Closes #772
> feat: read server logs directly from file

- docs/daytona_api-key_generate.md
- hack/docs/daytona_api-key_generate.yaml
- pkg/cmd/apikey/generate.go
- pkg/views/server/apikey/create.go
This PR addresses issue #748 
closes #748 
/claim #748 
> fix: remove save api key option (#748)

- pkg/gitprovider/github.go
- pkg/gitprovider/github_test.go
correctly parse branch names with slashes in GitHub Urls.
closes #843
> fix: correctly parse branch names with slashes in GitHub Urls

- pkg/cmd/agent/agent.go
bug: create daytona produces unnecessary debug logs
Fixed this bug by using if-else statement
This PR addresses issue #779 
Closes #779 
/claim #779
> bug: create daytona produces unnecessary debug log

- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/repository_wizard.go
- pkg/views/workspace/create/view.go
- pkg/views/workspace/selection/namespace.go
- pkg/views/workspace/selection/provider.go
- pkg/views/workspace/selection/repository.go
- pkg/views/workspace/selection/view.go
Remove duplicate repo validation and append occurence number to keep duplicate entries unique.
This PR addresses issue #773 
closes #773 
/claim #773
> Remove duplicate repo validation

- pkg/api/controllers/gitprovider/context.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/server.go
- pkg/apiclient/README.md
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_git_provider.go
- pkg/apiclient/docs/GitProviderAPI.md
- pkg/gitprovider/azure-devops.go
- pkg/gitprovider/azure-devops_test.go
- pkg/gitprovider/bitbucket.go
- pkg/gitprovider/bitbucket_test.go
- pkg/gitprovider/bitbucketserver.go
- pkg/gitprovider/bitbucketserver_test.go
- pkg/gitprovider/git_provider.go
- pkg/gitprovider/gitea.go
- pkg/gitprovider/gitea_test.go
- pkg/gitprovider/github.go
- pkg/gitprovider/github_test.go
- pkg/gitprovider/gitlab.go
- pkg/gitprovider/gitlab_test.go
- pkg/gitprovider/gitness.go
- pkg/gitprovider/gitness_test.go
Added a get URL from repository API route that allows passing a git repo (context) to the API to get the appropriate URL from the appropriate git provider.
Closes #865
> feat: implement get url from repository API route

- pkg/cmd/ide.go
- pkg/ide/vscode.go
User should be provided with an error if chosen ide 'vscode' for project is not installed.
This PR addresses issue #654 
closes #654 
/claim #654
> fix: inform user if vscode ide is not installed locally (#654)

- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/server/server.go
Added a note that users on linux should run `loginctl enable-linger $USER` to enable the server daemon to continue running after logging out of the machine. This is especially useful for servers running on remote machines.
> fix: add loginctl note for linux server daemon

- pkg/api/controllers/gitprovider/gitprovider.go
- pkg/cmd/gitprovider/add.go
Handling the error message for incorrect token for the `gh add` command.
closes #727
/claim #727
> fix: handle the error message for incorrect token

- pkg/cmd/server/serve.go
Added a root user check when starting the server to inform the user that we recommend running as a non-root user.
Closes #749
> fix: add a root user check on serve

- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/ssh.go
- pkg/cmd/workspace/util/workspace.go
Add workspace status check to code and ssh commands
Currently, the code and ssh commands do not check the status of the project before opening them in IDE or doing an ssh. This change adds additional checks to do the same.
This PR addresses issue https://github.com/daytonaio/daytona/issues/770
None
/claim #770
> feat: add workspace status check to code and ssh commands #821

- pkg/server/gitproviders/gitprovider.go
Minor fix to `GitProviderForUrl` interface return value for AWS CodeCommit conflict
> fix: gitprovider for url interface

- .devcontainer/postcreate.sh
- cmd/daytona/config/config.go
- pkg/cmd/server/serve.go
- pkg/server/config.go
- pkg/server/defaults.go
- pkg/server/headscale/config.go
- pkg/server/headscale/server.go
A small fix to use a different config dir when inside a devcontainer. This makes it easier to run Daytona in Daytona.
Closes #882
> chore: use different config dir in development mode

- pkg/api/server.go
- pkg/server/headscale/server.go
- pkg/server/registry/service.go
If the server port is already taken, it will be logged during the startup
/claim #676 
Closes #676 
This PR addresses issue #676 
> feat: notify users if server ports are taken

- pkg/server/registry/service.go
Check for docker requirements in  Local Container Registry Start
add check for Docker requirements in Local Container Registry Start
This PR addresses issue #724
closes #724
/claim #724
> fix: add check for Docker requirements in Local Container Registry Start

- pkg/server/config.go
- pkg/views/server/configure.go
server configuration fails to make directory
`daytona server configure` fails because it attempts to create dir on the cli. This PR moves the directory creation logic to the server.
This PR addresses issue #618
/claim #618
closes #618
> fix: server configuration fails to make directory

- pkg/cmd/projectconfig/delete.go
- pkg/cmd/projectconfig/setdefault.go
- pkg/cmd/projectconfig/update.go
- pkg/cmd/workspace/util/creation_data.go
Removes fatal err when ctrl-c-ing out of project config selection - delete, update, select
> fix: remove fatal on project config select ctrl-c

- pkg/cmd/server/daemon/daemon.go
This PR fixes and error where daytona server start in daemon mode fails if another daemon server already exists.
Closes #643
> fix: server start fails if systemd file exists

- pkg/server/registry/service.go
`LookPath` doesn't work on darwin so this PR just adds an installation guide to the docker info error message.
> fix: docker installation check

- PACKAGING.md
- README.md
Added packaging guidelines for Daytona to make distribution rules more clear to users.
> docs: add packaging guidelines

- pkg/docker/create_devcontainer.go
A minor fix for a race condition that occurs when reading the devcontainer configuration of a project. The race condition occurs when reading container logs of the container that executes the read operation.
If the container exits before logs are read, the workspace creation process fails.
Providers will need to be updated with `daytona provider update`
> fix: devcontainer read config race condition

- internal/util/apiclient/error_handler.go
Version mismatch warning displays wrong versions
The versions in the warning are swapped. I'm running the CLI on version `v0.25.1` and the server on `v0.0.0-dev`
This PR addresses issue #936 
/closes #936
> Version mismatch warning displays wrong versions

- pkg/server/workspaces/stop.go
This PR fixes a bug where the workspace was not saved properly if the telemetry was disabled.
> fix: save stopped workspace if telemetry is disabled

- pkg/ide/vscode.go
Minor fix for the home folder path when installing vscode extensions. This fixes the installation when the project is ran with the `root` user.
> fix: home folder when installing vscode extensions

- pkg/build/detect/detect.go
Fixes devcontainer auto-detect if `.devcontainer.json` should be detected
Closes #938 
Providers will need to be updated with `daytona provider update`
> fix: .devcontainer.json detection

- .devcontainer/devcontainer.json
Resolves the above error that sometimes occurs when opening daytona in a devcontainer.
> chore: mark git directory as safe in devcontainer

- docs/daytona_project-config_delete.md
- hack/docs/daytona_project-config_delete.yaml
- pkg/cmd/projectconfig/delete.go
This PR adds a `--all` flag to the `project-config delete` command so you can delete all project configurations at once. A confirmation prompt will now appear to make sure you really want to delete everything. You can also use the `--yes` flag to skip the prompt if you're sure.
Closes #890
- `/pkg/cmd/projectconfig/delete.go`
Closes #890
[Screencast_20240825_191600.webm](https://github.com/user-attachments/assets/33526f00-fae0-46fa-85fd-ca6cc5097292)
> feat: flag for the project-config delete command to delete all project configurations

- cmd/daytona/config/config.go
- internal/util/apiclient/error_handler.go
Update to the api error handling to store returned html pages as files that the user can open manually.
Closes #808
> fix: handle api errors that return html

- pkg/api/controllers/workspace/workspace.go
- pkg/cmd/workspace/code.go
- Adding validation for workspace names in the `daytona code` command.
- Enhancing error messages to provide clearer guidance, including suggesting the `daytona list` command for viewing available workspaces.
**Files changed:**
- **`pkg/cmd/workspace/code.go`**: Updated to include workspace validation and improved error handling.
Closes #859
- Before
-  After
> fix: improve error handling for daytona code command

- internal/util/time.go
Fix for some instances to correctly display created/updated times where the timestamp in the database contains a time zone.
Before:
After:
> fix: timestamp with timezone

- docs/daytona_prebuild_add.md
- hack/docs/daytona_prebuild_add.yaml
- pkg/cmd/prebuild/add.go
- pkg/cmd/prebuild/update.go
- pkg/views/prebuild/add/add.go
Adds a "Run the build once on submit?" TUI prompt when doing `daytona prebuild add` or `daytona prebuild update`
Closes #972
> fix: run prompt on prebuild add/update

- pkg/cmd/build/run.go
- pkg/cmd/prebuild/add.go
- pkg/cmd/projectconfig/add.go
- pkg/cmd/projectconfig/delete.go
- pkg/cmd/projectconfig/info.go
- pkg/cmd/projectconfig/setdefault.go
- pkg/cmd/projectconfig/update.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/views/workspace/selection/projectconfig.go
Adds an option to add a project config during `daytona prebuild add` and then continue on to set a prebuild
Closes #969 
> fix: add project config during prebuilds add flow

- docs/daytona_build_logs.md
- hack/docs/daytona_build_logs.yaml
- pkg/build/runner.go
- pkg/cmd/build/logs.go
Adds a polling function to stop reading logs once the build is published or has errored
Adds `--continue-on-completed` flag to continue reading logs and ignore the poll
Adds a newline and bolds the build success message
Closes #968
> fix: build logs UX

- internal/constants/profile.go
- pkg/views/profile/create.go
Update profile name validation to match workspace name [a-zA-Z0-9._-] (as in https://github.com/daytonaio/daytona/pull/775)
Closes #956
/claim #956
> fix: update profile name validation to match workspace name

- pkg/cmd/ide.go
- pkg/ide/cursor.go
Adds checking if the `code` binary is actually cursor and not VS Code. Additionally, improved error logging if Cursor is not found.
Closes #966, #967
> fix: opening cursor instead of vscode

- pkg/gitprovider/gitlab.go
- pkg/gitprovider/gitlab_test.go
Adds SHA property to `StaticGitContext` if the section after`commits\` is a SHA hashcode
Closes #904
/claim #904
> fix(gitlab): Configure SHA property for static git context

- pkg/api/controllers/build/build.go
- pkg/build/runner.go
- pkg/cmd/build/logs.go
Handle logging build deletion errors for docker image and db entity deletion.
Also removes "deleting" from being a completed state regarding pausing build log reading
> fix: handle logging build deletion errors

- docs/daytona.md
- docs/workspace_mode/daytona.md
- hack/docs/daytona.yaml
- hack/docs/workspace_mode/daytona.yaml
- pkg/cmd/cmd.go
Adds `daytona -v` "alias" for `daytona version`
> feat: add -v flag to root cmds

- hack/install.sh
Added a combined progress bar and spinner to visually represent the download progress, displaying both percentage completion and a graphical progress bar.
This PR addresses issue #970
/claim #970
```
(zulip-py3-venv) vamshi@LAPTOP-L0PR20E0:/mnt/c/Users/91970/Desktop/algora/daytona$ sudo hack/install.sh
Installing Daytona...
Default installation directory: /usr/local/bin
You can override this by setting the DAYTONA_PATH environment variable (ie. `| DAYTONA_PATH=/home/user/bin bash`)
Downloading Daytona binary from https://download.daytona.io/daytona/latest/daytona-linux-amd64
[⠏] Downloading... [####################################----] 91%
```
To test it use:
```
curl -sf -L https://raw.githubusercontent.com/varshith257/daytona/add-custom-install-loader/hack/install.sh | sudo bash
```
> feat: add custom installation loader to the install script

- cmd/daytona/config/const.go
- pkg/gitprovider/gitlab.go
This PR adds support for webhooks for GitLab / GitLab self-managed prebuilds. It implements five methods namely webhook get, register, unregister, comparing commit ranges and parsing event data. 
closes #993 
/claim #993
https://github.com/user-attachments/assets/53ebe944-88f5-44bc-afa1-f2c4ef3dc467
> feat: Support for Webhook events for GitLab/GitLab self-managed prebuilds

- docs/daytona_create.md
- docs/daytona_project-config_add.md
- hack/docs/daytona_create.yaml
- hack/docs/daytona_project-config_add.yaml
- pkg/cmd/projectconfig/add.go
- pkg/cmd/projectconfig/update.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/workspace.go
- pkg/views/build/info/view.go
- pkg/views/projectconfig/info/view.go
- pkg/views/projectconfig/list/view.go
- pkg/views/util/build_choice.go
- pkg/views/workspace/create/configuration.go
- pkg/views/workspace/create/summary.go
Allows for uninteractive creation of project configs by passing the same flags that work for `daytona create`.
Adds environment variables flag for both `daytona create` and `daytona project-config add`
> feat: uninteractive project config creation

- pkg/cmd/projectconfig/add.go
Fixes a panic that occurs when the image/user isn't set when doing `daytona project-config add` by adding a nil check
> fix: pc add image user nil check

- pkg/cmd/workspace/util/creation_data.go
Daytona create now correctly fetches the custom image/user when a project config is selected instead of using the default ones
> fix: fetch image user from project config on create

- pkg/views/workspace/selection/gitprovider.go
Fixes Choose a Provider to Choose a Git Provider
Renames the file provider.go -> gitprovider.go
Closes #1028
> fix: choose git provider label

- internal/util/apiclient/websocket_log_reader.go
- pkg/cmd/workspace/create.go
- pkg/views/logs/display.go
- pkg/views/styles.go
Makes the logs print out "PROVIDER |" instead of "WORKSPACE |" and skip the checkmark when the source is the provider.
Closes #1029 
Closes #1031
> feat: add provider prefix option to logs

- internal/util/env_vars.go
- pkg/cmd/server/daemon/daemon.go
1.Add `GetEnvVarsFromShell()` to retrieve environment variables 
2.Set EnvVars property in [config](https://pkg.go.dev/github.com/kardianos/service@v1.2.2#Config) of github.com/kardianos/service](https://pkg.go.dev/github.com/kardianos/service@v1.2.2) to consider env variables. 
This PR addresses issue #1036 
> fix: consider env variable while running `daytona server start`

- docs/daytona_ssh.md
- docs/workspace_mode/daytona.md
- docs/workspace_mode/daytona_expose.md
- hack/docs/daytona_ssh.yaml
- hack/docs/workspace_mode/daytona.yaml
- hack/docs/workspace_mode/daytona_expose.yaml
- internal/util/log_writer.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/ssh-proxy.go
- pkg/cmd/workspace/ssh.go
- pkg/cmd/workspacemode/expose.go
- pkg/cmd/workspacemode/workspace_mode.go
- pkg/ide/terminal.go
- Local workspaces are now accessed directly by forward ssh traffic with docker exec
- The ssh command now allows direct command execution through its arguments
These changes represent a significant performance improvement when working with local workspaces.
Closes #982
> feat: direct ssh access to local workspaces

- internal/util/apiclient/api_client.go
- pkg/cmd/provider/install.go
- pkg/cmd/provider/list.go
- pkg/cmd/provider/uninstall.go
- pkg/cmd/provider/update.go
- pkg/cmd/target/list.go
- pkg/cmd/target/remove.go
- pkg/cmd/target/set.go
- pkg/cmd/workspace/create.go
- pkg/views/provider/select.go
- pkg/views/provider/view.go
During `daytona target set`, let users choose a provider that hasn't been installed yet. If selected, the provider will get installed right away as a part of the same TUI flow.
Minor overdue refactor/cleanups
Closes #1030
> feat: install provider during target set

- pkg/server/downloads.go
Added a `Stat` check to the binary before serving it to projects. The stat check makes sure that the binary can be read so that the request doesn't fail with 403. If the file can not be read, the server will proceed to download the appropriate binary from our registry.
Closes #1034
> fix: check binary permissions before serving

- internal/testing/gitprovider/mocks/git_provider.go
- pkg/gitprovider/git_provider.go
- pkg/gitprovider/github.go
- pkg/gitprovider/gitlab.go
- pkg/server/projectconfig/prebuild.go
- pkg/server/projectconfig/prebuild_test.go
Removes the owner param string from get commits range and changes GitHub's implementation to use repo.Owner instead
> refactor: remove owner param from get commits range

- docs/daytona_code.md
- docs/daytona_ssh.md
- hack/docs/daytona_code.yaml
- hack/docs/daytona_ssh.yaml
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/ssh.go
- pkg/views/ide/start_workspace.go
ask user to start workspace if daytona code or ssh cmd is run for a stopped project
closes #914
/claim #914
> feat: add a workspace start prompt in daytona code for stopped projects

- pkg/server/downloads.go
Stat apparently doesn't throw if the user doesn't have permission to read the file so switched to checking with `os.Open`.
> fix: use open instead of stat to check permissions

- cmd/daytona/config/ssh_file.go
Following the thread [here](https://arc.net/l/quote/jfcxvtpt) it was clear that `daytona ssh` command won't work properly if `Include dayonta_config` line was not at the top of the `.ssh/config` file. That's exactly what this PR ensures.
> fix: move include daytona config to first line

- pkg/cmd/cmd.go
- pkg/cmd/ide.go
- pkg/cmd/workspace/code.go
- pkg/telemetry/cli_events.go
- track which IDE is used when opening a project
- track which IDE is set when changing the default
This will give us more insight into which IDEs are used with Daytona. The insights that comes from this will prove valuable in shaping and prioritizing roadmap targets.
> telemetry: track IDE id

- docs/daytona_create.md
- hack/docs/daytona_create.yaml
- pkg/cmd/workspace/create.go
Removed the obsolete `provider` flag from the `create` command.
Closes #1049
> fix: remove obsolete provider flag from create command

- pkg/gitprovider/bitbucket.go
This PR corrects options used for fetching repository branches for bitbucket as they are provided differently based on the type of creating project in daytona.
> fix: fetch branches with correct options provided from bitbucket

- internal/testing/server/workspaces/mocks/provisioner.go
- pkg/api/controllers/workspace/workspace.go
- pkg/provisioner/info.go
- pkg/provisioner/provisioner.go
- pkg/server/purge.go
- pkg/server/workspaces/get.go
- pkg/server/workspaces/list.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
Running `daytona list -v` and `daytona info`/`daytona code` no longer hangs indefinitely in case a workspace/project is impossible to reach (e.g. droplet is shut down or theres network issues)
> fix: add timeout to get workspace info from provider

- pkg/api/controllers/projectconfig/project_config.go
This pull request addresses issue #933, where the Daytona server improperly logs a 404 error when a repository is created without an existing project config. The current behavior is misleading, as the absence of a project config should not be treated as a failure.
Closes #933 
/claim #933
BEFORE 
AFTER
> fix: Handling and Logging of Missing Project Config on Repository Creation (#933)

- pkg/views/workspace/selection/view.go
- pkg/views/workspace/selection/workspace.go
Pressing "x" during daytona start/stop/code/info workspace selections would still visually "mark" workspaces for deletion because a check was missing for this being a multi-workspace selection action
Closes #1042
> fix: multi ws select marking

- internal/util/apiclient/api_client.go
- pkg/api/controllers/workspace/workspace.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_workspace.go
- pkg/apiclient/docs/WorkspaceAPI.md
- pkg/cmd/ports/forward.go
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/info.go
- pkg/cmd/workspace/ssh-proxy.go
- pkg/cmd/workspace/ssh.go
- pkg/cmd/workspacemode/info.go
- pkg/server/workspaces/get.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
This PR adds verbose argument to get workspace info command which consequently fixes `daytona delete -f` command.
Closes #1074
> fix: add verbose arg to get ws info

- pkg/ide/jetbrains.go
Before this PR, we assumed that the user inside the project is `daytona`.  Now we correctly detect the home folder of the user inside the container.
Closes #1079
> fix: detect correct user when opening jetbrains IDEs

- pkg/gitprovider/bitbucket.go
Getting repository pull requests would fail due to the poorly constructed full repository name
> fix: bitbucket get repo prs

- cmd/daytona/config/const.go
- go.mod
- go.sum
- pkg/gitprovider/bitbucket.go
- pkg/gitprovider/bitbucketserver.go
- pkg/server/projectconfig/prebuild.go
This PR adds support for webhooks for Bitbucket prebuilds. It implements five methods namely webhook get, register, unregister, comparing commit ranges and parsing event data. Since the default Bitbucket package does not support parsing Push events, I have used `"github.com/go-playground/webhooks"` instead. Additionally, this PR enhances error handling by making it more detailed and addresses issues with capitalized error messages.
closes #994 
/claim #994
https://github.com/user-attachments/assets/2fd121f0-282d-405a-8b65-33ebabdcc29d
In the file pkg/gitprovider/bitbucket.go, I had to comment out 
```
owner, repo, err := g.getOwnerAndRepoFromFullName(repositoryId)
if err != nil {
return nil, err
}
```
because it was causing this error:
> feat: Add support for Bitbucket Webhook events

- pkg/cmd/workspace/create.go
- pkg/ide/browser.go
- pkg/ide/cursor.go
- pkg/ide/vscode.go
Fixes a regression introduced with https://github.com/daytonaio/daytona/pull/1077 that broke extension installs if `--code` was used with `daytona create`.
Closes #1083
> fix: install code extensions on create

- cmd/daytona/config/const.go
- docs/daytona_code.md
- docs/daytona_create.md
- hack/docs/daytona_code.yaml
- hack/docs/daytona_create.yaml
- pkg/cmd/ide.go
- pkg/cmd/workspace/code.go
- pkg/ide/fleet.go
This PR adds support for JetBrains Fleet IDE. The SSH connection is set up via the URI provided by the [Fleet CLI](https://www.jetbrains.com/help/fleet/launch-from-cli.html#connecting-to-ssh-with-fleet-uri-handler) through the browser route.
closes #1001 
/claim #1001
https://github.com/user-attachments/assets/f37558c0-7111-45fb-8ad3-de2a0d6fc329
> feat(ide): Support for JetBrains Fleet IDE

- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/ssh-proxy.go
This PR fixes ssh access when using a remote profile. The bug was caused by the switch in directly accessing workspaces with docker exec but that should only be applied when using the default local profile.
> fix: ssh access with remote profiles

- pkg/cmd/target/remove.go
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
- pkg/cmd/workspacemode/start.go
- pkg/cmd/workspacemode/stop.go
- pkg/views/util/spinner.go
This PR adds a spinner to `daytona start`, `daytona stop` and `daytona delete` commands 
This PR addresses issue #915
closes #915
/claim #915
> feat: add spinner to workspace start, stop and delete

- cmd/daytona/config/const.go
- pkg/gitprovider/gitea.go
This PR adds support for webhooks for Gitea prebuilds. It implements five methods: webhook get, register, unregister, comparing commit ranges and parsing event data.
closes #996 
/claim #996  
https://github.com/user-attachments/assets/da1e8441-8a52-491c-aa46-a096ad5f4999
> feat: Support for Gitea Webhook Prebuilds

- docs/daytona_provider_install.md
- hack/docs/daytona_provider_install.yaml
- pkg/cmd/provider/install.go
Added a suggestion to immediately add a target after installing a provider.
Closes #1070
The suggestion is not triggered if the provider has targets already set on the server (e.g. it comes with default targets).
> feat: suggest adding a target after provider install

- pkg/docker/start_image.go
If the image contains devcontainer.metadata label, the provider will execute all the features entrypoints found in the label.
Closes #1106 
This PR requires updates to all the providers!
With this PR, only the image entry point logic is built using the devcontainer. The logic still needs to be implemented for the plain Docker images.
A new Issue should be created to resolve this.
> feat: entrypoint execution for workspace image

- pkg/api/controllers/gitprovider/branches.go
- pkg/api/controllers/gitprovider/context.go
- pkg/api/controllers/gitprovider/gitprovider.go
- pkg/api/controllers/gitprovider/namespaces.go
- pkg/api/controllers/gitprovider/pull_requests.go
- pkg/api/controllers/gitprovider/repositories.go
- pkg/api/controllers/gitprovider/user.go
- pkg/api/controllers/utils.go
- pkg/gitprovider/aws-codecommit.go
- pkg/gitprovider/azure-devops.go
- pkg/gitprovider/bitbucket.go
- pkg/gitprovider/bitbucketserver.go
- pkg/gitprovider/gitea.go
- pkg/gitprovider/github.go
- pkg/gitprovider/gitlab.go
- pkg/gitprovider/gitness.go
- pkg/gitprovider/gitnessclient/gitness_client.go
Returns client-side HTTP response code & adds error messages according to the error.
issue #934 
/claim #934
> refactor: http status code and error in api(daytonaio#934)

- pkg/cmd/workspace/util/branch_wizard.go
Fixes an issue for namespaces that have `/` or when gitlab subgroups where used. The namespace is now correctly escaped before sending the request.
> fix: escape git namespace when fetching from API

- pkg/build/devcontainer/types.go
- pkg/docker/create_devcontainer.go
Minor fix to the devcontainer command definition. Commands are now correctly typed as `interface{}` since they can be a string, array or object.
Closes #1011 
All providers will require an update
> fix: devcontainer command definition

- pkg/cmd/workspace/util/branch_wizard.go
- pkg/views/workspace/selection/checkout.go
Ctrl-c-ing out of Cloning Options selection screen in the TUI used assume the default checkout option instead of cancelling the operation
> fix: ctrl-c out of cloning option selection

- pkg/views/initial/view.go
Fixes ctrl-c-ing out of the `daytona` command to simply exit instead of defaulting to the first command in the list
> fix: ctrl-c out of daytona command

- pkg/cmd/build/run.go
Fixes the verb in the title when running `daytona build run` from "Update" to "Build"
> fix: build run project config selection verb

- cmd/daytona/config/ssh_file.go
Adds double quotes to ProxyCommand's binary file location to fix ssh-ing on Windows
> fix: ssh proxycommand file location windows

- internal/cmd/tailscale/connection.go
- internal/testing/agent/mocks/apiserver.go
- internal/util/workspace.go
- pkg/build/devcontainer.go
- pkg/build/factory.go
- pkg/cmd/ports/forward.go
- pkg/cmd/projectconfig/add.go
- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/workspace/create.go
- pkg/docker/create_devcontainer.go
- pkg/gitprovider/aws-codecommit.go
- pkg/gitprovider/bitbucket.go
- pkg/gitprovider/bitbucketserver.go
- pkg/gitprovider/gitea.go
- pkg/gitprovider/gitnessclient/gitness_client.go
- pkg/ide/jetbrains.go
- pkg/ide/jupyter.go
- pkg/os/os.go
- pkg/server/projectconfig/prebuild.go
- pkg/server/registry/service.go
- pkg/ssh/user.go
- pkg/tailscale/connection.go
- pkg/tailscale/tunnel/tunnel.go
- pkg/views/workspace/create/summary.go
Changes all call of `fmt.Errorf` that don't include any dynamic string formatting to instead use `errors.New` for consistency
> refactor: use errors new for simple strings

- pkg/cmd/workspace/ssh.go
This PR introduces a fix when selecting a project to SSH in from multi-project workspace.
Issue fixed is that no matter which project was chosen, always the first one was selected, now it is selected one.
Closes #1128 
https://github.com/user-attachments/assets/aaee284e-0113-4d29-85b1-c44ee5b6ca34
> fix: add selected project name to ssh on multi project workspace

- pkg/ide/cursor.go
- pkg/ide/vscode.go
Fixing the order of flags when calling the VSCode/Cursor CLI prevents the command from not doing anything
> fix: daytona code windows for vscode-like ides

- docs/daytona_create.md
- docs/daytona_project-config_add.md
- hack/docs/daytona_create.yaml
- hack/docs/daytona_project-config_add.yaml
- pkg/cmd/projectconfig/add.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/add_from_config.go
- pkg/cmd/workspace/util/branch_wizard.go
- pkg/cmd/workspace/util/workspace.go
This PR adds the ability to pass multiple repository urls (or project config names) to the `daytona create` command. This adds the ability to create a multi-project workspace non-interactively.
> feat: support creating multiple projects non-interactively

- pkg/build/devcontainer.go
Small fix for running builds. The `daytonaio/workspace-project` image is now pulled before starting the building process.
Closes #1120
> fix: pull image before building

- docs/daytona_build_delete.md
- hack/docs/daytona_build_delete.yaml
- internal/testing/server/workspaces/mocks/build_service.go
- pkg/api/controllers/build/build.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_build.go
- pkg/apiclient/docs/BuildAPI.md
- pkg/apiclient/docs/BuildBuildState.md
- pkg/apiclient/model_build_build_state.go
- pkg/build/build.go
- pkg/build/runner.go
- pkg/cmd/build/delete.go
- pkg/server/builds/service.go
- pkg/server/builds/service_test.go
- pkg/server/projectconfig/prebuild.go
- pkg/server/projectconfig/prebuild_test.go
- pkg/server/purge.go
Adds a force flag to the `daytona build rm` command
Backend includes adding params to endpoints for deleting all builds, deleting a specific build and deleting all builds for a prebuild
> feat: force build deletion

- Makefile
The Makefile can be used to easily build daytona for different OSs and architectures This is especially useful for developing on non-linux machines
> chore: add a Makefile

- go.mod
- pkg/views/server/apikey/notify.go
With this PR, the command that is supposed to be run after `daytona api-key new` is automatically copied to the users clipboard.
Closes #957
> feat: auto-copy api key to clipboard

- docs/daytona_prebuild_add.md
- hack/docs/daytona_prebuild_add.yaml
- pkg/cmd/prebuild/add.go
- pkg/views/prebuild/add/add.go
This PR resolves an issue where build run prompt was appearing even when the `--run` flag was specified
closes #1129
> fix: prebuild run prompt if run flag is provided

- cmd/daytona/config/const.go
- pkg/gitprovider/azure-devops.go
This PR adds support for webhooks for Azure DevOps prebuilds. It implements five methods: webhook get, register, unregister, comparing commit ranges and parsing event data.
closes #998 
/claim #998
https://github.com/user-attachments/assets/0cd9fed1-3c80-421c-a826-a5ff5288d858
> feat: Added support for Azure DevOps Prebuild Webhooks

- CONTRIBUTING.md
Fixed broken Code of Conduct link
This pull request addresses the issue of a broken link in the repository’s documentation. The previous link to the Code of Conduct resulted in a 404 Page Not Found error.
Motivation and Context:
The Code of Conduct is an important document that outlines the expected behavior of contributors. Ensuring that this link works correctly is essential for maintaining a welcoming and informative environment for all contributors.
##Dependencies:
No additional dependencies are required for this change.
- [✅ ] I have made corresponding changes to the documentation
Closes #1143
> fix: broken code of conduct link

- pkg/ide/vscode.go
auto install remote SSH extension if it is not already installed in user's `vscode`
closes #1094
> feat: auto install remote SSH extension in vscode

- pkg/gitprovider/bitbucketserver.go
- pkg/server/gitproviders/gitprovider.go
Because, in the creation process, the gitprovider is expected to parse the clone url, the bitbucket context parsing would fail. This PR adds support for parsing the clone url as well. Additionally, refactored how git providers are fetched for URLs which was part of the issue.
> fix: bitbucket server context parse

- pkg/gitprovider/bitbucket.go
Fixes missing repos when listing repos for Bitbucket in the TUI
> fix: bitbucket repo list missing entries

- pkg/gitprovider/bitbucket.go
Fixes an issue with incorrectly formed Bitbucket PR options argument properties that lead to 404 errors
> fix: bitbucket pr list options argument

- pkg/cmd/workspace/create.go
This PR introduces a spinner with a timeout and appropriate error message if tailscale takes more than usual to create a connection.
Closes #450
> feat: add spinner when tailscale takes longer than ususal

- docs/workspace_mode/daytona.md
- docs/workspace_mode/daytona_forward.md
- hack/docs/workspace_mode/daytona.yaml
- hack/docs/workspace_mode/daytona_forward.yaml
- pkg/cmd/workspacemode/forward.go
The tailscale forward inside a workspace/project was redundant so this PR removes that and makes public forwarding the default behavior.
removed the public flag from forward inside a workspace/project
Closes #1156
> feat: port forward in workspacemode is public by default

- internal/util/apiclient/api_client.go
- pkg/cmd/purge.go
- pkg/views/config/view.go
Fixes getting the config client ID so it's consistent everywhere. Before this PR, the client ID was correctly fetched only in the root command (which allowed overriding with `DAYTONA_CLIENT_ID`)
> fix: config client id getting

- pkg/views/workspace/create/view.go
Adds a spinner to the "Enter a custom repository URL" form's validation
Closes #1155
> feat: spinner during repo url validation

- pkg/gitprovider/azure-devops.go
Fixes Server panic when running `daytona gp add`, choosing Azure DevOps and entering invalid inputs (e.g. "test" and "test")
Closes #1141
> fix: azure devops add invalid input panic

- pkg/cmd/purge.go
If `daytona purge` fails upon deleting autocompletion data, only error is output to user instead of fataling.
Closes #594
> fix: output error when purging autocompletion data

- pkg/cmd/cmd.go
- pkg/cmd/workspacemode/workspace_mode.go
This PR adds flag name tracking to our telemetry.
**NOTE:** Only flag names are tracked, not flag values.
> telemetry: track used flag names

- pkg/git/service.go
This PR sets the safe.directory value in the global gitconfig to the project dir. This way, users won't have to mark it themselves after creating a project in some scenarios.
> feat: always mark project dir as safe in git

- pkg/gitprovider/git_provider.go
Adds a len check to the abstract git provider context parsing that would cause a server panic.
Before: 
Now:
> fix: server panic on invalid repo url

- internal/apikeys/functions.go
- internal/util/hash.go
- pkg/docker/create_devcontainer.go
Fix for creating devcontainer compose projects. Before, docker compose would get lifted twice because of the different project names.
All providers will need to be updated.
> fix: devcontainer compose creation

- pkg/cmd/cmd.go
Fixes a leftover version command Run instead of RunE call
Closes #1172
> fix: version flag cmd RunE

- hack/install.sh
Checking for "daytona" in the process list wouldn't be a good way to check for the server because of the other possible active daytona commands. Now the script checks for "daytona serve"/"daytona server"
> fix: correctly check for server running in install script

- internal/testing/gitprovider/mocks/git_provider.go
- pkg/gitprovider/aws-codecommit.go
- pkg/gitprovider/aws-codecommit_test.go
- pkg/gitprovider/azure-devops.go
- pkg/gitprovider/azure-devops_test.go
- pkg/gitprovider/bitbucket.go
- pkg/gitprovider/bitbucket_test.go
- pkg/gitprovider/bitbucketserver.go
- pkg/gitprovider/bitbucketserver_test.go
- pkg/gitprovider/git_provider.go
- pkg/gitprovider/gitea.go
- pkg/gitprovider/gitea_test.go
- pkg/gitprovider/github.go
- pkg/gitprovider/github_test.go
- pkg/gitprovider/gitlab.go
- pkg/gitprovider/gitlab_test.go
- pkg/gitprovider/gitness.go
- pkg/gitprovider/gitness_test.go
- pkg/server/gitproviders/gitprovider.go
- pkg/server/gitproviders/service.go
This PR adds a `CanHandle` method to the `GitProvider` interface that is used to check if a git provider can handle a certain repo url. With this change, the appropriate provider is now always returned when requested for a certain URL.
> fix: properly check if git provider can handle repo url

- docs/daytona_build_logs.md
- hack/docs/daytona_build_logs.yaml
- internal/util/apiclient/websocket_log_reader.go
- internal/util/log_reader.go
- pkg/api/controllers/log/websocket.go
- pkg/cmd/build/logs.go
This PR fixes log websocket log reading. Now the logs are correctly read and the connection correctly cleaned up when the `--follow` flag is not used. This ensures a consistent behavior where the logs are always correctly stopped once the file is fully read.
Closes #1174 
Removed `continue-on-completed` flag from the `build logs` command. Because the logs are now read correctly, the flag 
becomes obsolete
> fix: inconsistency with non-follow log reading

- pkg/views/initial/view.go
Corrects the height of the initial screen so that the bottom option ("view all commands") is visible
Before:
After:
> fix: entry not visible in initial screen

- pkg/cmd/purge.go
Fixes an issue where there user can run `daytona purge` and ignore the "Please stop the Daytona Server" message which would lead to unexpected behavior
> fix: prevent purge if server is active

- pkg/api/middlewares/version.go
- pkg/api/server.go
- pkg/cmd/cmd.go
- pkg/cmd/purge.go
- pkg/cmd/server/serve.go
- pkg/posthogservice/service.go
- pkg/provider/manager/manager.go
- pkg/server/downloads.go
- pkg/server/server.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/start.go
- pkg/telemetry/telemetry.go
- pkg/workspace/project/project.go
- pkg/workspace/workspace.go
Just a small refactor that sets the server version in the entrypoint (`serve`) instead of being hardcoded to `internal.Version`. This change makes it easier for tools implementing Daytona as a lib to set the version of the server.
> refactor: server version from entrypoint

- internal/util/apiclient/websocket_log_reader.go
Minor fix for a regression introduced with https://github.com/daytonaio/daytona/pull/1182. This PR prevents logging empty log entries that are sent when the websocket connection closes.
> fix: don't log empty log entry

- pkg/ide/vscode.go
Fixes a panic in VSCode customizations var property access
> fix: vscode customizations panic

- pkg/views/target/set.go
- fix custom path handling
- add property description
- add selection tip
- handle no results from read dir
> fix: target set file path improvements

- pkg/api/server.go
- pkg/cmd/purge.go
- pkg/cmd/server/serve.go
- pkg/cmd/server/server.go
- pkg/server/headscale/server.go
- pkg/server/purge.go
- pkg/server/registry/service.go
- pkg/server/server.go
- pkg/server/types.go
This is a small logical refactor that moves responsibility of starting the FRP connection into their respective components. Additionally, starting the headscale server and local CR is now done in the entrypoint (`serve`) rather than in the server start method. Since those components are self-contained, they should be started outside of the server and provided as a dependency to the server itself. This will also enable us to connect to external headscale servers since the Daytona server won't manage one by itself.
> refactor: server start

- pkg/api/controllers/binary/get_daytona.go
- pkg/common/get_daytona_script.go
- pkg/common/get_daytona_script_test.go
Minor refactor that moves the `GetDaytonaScript` function to the `common` package so it can be reused by other applications.
> refactor: move get daytona script to common

- pkg/cmd/workspace/create.go
This PR fixes spinner trigger time by setting it to 15 seconds instead of 3 seconds and by setting timeout for tailscale connection upon workspace creation from 1 to 2 minutes.
> fix: set spinner trigger time to 15 seconds

- pkg/agent/tailscale/server.go
- pkg/server/headscale/connect.go
This PR fixes an issue where tsnet files were not properly purged because tsnet server was creating its own directory by default due to server directory not being set
Closes #764 
Users can delete the old tailscale directory found at:
Linux: `~/.config/tsnet-daytona`
Mac: `~/Library/Application\ Support/tsnet-daytona`
Windows: `C:\Users\[USER]\AppData\Roaming\tsnet-daytona`
> fix: add tsnet directory for proper purge

- README.md
- docs/daytona_create.md
- hack/docs/daytona_create.yaml
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/start.go
This PR makes daytona create open the IDE by default, replacing the `--code` flag with `--no-ide` to opt out.
Removed `--code` flag from the create command. The IDE now opens by default. Users can now pass `--no-ide` flag if they don't wish to open IDE immediately after workspace creation.
---
closes #1203
> feat: open IDE by default on daytona create

- internal/util/apiclient/websocket_log_reader.go
- pkg/cmd/logs.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
- pkg/logs/project.go
- pkg/logs/workspace.go
This PR enhances the UX by reading workspace and project logs on start and stop. I've implemented time-stamps to logs of workspace and project as [breakpoints](https://github.com/daytonaio/daytona/issues/593#issuecomment-2228009616) and logic to handle those.
closes #593
/claim #593
The logs for ending a workspace/project do not function at this time because there is no implementation of logger for `daytona stop WS`, which is visible [here](https://github.com/daytonaio/daytona/blob/44dfd6118509b65ef5ac64722339a62a532fca79/pkg/server/workspaces/stop.go#L14).
> feat: Read Workspace and Project logs on Start-Stop

- pkg/api/controllers/provider/dto/dto.go
- pkg/api/controllers/provider/list.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/Provider.md
- pkg/apiclient/docs/ProviderProviderInfo.md
- pkg/apiclient/model_provider.go
- pkg/apiclient/model_provider_provider_info.go
- pkg/cmd/provider/install.go
- pkg/cmd/provider/list.go
- pkg/cmd/target/remove.go
- pkg/cmd/target/set.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/get_target.go
- pkg/db/dto/provider_target.go
- pkg/provider/manager/manifest.go
- pkg/provider/types.go
- pkg/views/provider/list.go
- pkg/views/provider/select.go
- pkg/views/provider/view.go
- pkg/views/target/select.go
- pkg/views/target/set.go
- pkg/views/target/view.go
Allow installing new provider and adding a target as a part of the `daytona create` flow.
Adds provider labels to all provider views (the manifest has been updated).
Closes #1204 
> feat: add provider and target during create, provider labels

- pkg/cmd/workspace/create.go
Moves the "Request submitted" message during `daytona create` to after the target selection screen.
The reason is that if the user exited the target selection screen, it would seem the request had been submitted regardless
> fix: move request submitted message after target selection screen

- docs/daytona_git-providers_delete.md
- hack/docs/daytona_git-providers_delete.yaml
- pkg/cmd/gitprovider/delete.go
Adds `daytona git-provider remove --all` flag
> feat: all flag for git provider remove command

- docs/daytona_git-providers.md
- docs/daytona_git-providers_delete.md
- docs/daytona_git-providers_update.md
- hack/docs/daytona_git-providers.yaml
- hack/docs/daytona_git-providers_delete.yaml
- hack/docs/daytona_git-providers_update.yaml
- pkg/cmd/gitprovider/add.go
- pkg/cmd/gitprovider/gitprovider.go
- pkg/cmd/gitprovider/update.go
- pkg/views/gitprovider/select.go
Adds the `daytona git-provider update` command which allows users to update an existing Git provider config's token after it e.g. expired or update another property in the future.
Removes `update` from aliases for `add`
Minor refactors to the view functions
> feat: update git provider command

- docs/daytona_create.md
- docs/daytona_project-config_add.md
- hack/docs/daytona_create.yaml
- hack/docs/daytona_project-config_add.yaml
- pkg/cmd/gitprovider/add.go
- pkg/cmd/gitprovider/update.go
- pkg/cmd/projectconfig/add.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/workspace.go
- pkg/db/dto/git_provider.go
- pkg/server/gitproviders/gitprovider.go
- pkg/views/gitprovider/select.go
Changes `daytona create`'s flag from `--git-provider-config-id` to `--git-provider-config`
`daytona create --git-provider-config` now accepts both Git provider config ID's and aliases.
Aliases are now globally unique - to-be-duplicates have a number appended to them to differentiate
Flag rename would've been a "breaking change" but there hasn't been a release of it yet
Drafted until #1228 is merged - missing frontend alias validation and database uniqueness validation
> feat: accept git provider aliases flag and make them unique

- internal/testing/server/workspaces/mocks/git_provider_service.go
- pkg/agent/agent.go
- pkg/api/controllers/gitprovider/gitprovider.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/middlewares/auth.go
- pkg/api/server.go
- pkg/apiclient/README.md
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_git_provider.go
- pkg/apiclient/docs/GitProviderAPI.md
- pkg/build/mocks/gitprovider_config_store.go
- pkg/build/runner.go
- pkg/build/runner_test.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/cmd/workspace/util/repository_wizard.go
- pkg/cmd/workspacemode/git_cred.go
- pkg/server/gitproviders/config.go
- pkg/server/gitproviders/gitprovider.go
- pkg/server/gitproviders/service.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service_test.go
When the user has e.g. two GitHub Git providers registered, they will now be prompted on which one to use for repositories accessible to both. Applies to both daytona create <REPO_URL> and daytona create
Minor refactors along the way
> Git provider retrieval refactor

- pkg/views/gitprovider/select.go
Fixes `daytona git-provider update` frontend validation for "Alias" failing when being left unchanged
> fix: git provider update alias

- pkg/server/projectconfig/prebuild.go
Fixes validation to ensure prebuilds are unique per branch
> fix: ensure prebuild is unique per branch

- pkg/server/gitproviders/service.go
This PR fixes a nil pointer dereference exception thrown when trying to parse git provider base api url.
> fix: resolve nil pointer dereference on base api url

- pkg/cmd/cmd.go
- pkg/cmd/server/serve.go
- pkg/server/headscale/config.go
- pkg/server/headscale/connect.go
- pkg/server/headscale/server.go
Fix scenarios where the `daytona serve` command would hang forever after ctrl+C.
Closes #1209
> fix: server stop hanging

- pkg/views/build/list/view.go
- pkg/views/containerregistry/list/view.go
- pkg/views/prebuild/list/view.go
- pkg/views/profile/list.go
- pkg/views/projectconfig/list/view.go
- pkg/views/provider/list.go
- pkg/views/server/apikey/list.go
- pkg/views/target/list/view.go
- pkg/views/util/table.go
- pkg/views/workspace/list/view.go
Makes all 9 "list" components use the same util function for displaying the list
> refactor: reuse the list component across the cli

- docs/daytona_prebuild_add.md
- docs/daytona_prebuild_update.md
- hack/docs/daytona_prebuild_add.yaml
- hack/docs/daytona_prebuild_update.yaml
- pkg/cmd/prebuild/add.go
- pkg/cmd/prebuild/update.go
- pkg/server/projectconfig/prebuild.go
In the cobra command added the flags 
```  
daytona update <Project Config>  <PrebuildID>  --branch=main --retention=300 --commit-interval=60 --trigger-files="file1.go,file2.go" --run
```
```
daytona prebuild add <Project Config>  --branch=main --retention=30 --commit-interval=60 --trigger-files="file1.go,file2.go" --run  
```
This PR fixes #985 
@quest-bot loot #985
> feature: Added the support for the flags

- pkg/api/controllers/provider/install.go
- pkg/cmd/provider/install.go
- pkg/os/download.go
- pkg/provider/manager/installer.go
- pkg/provider/manager/manager.go
- pkg/server/downloads.go
- pkg/server/providers.go
- pkg/server/server.go
- pkg/views/util/spinner.go
fix: allow ctrl+c in provider install
Closes #1044
> fix: allow ctrl+c in provider install

- cmd/daytona/config/config.go
- pkg/agent/agent.go
- pkg/cmd/cmd.go
- pkg/cmd/profile/add.go
- pkg/cmd/server/serve.go
Instead of the config being generated by `daytona serve` it is now generated whenever requested with `GetConfig`. This ensures that the config is always available without having to run `daytona serve` first.
> refactor: default config generation

- pkg/cmd/workspace/util/creation_data.go
Adding a Gitlab repo when only a Github provider is registered by selecting the "Enter a custom repository url" or "Create from Sample" option would result in an incorrect placeholder Git provider config in the project config.
> fix: git provider config id when entering custom repo or sample

- pkg/cmd/gitprovider/list.go
- pkg/views/gitprovider/info/view.go
- pkg/views/gitprovider/list/view.go
Git provider config list view now uses the same table layout as other commands allowing us to display missing information - username/base API URL
> feat: improve git provider config list view

- pkg/views/util/help.go
- pkg/views/util/text_wrapper.go
- pkg/views/workspace/create/view.go
In this issue #1166  we need to make the text wrapped so that for all the terminal sizes we can able to see it. It was added to it. 
closes #1166 
@quest-bot loot #1166
> fix: Wrap text on the error

- pkg/cmd/gitprovider/list.go
This PR adds wrapping to the no git provider found message
Closes #1259 
> fix: wrap no git providers found message

- pkg/cmd/gitprovider/delete.go
this PR adds a confirmation prompt for removing git providers. Prompt can be skipped by passing `--yes` flag
closes #1256
> feat: add confirmation prompt for removing git providers

- pkg/gitprovider/bitbucket.go
Fixes Bitbucket branch retrieval to use the recently implemented pagination support. Previously, the TUI would list only 10 branches in total instead of listing up to 100 plus a "Load more" option.
> fix: bitbucket branch list pagination

- pkg/gitprovider/bitbucket.go
Fixes the Bitbucket context retrieval being slow due to the speed of the API call for retrieving every commit and figuring out the last commit's SHA instead of getting just the one that is needed.
Closes #1258
> fix: bitbucket context retrieval speed

- pkg/docker/create_devcontainer.go
Adds a check to validate that the devcontainer config file exists before attempting to read and create the devcontainer. 
Closes #917
All providers will need to be updated
> fix: check if devcontainer file exists before creating

- pkg/views/workspace/create/view.go
This PR fixes the API failure on repeated validation of Repo URL.
Closes #1257
> fix: api failure on repeated validation of repo url

- internal/testing/server/projectconfig/store.go
- pkg/cmd/server/serve.go
- pkg/db/project_config_store.go
- pkg/server/gitproviders/remove.go
- pkg/server/gitproviders/service.go
- pkg/workspace/project/config/store.go
This PR fixes an issue where project configs would still retain the GitProviderId even after it was removed.
> fix: detach git provider config from project config on removal

- pkg/cmd/gitprovider/delete.go
- pkg/cmd/gitprovider/update.go
- pkg/cmd/projectconfig/update.go
- pkg/cmd/workspace/create.go
- pkg/cmd/workspace/util/creation_data.go
- pkg/views/workspace/selection/gitproviderconfig.go
This PR adds the option to update the attached git provider config on a project config. The user is only able to select from git providers that can handle the repository URL. Additionally, the user can choose `None` which will set the git provider config id to `nil`
> feat: update project config git provider

- pkg/git/service.go
- pkg/git/service_test.go
Adds support for the HTTP protocol for git URLs. Most relevant for local git providers.
> fix: support http protocol for git urls

- pkg/cmd/cmd.go
Fixes showing "help" on failed commands for commands without extra arguments - e.g. `daytona autocomplete` and `daytona forward`
> fix: show help on failed noargs commands

- pkg/api/controllers/target/list.go
This PR introduces hiding of sensitive information (e.g. access key IDs, Auth Tokens, etc.) when listing targets.
Before
After
> fix: hide sensitive info when listing targets

- pkg/agent/tailscale/server.go
- pkg/common/error.go
- pkg/frpc/frpc.go
- pkg/tailscale/connection.go
Added a troubleshooting tip for connection issues. Possible connection issues that were covered:
- Tailscale connection timeout (in the CLI and Agent)
- FRP service connection errors
Closes #657
Closes #45
Closes #664
The issues that this PR closes are not directly resolved by this PR. Since Daytona can not influence the network configuration of a user, it can only provide a troubleshooting tip to help the user work around the problem.
The relevant docs entry PR: https://github.com/daytonaio/docs/pull/184
> fix: connection troubleshooting help

- cmd/daytona/config/config.go
Instead of doing any checks during `daytona create`, simply checks if the `code` command is available on initial config setup and if it isn't, it reverts to the browser IDE. Browser being unavailable isn't considered
Closes #1216
> feat: improve initial default ide

- pkg/cmd/workspace/create.go
This PR ensures that each project is assigned a unique name when creating workspaces, allowing for successful API key generation.
closes #1301 
https://github.com/user-attachments/assets/c042f529-9b48-4cd9-a273-da7b68ff4c7e
> fix: add unique project names while creating multi-project ws

- hack/generate-cli-docs.sh
Removing CLI commands could previously result in leftovers
> chore: cleanup existing cli docs before generation

- internal/testing/server/workspaces/store.go
- pkg/api/controllers/workspace/create.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/README.md
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_workspace.go
- pkg/apiclient/docs/WorkspaceAPI.md
- pkg/apiclient/docs/WorkspaceDTO.md
- pkg/apiclient/docs/WorkspaceViewDTO.md
- pkg/apiclient/model_workspace_dto.go
- pkg/apiclient/model_workspace_view_dto.go
- pkg/db/dto/workspace.go
- pkg/db/workspace_store.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/dto/workspace.go
- pkg/server/workspaces/get.go
- pkg/server/workspaces/list.go
- pkg/server/workspaces/remove.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
- pkg/server/workspaces/start.go
- pkg/server/workspaces/stop.go
- pkg/views/workspace/list/view.go
- pkg/workspace/store.go
This PR replaces target id with target name field in list workspaces command.
New DTO type `WorkspaceViewDTO` is introduced.
> refactor: replace target id with name in list cmd

- pkg/cmd/workspace/create.go
- pkg/logs/logger.go
- pkg/logs/target.go
- pkg/server/targets/create.go
- pkg/server/targets/remove.go
- pkg/server/targets/start.go
- pkg/views/logs/display.go
- pkg/views/workspace/info/view.go
This PR syncs output when running `daytona create` with what it was like before.
It also fixes target ID showing as a prefix in logs instead of target name.
Note that even though output on `daytona create` looks like this:
Output when running `daytona info` looks like this which needs refactor as well.
All of the providers need to be updated with expanding arguments of `CreateTargetLogger function` with `targetName string` argument as in [#42](https://github.com/daytonaio/daytona-provider-docker/pull/42).
> refactor: target logger and create command output update

- pkg/api/controllers/provider/install.go
- pkg/provider/manager/error.go
- pkg/provider/manager/installer.go
- pkg/provider/manager/manager.go
- pkg/server/providers.go
Persists default provider/target deletion on Daytona Server restarting instead of redownloading every time
Closes #1273
> fix: persist default provider deletion

- pkg/cmd/workspace/create.go
Fixes 2 issues:
- Null-pointer exception if a user ctrl+c's out of the Git Provider selection TUI
- Don't trigger TUI if the flag was provided
> fix: git provider config flag on create

- cmd/daytona/config/const.go
- docs/daytona_code.md
- docs/daytona_create.md
- hack/docs/daytona_code.yaml
- hack/docs/daytona_create.yaml
- pkg/cmd/ide.go
- pkg/cmd/workspace/code.go
- pkg/ide/zed.go
add zed ide support
closes https://github.com/daytonaio/daytona/issues/1002
/claim https://github.com/daytonaio/daytona/issues/1002
https://github.com/user-attachments/assets/c2225136-98a2-426f-9c47-c642e5de1178
> feat: add zed ide support

- pkg/cmd/server/daemon/daemon.go
Moves the GOOS check further up so that 'daytona server' does not try getting the e.g. USER env var before returning an error on Windows
Closes #1310 
Daemon mode is not yet supported for Windows
> fix: windows check for daytona server

- pkg/cmd/workspace/create/cmd.go
Fixes prefix logs on `daytona create`
Before
After
> fix: logs prefix

- pkg/views/workspace/info/view.go
This PR syncs workspace info output as it was before the target refactor.
Info now looks like this:
> refactor: adjust workspace info output

- pkg/server/workspaces/list.go
Workspace target rename leftover
> fix: workspace target rename leftover

- pkg/cmd/build/run.go
- pkg/cmd/prebuild/add.go
- pkg/cmd/workspace/create/add_from_config.go
- pkg/cmd/workspace/create/branch_wizard.go
- pkg/cmd/workspace/create/cmd.go
- pkg/cmd/workspace/create/creation_data.go
- pkg/cmd/workspace/create/process_cmd_arguments.go
- pkg/cmd/workspace/create/process_prompting.go
- pkg/cmd/workspace/create/repository_wizard.go
- pkg/cmd/workspaceconfig/add.go
- pkg/views/workspace/create/summary.go
Fixes passing the context to certain functions and improves naming consistency for "Params" types
> refactor: fix passing ctx and config params naming

- cmd/daytona/config/const.go
- pkg/gitprovider/bitbucketserver.go
- pkg/gitprovider/bitbucketserver_test.go
This PR adds support for webhooks for Bitbucket Server prebuilds. It implements five methods: webhook get, register, unregister, comparing commit ranges and parsing event data.
closes #995 
/claim #995
https://github.com/user-attachments/assets/795542cb-d52d-4d48-aea9-158b5bc97342
While fetching [RepoBranches](https://github.com/daytonaio/daytona/blob/5973ccc3d53363e781252f664f972d39718e801f/pkg/gitprovider/bitbucketserver.go#L166), the namespaceId and repositoryId was same that's why it was throwing this error:
```
ERRO[4348] API ERROR                                     URI=/gitprovider/bitbucket-server/so
m/som/branches error="Error #01: Request failed with Status: 404 , Body: {errors:[{message:Repository som/som does not exist.,exceptionName:com.atlassian.bitbucket.repository.NoSuchRep …
```
> feat: Add Bitbucket-Server Prebuilds Webhook

- pkg/views/common.go
This PR removes env vars input character limit.
closes #1316
> fix: remove env vars input char limit

- hack/project_image/Dockerfile
- internal/testing/server/workspaces/mocks/provisioner.go
- pkg/build/builder.go
- pkg/build/devcontainer.go
- pkg/build/factory.go
- pkg/cmd/server/serve.go
- pkg/docker/client.go
- pkg/docker/create.go
- pkg/docker/create_devcontainer.go
- pkg/docker/create_image.go
- pkg/docker/create_test.go
- pkg/docker/start_devcontainer.go
- pkg/provider/types.go
- pkg/provisioner/create.go
- pkg/provisioner/provisioner.go
- pkg/provisioner/start.go
- pkg/server/registry/service.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service.go
- pkg/server/workspaces/service_test.go
- pkg/server/workspaces/start.go
- pkg/views/server/configure.go
Added the option to configure the custom builder image. The option in the server existed before but wasn't used in the entire build process. The image, with the appropriate registry is used in the entire creation process now.
Additionally, added container registry credentials to the local container registry service. If the local registry fails to start, the serve command does not exit. Instead, it prints out the error and lets the user know they should restart the server to restart the registry.
Closes https://github.com/daytonaio/daytona/issues/1348
All providers will need to be updated.
> feat: custom builder image

- pkg/docker/create_devcontainer.go
Fixes handling of multiple compose files when `dockerComposeFile` is defined as an array.
Closes https://github.com/daytonaio/daytona/issues/1344.
All providers will need to be updated.
Can be tested with https://github.com/Tpuljak/multi-compose-devcontainer.
> fix: handle multiple compose files in devcontainers

- pkg/docker/create_devcontainer.go
Fixes an issue for creating devcontainer on MacOS. The socat container is now ran as the root user.
Providers will need to be updated.
> fix: run socat container as root

- pkg/cmd/cmd.go
- pkg/cmd/server/daemon/daemon.go
- pkg/cmd/server/serve.go
Disabled telemetry logging for the command used by the daemon to start the Daytona server.
The command is not relevant for telemetry and is called too many times.
> telemetry: disable telemetry on server daemon command

- pkg/api/controllers/workspace/create.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_workspace.go
- pkg/apiclient/docs/WorkspaceAPI.md
- pkg/cmd/workspace/create/cmd.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/service_test.go
- pkg/services/workspace.go
- pkg/views/workspace/info/multi.go
- pkg/views/workspace/list/view.go
This PR fixes info output of the `daytona create --multi-workspace` command whereas now output is adapted to be similar as it was when daytona was using multi projects.
Not shown in the screenshot above, extra new line under `Editor` was removed.
> fix: implement correct multi-create output

- pkg/docker/create.go
- pkg/docker/create_devcontainer.go
Fixes an issue for creating compose devcontainers on remote environments (e.g. remote Docker target or any of the other providers).
Closes https://github.com/daytonaio/daytona-provider-hetzner/issues/5
Providers will need to be updated
> fix: remote devcontainer compose creation

- pkg/build/detect/detect.go
Fixes an issue where providers would panic because of a nil pointer exception in a scenario where the Custom Image builder was used in a devcontainer project.
All providers will need to be updated.
> fix: custom image builder detection

- pkg/api/controllers/workspace/create.go
If the workspace with the same name already exists, the API returns 500 error instead of 4xx.
Solved this issue with appropriate error handling.
Fixes #1391 
/closes #1391
> Fix: Status code issue

- internal/testing/job/store.go
- pkg/cmd/server/bootstrap/get_job_runner.go
- pkg/cmd/server/bootstrap/get_server_instance.go
- pkg/db/job_store.go
- pkg/server/jobs/service.go
- pkg/server/jobs/service_test.go
- pkg/services/job.go
- pkg/stores/job_store.go
The job service now disallows concurrent jobs. E.g. a workspace can't be deleted while being created.
Also, split the `Save` method into `Create` and `Update` in the user service to make this possible and to improve readability.
> fix: disallow concurrent jobs

- pkg/api/controllers/target/target.go
- pkg/api/controllers/workspace/workspace.go
> fix: hide env vars for nested target or workspace

- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/restart.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
- pkg/views/workspace/selection/view.go
- pkg/views/workspace/selection/workspace.go
This PR introduces selection of items in improper state for commands such as `daytona start`, `daytona stop`, `daytona restart` and `daytona delete`.
https://github.com/user-attachments/assets/9b5910e0-a28d-4f78-b03e-72706616c416
> feat: disable items for selection when in invalid state

- docs/daytona_git-providers_add.md
- hack/docs/daytona_git-providers_add.yaml
- pkg/cmd/gitprovider/add.go
- pkg/cmd/gitprovider/update.go
- pkg/views/gitprovider/select.go
currently, `daytona gp add` works only via TUI. This PR adds support for adding Git providers non-interactively.
closes #1352
> feat: support non-interactive mode in git provider add

- cmd/daytona/config/ssh_file.go
- docs/daytona_ssh.md
- hack/docs/daytona_ssh.yaml
- pkg/cmd/workspace/delete.go
- pkg/cmd/workspace/ssh.go
This PR adds support for editing a workspace's project SSH config through the `daytona` CLI. Specifically it now supports `-e` to edit SSH config files.
closes #1207
https://github.com/user-attachments/assets/49450ad9-b7ae-4abb-af07-eeabc43e7959
This PR also fixes #1392
> feat: add support for editing ssh config files

- pkg/cmd/workspace/create.go
- pkg/docker/client_test.go
- pkg/docker/create.go
- pkg/docker/create_image.go
- pkg/docker/create_test.go
- pkg/docker/start_image.go
Cloning the repo first and mounting it into the project container is now skipped when a custom image is used.
This is unnecessary since daytona won't build a devcontainer.
This significantly improves creation time when a custom image is used.
> feat: skip external clone with custom image

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/TargetConfigAPI.md
- pkg/apiclient/docs/TargetProviderInfo.md
- pkg/apiclient/model_target_provider_info.go
- pkg/cmd/common/await_state.go
- pkg/cmd/target/create.go
- pkg/cmd/target/restart.go
- pkg/cmd/target/ssh.go
- pkg/cmd/target/start.go
- pkg/cmd/target/stop.go
- pkg/cmd/workspace/stop.go
- pkg/jobs/target/create.go
- pkg/models/target.go
- pkg/provider/manager/manager.go
- pkg/provider/types.go
- pkg/server/targets/start.go
- pkg/server/targets/stop.go
- pkg/services/target.go
Frontend and backend validation for target mode agent in providers - currently only relevant for [Docker](https://github.com/daytonaio/daytona-provider-docker/pull/49), other providers need no changes
> fix: properly handle no target mode agent in providers

- docs/daytona_project-config.md
- docs/daytona_project-config_export.md
- docs/daytona_project-config_import.md
- hack/docs/daytona_project-config.yaml
- hack/docs/daytona_project-config_export.yaml
- hack/docs/daytona_project-config_import.yaml
- pkg/cmd/projectconfig/add.go
- pkg/cmd/projectconfig/export.go
- pkg/cmd/projectconfig/import.go
- pkg/cmd/projectconfig/projectconfig.go
- pkg/cmd/projectconfig/update.go
- pkg/cmd/workspace/create.go
- pkg/views/workspace/create/configuration.go
- pkg/views/workspace/create/summary.go
This PR allows users to import and export project configurations by adding two new commands `daytona pc export` & `daytona pc import`. When a project-config is exported it's by default copied to the clipboard also while exporting prebuilds(if any) are set to empty. 
closes #1202
https://github.com/user-attachments/assets/61abd178-32dc-4c6c-98f3-6e7a538212bc
> feat: add project config export/import

- internal/testing/agent/mocks/sshserver.go
- internal/testing/agent/mocks/tailscaleserver.go
- pkg/agent/agent.go
- pkg/agent/agent_test.go
- pkg/agent/tailscale/server.go
- pkg/docker/exec_test.go
- pkg/docker/start.go
- pkg/docker/start_test.go
Fixes the check for starting the Daytona agent. Removed the hardcoded 5 second timeout.
> fix: agent started check

- cmd/daytona/config/ssh_file.go
Fixes the above error that occurred when removing a workspace that doesn't have an ssh config entry
> fix: don't throw when ssh entry not found on removal

- pkg/cmd/build/run.go
- pkg/cmd/server/bootstrap/get_job_runner.go
This PR fixes env vars not being propagated from workspace templates to builds on running build as well as setting builder registry server to default frpc domain registry server to avoid nil pointer dereference bug.
> fix: set builder registry server to default frpc domain

- pkg/cmd/workspace/create/creation_data.go
This PR adds missing git provider id in the title of selection cloning options (and others) when running builds.
Before:
After:
> fix: add git provider id to cloning options output

- pkg/server/targets/remove.go
- pkg/server/workspaces/create.go
- pkg/server/workspaces/remove.go
- pkg/server/workspaces/service_test.go
- pkg/services/target.go
- pkg/services/workspace.go
This PR moves api-key revoke before target/workspace deletion job is started.
In this PR `ws-` prefix is removed from workspace api-keys as this was obsolete. (If there are any existing workspaces with this format of ID they won't be revoked)
> refactor: add api key revoke on target/workspace removal

- pkg/agent/agent_test.go
- pkg/ide/vscode.go
Fixes parsing the devcontainer metadata when the metadata is a single object instead of an array of configurations
Closes #1382
> fix: devcontainer metadata parsing

- hack/samples/index.json
Add Tutor-Connect to index.json
> samples: react tutor connect

- hack/install.sh
Minor fix to the install.sh script to fix leaking sudo permissions.
Closes #1445
> fix: install.sh permission leak

- pkg/api/controllers/target/restart.go
- pkg/api/controllers/workspace/restart.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/api/server.go
- pkg/apiclient/README.md
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/api_target.go
- pkg/apiclient/api_workspace.go
- pkg/apiclient/docs/TargetAPI.md
- pkg/apiclient/docs/WorkspaceAPI.md
- pkg/cmd/target/restart.go
- pkg/cmd/target/ssh.go
- pkg/cmd/target/start.go
- pkg/cmd/workspace/code.go
- pkg/cmd/workspace/restart.go
- pkg/cmd/workspace/start.go
- pkg/jobs/workspace/restart.go
- pkg/jobs/workspace/workspace.go
- pkg/server/targets/restart.go
- pkg/server/workspaces/restart.go
- pkg/services/target.go
- pkg/services/workspace.go
- pkg/telemetry/server_events.go
Fixes the services to properly use the "restart" job. Adds api endpoints for restarting which are in turn now used by the CLI - includes both workspaces and targets
> fix: restart methods

- pkg/agent/toolbox/toolbox.go
- pkg/api/server.go
Removed trailing slash from API routes such as `/workspace`, `/health`, `/profile`, etc.
> fix: remove trailing slash from API routes

- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/CreateTargetDTO.md
- pkg/apiclient/docs/TargetAPI.md
- pkg/apiclient/model_create_target_dto.go
- pkg/cmd/target/create.go
- pkg/cmd/workspace/create/cmd.go
- pkg/models/target.go
- pkg/server/targets/create.go
- pkg/server/targets/service_test.go
- pkg/services/target.go
Fixes the target creation DTO to use target config ID instead of target config name to handle users deleting target configs and readding them using the same name. Another minor fix to allow "error" state for agentless target providers
> Create target dto fix

- cmd/daytona/config/const.go
- docs/daytona_code.md
- docs/daytona_create.md
- hack/docs/daytona_code.yaml
- hack/docs/daytona_create.yaml
- pkg/cmd/ide.go
- pkg/cmd/workspace/code.go
- pkg/ide/positron.go
add support for Positron IDE
/claim #722
closes #722
> feat: add support for Positron IDE

- internal/testing/build/store.go
- pkg/api/docs/docs.go
- pkg/api/docs/swagger.json
- pkg/api/docs/swagger.yaml
- pkg/apiclient/api/openapi.yaml
- pkg/apiclient/docs/BuildDTO.md
- pkg/apiclient/model_build_dto.go
- pkg/models/build.go
- pkg/server/builds/create.go
- pkg/server/builds/service_test.go
- pkg/server/workspacetemplates/prebuild.go
- pkg/server/workspacetemplates/prebuild_test.go
- pkg/telemetry/build.go
- pkg/views/build/info/view.go
- pkg/views/build/list/view.go
This PR makes prebuild ID on build optional so that builds ran regardless of prebuild configuration don't need to carry this information.
> fix: make prebuild ID optional for build

- pkg/docker/credential_helper.go
This PR fixes issue of Daytona not being able to set docker cred-helper config when workspace is restarded.
> fix: set docker cred helper config

- pkg/cmd/workspace/logs.go
- pkg/cmd/workspace/ssh.go
- pkg/cmd/workspace/start.go
- pkg/cmd/workspace/stop.go
This PR fixes SSH command with edit flag provided as editing would proceed to ssh into workspace even though it shouldn't have.
Also, minor change of removing duplicated imports.
> fix: ssh edit command

- pkg/server/targets/delete.go
- pkg/server/targets/set-default.go
This PR fixes issue of default target not being set as non-default which resulted in other targets erroring on creation.
> fix: ghost default target

- hack/install.ps1
add install.ps1 for windows
Closes #1517 
for testing purposes 
```powershell
powershell -c "irm https://raw.githubusercontent.com/hunnywar/daytona/ps-install/hack/install.ps1 | iex"
``` 
example in production 
```powershell
powershell -c "irm https://download.daytona.io/daytona/install.ps1 | iex"
```
> feat: add install.ps1 for windows

- pkg/api/controllers/runner/jobs.go
- pkg/cmd/server/runner/delete.go
- pkg/runner/runner.go
- pkg/server/workspacetemplates/prebuild.go
Adds long polling for runner jobs to reduce overhead and improve speed
Refactors the way runners fetch jobs and runs jobs in goroutines
Drafted for testing
> refactor: long polling for runner jobs

- hack/samples/index.json
This PR add the following samples:
- Deno
- Prolog
- Racket
- Zig
This PR addresses issue #1526 
> samples: add Deno, Prolog, Racket, Zig

- pkg/cmd/common/get_runner.go
Default to single runner in TUI prompt - `GetRunnerFlow`
> feat: default to single runner in prompt

- pkg/cmd/common/delete_workspace.go
- pkg/cmd/common/polling.go
- pkg/cmd/target/delete.go
Merges the "await resource deleted" helpers into "await resource state" so that the CLI now fails the await if deleting the resource had errored
> fix: fail cli await if deleting resource errors

- pkg/api/server.go
Fixes the gin mode to be "release" in production and "debug" in development
Before:
> fix: remove gin debug logs in production

- pkg/agent/toolbox/toolbox.go
Set the gin mode to release for the toolbox api server to remove the output from workspace logs
> fix: remove gin debug logs from workspaces

- CONTRIBUTORS.md
Adding myself to the contributor's list
My contributions:
- [MacOs Provider ](https://github.com/Rutik7066/daytona-provider-macos)
- [Windows Provider](https://github.com/Rutik7066/daytona-provider-windows) 
- feat:  agent support for windows    [PR #1741](https://github.com/daytonaio/daytona/pull/1741)
- feat: add gitness provider  [PR #1999](https://github.com/daytonaio/daytona/pull/1199)
- feat: Gitness/Harness prebuild webhook  [PR #1999](https://github.com/daytonaio/daytona/pull/1199)  
- refactor: http status code and error in api   [PR #1056](https://github.com/daytonaio/daytona/pull/1056)  
- feat: multi-profile support for git providers   [PR #1032](https://github.com/daytonaio/daytona/pull/1032)  
- fix: clone project from commit url  [PR #873 …
> docs: added rutik thakre to contributors

- apps/dashboard/src/components/VerifyEmailDialog.tsx
- apps/dashboard/src/pages/Dashboard.tsx
Adds a dialog which is displayed in the dashboard as a reminder to users that need to verify their registered email address.
> feat: display dialog for email address verification

- apps/runner/pkg/docker/create_snapshot.go
This PR introduces removal of snapshot images from runner node after snapshot is successfully pushed to the internal image registry.
> fix(runner): add snapshot image removal from runner

- apps/dashboard/src/components/ApiKeyTable.tsx
- apps/dashboard/src/pages/Keys.tsx
I've modified the code to apply loading states to individual API keys during revocation instead of blocking the entire table. This improves the user experience by allowing users to continue interacting with other keys while one is being revoked.
Changes Made: 
In `Keys.tsx`:
1- Added a new `revokingKeys` state array to track which specific keys are being revoked.
In `ApiKeyTable.tsx`:
1- Modified the "Revoke" button to show loading state only for specific keys being revoked.
2- Added visual indicators (spinner + "Revoking..." text) for keys in the process of revocation.
This PR addresses issue #1785 
@quest-bot loot #1785 
https://github.com/user-attachments/assets/d72cb48e-feec-4dbd-a835-68ae00e3b2ef
The changes maintain a responsive UI during API key operations and provide clearer …
> Individual rows now have separate state

- apps/dashboard/src/App.tsx
- apps/dashboard/src/pages/LandingPage.tsx
Moves the logic for identifying a user in PostHog to the top-level component in the dashboard application. Previously, this action was triggered only if users visited the landing page.
> fix(dashboard): move posthog user identification to App.tsx

- apps/api/src/api-key/api-key.controller.ts
- libs/api-client-go/api/openapi.yaml
- libs/api-client-go/api_api_keys.go
- libs/api-client-python/daytona_api_client/api/api_keys_api.py
- libs/api-client/src/api/api-keys-api.ts
Adds an endpoint for getting ApiKeyDTO from api key value - useful for fetching the organization ID from e.g. the CLI
> feat: get current api key endpoint

- apps/runner/pkg/api/server.go
This PR introduces fix to setting swagger endpoint in development mode only
> fix(runner): fix swagger endpoint in development only

- apps/runner/pkg/docker/destroy.go
- apps/runner/pkg/docker/image_remove.go
- apps/runner/pkg/services/sandbox.go
Fixes sandbox and image removal conflicts on the runner.
- if the image is not found, return from the function
- if the container is already removing, return from the function
> fix(runner): image and sandbox removal conflicts

- apps/daemon/pkg/toolbox/process/session/execute.go
- apps/daemon/pkg/toolbox/process/session/types.go
Backwards compatibility for the async parameter
> fix(daemon): async backwards compatibility

- apps/dashboard/src/App.tsx
- apps/dashboard/src/auth/oidc-config.ts
- apps/dashboard/src/components/GettingStarted.tsx
- apps/dashboard/src/components/Organizations/CreateOrganizationDialog.tsx
- apps/dashboard/src/components/Sidebar.tsx
- apps/dashboard/src/constants/ExternalLinks.ts
- apps/dashboard/src/enums/RoutePath.ts
- apps/dashboard/src/pages/LandingPage.tsx
- apps/dashboard/src/pages/Workspaces.tsx
- apps/dashboard/tsconfig.app.json
I've completely overhauled the routing system in the Daytona dashboard application by implementing a TypeScript enum-based approach that provides better organization, type safety, and maintainability.
Key Features introduced:
1- Organized routes logically into categories `(main routes, dashboard sub-routes, user routes)`.
2- Added `external URL` constants for documentation and Slack integration.
3- Updated all routing references throughout the codebase to use the centralized enum.
4- The old routes.ts file was removed and replaced with a new `RoutePath` implementation.
This PR addresses issue #1783 
@quest-bot loot #1783
No Screenshots required, as only the enum introduced for route paths.
`Note: The structured approach also improves developer experience by making it easy to locate, …
> Introduced enum for page router paths

- apps/dashboard/src/components/ImageTable.tsx
This PR resolves a UI responsiveness issue where the icon size would shrink when the label (e.g., "Pulling Image") wrapped onto multiple lines in smaller viewports. The layout is updated to keep the icon size consistent and prevent text wrapping by:
Wrapping the icon in a fixed-size, non-shrinking container (flex-shrink-0 w-5 h-5)
Applying whitespace-nowrap to the label text to maintain layout integrity
Ensuring better responsive behavior across screen sizes
This PR addresses issue #1781
@quest-bot loot #1781
> refactord ImageTable.tsx (fixed the imageState icon size) 

- apps/api/src/email/services/email.service.ts
Sets the email sender address in the mail options object instead of the transporter object.
> fix(api): email service sender address

- apps/runner/pkg/docker/container_commit.go
- apps/runner/pkg/docker/create_snapshot.go
This PR adds retries on container commit when creating snapshot
> fix(runner): add retries to container commit on snapshot create

- apps/api/.env
- apps/dashboard/src/App.tsx
- apps/dashboard/src/pages/LandingPage.tsx
- apps/dashboard/src/providers/ApiProvider.tsx
Preserves original query string when the `signinRedirect` method from the authentication provider is called. This means that reloading a page will not strip away the URL search params. Also, the appropriate confirmation dialog will now be displayed when a user attempts to accept an invitation to join an organization:
> fix(dashboard): preserve original query string on signinRedirect

- apps/dashboard/src/components/ui/sonner.tsx
- package.json
- yarn.lock
Resolves an issue where the styling for the toaster close button was broken in some browsers for specific combinations of system theme and application light/dark mode:
> fix(dashboard): toaster close button styling

- libs/api-client/tsconfig.json
Set `importHelpers` to false in the` api-client` package to ensure all necessary TypeScript helpers are included in the compiled output, so end users don't need to install `tslib` separately.
> fix: set importHelpers to false for api-client

- apps/dashboard/src/components/ImageTable.tsx
- apps/dashboard/src/components/Pagination.tsx
- apps/dashboard/src/pages/Images.tsx
This PR fixes an issue with the Image Table pagination where even with multiple pages of images, the pagination controls were not working properly and only showing "Page 1 of 1". The update introduces server-side pagination using the API’s pagination features, adds state management for the current page, page size, and total item count, and links the pagination UI controls directly to server data fetching. Additionally, it ensures that real-time updates keep the pagination state consistent, allowing users to navigate between pages and adjust the number of images displayed per page as expected.
This PR addresses issue #1769 
@quest-bot loot #1769
> fix: Pagination of Images Table

- apps/api/src/workspace/services/image.service.ts
- apps/cli/cmd/image/list.go
- apps/cli/cmd/sandbox/list.go
- apps/cli/views/sandbox/list.go
This PR fixes the pagination of images and sandboxes in the CLI. While implementing pagination for images was straightforward, manual handling was required to paginate sandboxes.
This PR addresses issue #1770
@quest-bot loot #1770
```
daytona ➜ /workspaces/daytona (fix/pagination-cli) $ ./dtn sandbox ls
Sandbox                                       State          Region        Class        Last Event               
─────────────────────────────────────────────────────────────────────────────────────────────────────────────    
8aee3da9-5f03-4264-b3b4-18aefa1a0763          STARTED        us            small        < 1 minute ago           
ce148916-11b6-4597-a397-7e1d13e10d61          STARTED        us            small        30 minutes ago           
fb33566e-5f12-4390-ae06-49ed7f10332f …
```
> fix: pagination of sandbox and images in the CLI

- apps/daemon/pkg/toolbox/process/session/execute.go
Fixes session command persistence between executions. Because of `(%s)` before, all commands were executed in a sub-shell that didn't persist context.
Now this flow should work correctly:
```typescript
await sandbox.process.createSession('sess');
await sandbox.process.executeSessionCommand('sess', {
command: `cd /`,
});
await sandbox.process.executeSessionCommand(agentSessionId, {
command: `export VAR=123 && echo $VAR && export VAR2=456 && echo $VAR2`,
});
const response = await sandbox.process.executeSessionCommand(agentSessionId, {
command: `pwd && echo $VAR1 && echo $VAR2`,
});
```
> fix(daemon): session exec persistence

- apps/dashboard/src/components/Sidebar.tsx
Adds the org suspension reason into the alert box in the sidebar to improve clarity.
Closes #1821
> feat(dashboard): display organization suspension reason

- apps/cli/apiclient/error_handler.go
Improves error messages by adding the `message` field (string or array of strings) to the `error` property when displaying them to the user
Before:
After:
> feat: improve CLI error messages

- apps/dashboard/src/components/ui/table.tsx
This PR addresses an issue where table row heights were inconsistent between users with different permission levels. The problem occurred because users with permission to see action menus had taller rows than those without permission, causing visual inconsistency across the application's tables.
- Added `[&_tr]:h-14` class to the TableBody component in `table.tsx`, ensuring consistent row height (56px) across all tables in the application
- This single change applies to all tables including:
- WorkspaceTable
- ImageTable
- RegistryTable
- ApiKeyTable
- The centralized approach in the base component avoids duplicating height classes in multiple places and ensures consistent height application
This fix ensures that all table rows maintain the same height (14 units/56px) regardless of user …
> fix: apply consistent height to table rows

- apps/runner/pkg/daemon/util.go
This PR introduces removal of old daemon binaries when reinitializing new runner
> fix(runner): remove old daemon binary on embed init

- apps/api/src/api-key/api-key.entity.ts
- apps/api/src/api-key/api-key.service.ts
- apps/api/src/api-key/dto/api-key-list.dto.ts
- apps/api/src/auth/api-key.strategy.ts
- apps/api/src/migrations/1747658203010-migration.ts
- apps/api/src/workspace/services/image.service.ts
- apps/dashboard/src/components/ApiKeyTable.tsx
- apps/dashboard/src/components/ImageTable.tsx
- apps/dashboard/src/lib/utils.ts
- apps/dashboard/src/pages/Images.tsx
- libs/api-client-go/api/openapi.yaml
- libs/api-client-go/model_api_key_list.go
- libs/api-client-python/daytona_api_client/models/api_key_list.py
- libs/api-client/src/models/api-key-list.ts
When listing API keys and Images, their corresponding tables will now display the timestamp of the last time they were used. For API keys, it's the last time they were used to authenticate with the API, while for Images it's the last time they were used for creating a Sandbox.
Both of these tables are sorted by most recently API key or Image. For those unused, they are sorted by most recently created.
> feat(api,dashboard): last used timestamp for api keys and images

- apps/api/src/workspace/managers/snapshot.manager.ts
> chore(api): log sync snapshot state error after 10 retries

- apps/api/src/organization/services/organization.service.ts
Fix event emit when stopping suspended org sandboxes.
> fix(api): suspended org workspace stopped event emit

- apps/api/src/workspace/dto/workspace.dto.ts
- apps/api/src/workspace/managers/workspace.manager.ts
Since archiving takes the longest, this can build up a long queue of sandboxes that are not processed. Having a separate job for archiving sandboxes will unblock that.
Additionally, we include the 3-per-node rule in the query itself.
> fix(api): separate job for archiving sandboxes

- apps/api/src/workspace/managers/image.manager.ts
The builder should use the internal registry name for image when validating it on the API - otherwise the syncing hangs
> fix: image name for pending validation state

- apps/api/src/workspace/managers/image.manager.ts
- apps/api/src/workspace/managers/workspace.manager.ts
- apps/api/src/workspace/services/node.service.ts
- apps/api/src/workspace/services/workspace.service.ts
- apps/cli/cmd/common/logs.go
- apps/cli/cmd/image/build.go
- apps/cli/cmd/sandbox/create.go
Improves choosing the runner for building by limiting the concurrent builds on a runner to less than three.
Small refactor to the node retrieval function to accommodate this change
> Limit concurrent builds

- apps/runner/pkg/docker/destroy.go
Removed the err check when destroying a sandbox on a runner.
The err check prevented exited containers from being deleted.
> fix(runner): destroy exited containers

- apps/dashboard/src/App.tsx
- apps/dashboard/src/components/Sidebar.tsx
Modifies the conditional logic for rendering the "Limits" page. Only organization owners have access to it.
> fix(dashboard): render Limits page to organization owners only

- apps/dashboard/src/components/ApiKeyTable.tsx
- apps/dashboard/src/components/ImageTable.tsx
- apps/dashboard/src/components/OrganizationMembers/OrganizationInvitationTable.tsx
- apps/dashboard/src/components/OrganizationMembers/OrganizationMemberTable.tsx
- apps/dashboard/src/components/OrganizationRoles/OrganizationRoleTable.tsx
- apps/dashboard/src/components/Pagination.tsx
- apps/dashboard/src/components/RegistryTable.tsx
- apps/dashboard/src/components/UserOrganizationInvitations/UserOrganizationInvitationTable.tsx
- apps/dashboard/src/components/VolumeTable.tsx
- apps/dashboard/src/components/WorkspaceTable.tsx
This PR enhances the user experience of table pagination by introducing context-specific labels. Instead of using generic terms like "Rows per page" or "Items," the labels now reflect the specific content of each table, making the interface more intuitive and informative.
Changes Made: 
1. Added optional `entityName` prop to the interface in `Pagination.tsx`:
- Implemented dynamic label generation: `{entityName} per page` or fallback to `Rows per page`.
2. Updated All Table Components with context-specific entity names:
- `WorkspaceTable` → "Sandboxes per page"
- `VolumeTable` → "Volumes per page"
- `ImageTable` → "Images per page"
- `ApiKeyTable` → "API Keys per page"
- `RegistryTable` → "Registries per page"
- `OrganizationRoleTable` → "Organization Roles per page"
- …
> feat(ux): apply context-specific labels to table pagination

- apps/dashboard/src/components/ApiKeyTable.tsx
- apps/dashboard/src/components/ImageTable.tsx
- apps/dashboard/src/components/OrganizationMembers/OrganizationInvitationTable.tsx
- apps/dashboard/src/components/OrganizationMembers/OrganizationMemberTable.tsx
- apps/dashboard/src/components/OrganizationRoles/OrganizationRoleTable.tsx
- apps/dashboard/src/components/RegistryTable.tsx
- apps/dashboard/src/components/TableEmptyState.tsx
- apps/dashboard/src/components/UserOrganizationInvitations/UserOrganizationInvitationTable.tsx
- apps/dashboard/src/components/VolumeTable.tsx
- apps/dashboard/src/components/WorkspaceTable.tsx
- apps/dashboard/src/pages/Workspaces.tsx
This PR improves the user experience of the Container Sandbox section by enhancing the empty state with purpose-driven messaging and actionable guidance.
**Changes Made:** 
1. Updated the empty state in `WorkspaceTable.tsx` to replace the generic "No results." message with a more informative and helpful message.
2. The new empty state includes:
- A clear message: "You don't have any Sandboxes yet."
- Helpful guidance: "Create your first sandbox to get started with isolated development environments."
3. Cleaned up unused imports to avoid linting issues in `Workspaces.tsx`.
This PR addresses issue #1872 
This provides better context about what sandboxes are and guides users toward action.
> feat(ui): add guidance and purpose to container sandbox empty state

- apps/api/src/usage/entities/workspace-usage-period.entity.ts
- apps/api/src/usage/services/usage.service.ts
- apps/api/src/usage/usage.module.ts
Closing and reopening usage periods after 24h makes the billing more accurate while not affecting the usage metrics in the API itself.
> feat(api): close and reopen usage periods after 24h

- apps/api/src/workspace/managers/workspace.manager.ts
Due to the redis unlocks being scattered around all functions, multiple API instances could process the same sandbox due to race conditions.
Refactored how state is synced, locked and unlocked so that only one instance can handle a certain sandbox.
> fix(api): sandbox state sync locking

- apps/cli/cmd/image/push.go
- apps/cli/views/util/spinner.go
Fixes a spinner bug when using calling `image push` uninteractively
Also adds an `entrypoint` flag
Closes #1997 
Closes #2004
> fix: image push uninteractive and entrypoint flag

- libs/sdk-python/pyproject.toml
fixes:
```py
Traceback (most recent call last):
File "c:\Users\smart\Desktop\GD\Kevin\tempCodeRunnerFile.python", line 1, in <module>
from daytona import Daytona, DaytonaConfig
File "C:\Python312\Lib\site-packages\daytona\__init__.py", line 4, in <module>
from daytona_api_client import SandboxState, SessionExecuteResponse
ImportError: cannot import name 'SandboxState' from 'daytona_api_client' (C:\Python312\Lib\site-packages\daytona_api_client\__init__.py)
```
> bump `daytona_api_client` and `daytona_api_client_async`

- apps/api/src/sandbox/managers/sandbox.manager.ts
Use a more specific error message for sandbox state instead of just a 500 error or a 40x error which would lead users to believe they made a mistake
Before:
`Request failed with status code 500` 
After:
`timeout waiting for container 4b5ac9ac-9c4b-4933-aee5-55a3f68582b8 to start`
> fix: improve error message in sandbox

- apps/api/src/sandbox/services/runner.service.ts
Exclude destroyed sandbox from `findBySandboxId` because destroyed sandboxes should be treated as "not found" by the domain
> fix(api): exclude destroyed sandbox from findBySandboxId

- apps/api/src/sandbox/controllers/runner.controller.ts
- apps/api/src/sandbox/dto/runner-snapshot.dto.ts
- apps/api/src/sandbox/services/runner.service.ts
This PR adds a new endpoint to retrieve all runner records where a snapshot-runner record exists for a given snapshot internal name. This feature enables querying which runners have access to a specific snapshot, which is useful for monitoring snapshot distribution across the runner infrastructure.
* New DTO: Created RunnerSnapshotDto with fields for runnerSnapshotId, runnerId, and runnerDomain
* Service Method: Added getRunnersBySnapshotInternalName() method to RunnerService that:
* Finds the snapshot by internal name
* Queries snapshot runners using the internal name as the snapshotRef
* Retrieves corresponding runner details
* Returns formatted DTO objects
* Controller Endpoint: Added `GET /runners/by-snapshot` endpoint with:
* Query parameter for internalName
* Proper Swagger …
> feat: get runners by snapshot

- apps/daemon/pkg/toolbox/toolbox.go
Because the params were in the incorrect order when calling `NewSessionController`, sessions were spawned in `$HOME/.daytona` rather than in `$HOME`. Additionally, logs were being stored at `$HOME/sessions` instead of `$HOME/.daytona/sessions` amongst other things.
> fix(daemon): swap configDir and ProjectDir params

- libs/sdk-python/src/daytona/_async/snapshot.py
- libs/sdk-python/src/daytona/_sync/snapshot.py
- libs/sdk-python/src/daytona/_utils/stream.py
- libs/sdk-typescript/src/Image.ts
- libs/sdk-typescript/src/ObjectStorage.ts
- libs/sdk-typescript/src/Snapshot.ts
- pyproject.toml
Fixed the TypeScript SDK’s COPY path resolution for declarative builder and improved stream log termination to ensure the stream closes asap.
> fix: dockerfile COPY command path resolutions; stream error handling

- apps/runner/cmd/runner/config/config.go
- apps/runner/pkg/docker/container_configs.go
- apps/runner/pkg/docker/create.go
In a self-hosted deployment, when the `runner`, `proxy`, and `api` are placed in a custom network, if the sandbox container uses the default network, all API calls from the `runner` to the `sandbox daemon 2280` will time out.
1. First, set the environment variable `CONTAINER_NETWORK=sandbox` when starting the runner.
2. After creating the sandbox through the sdk, you can see that the container network is sandbox.
> feat(runner): allow setting the network of the sandbox container

- apps/proxy/pkg/proxy/proxy.go
- apps/runner/pkg/api/middlewares/auth.go
- libs/common-go/pkg/proxy/proxy.go
- fix allowed headers handling - now all headers part of the request are allowed
- added X-Daytona-Disable-CORS header - users can now choose to disabled our CORS and rely on their implementation
- fixed proxy -> runner auth - prioritize `X-Daytona-Authorization` instead of `Authorization`
> fix(proxy): cors issues

- libs/sdk-python/src/daytona/_async/daytona.py
- libs/sdk-python/src/daytona/_sync/daytona.py
- libs/sdk-typescript/src/Daytona.ts
Ensure environment variables don't override any values passed in via the `config` argument, even if the provided `config` is partial.
Solve a case where environment variables overwritten values from config argument when it was provided partial config object.
closes #2078
> fix: daytona config argument overrides env vars (fixed edge cases)

- libs/sdk-python/scripts/sync_generator.py
- libs/sdk-python/src/daytona/_async/filesystem.py
- libs/sdk-python/src/daytona/_sync/filesystem.py
I haven't seen any issues yet, but the issue exists and is 100% reproducible. It happens when you try to use [this api](https://www.daytona.io/docs/python-sdk/sync/file-system/#filesystemdownload_file-1)
Basically it is wrongly using `httpx`, headers is used as a keyword parameter in `httpx.client`, but it is passed in as a positional parameter.
reference from httpx: 
https://github.com/encode/httpx/blob/26d48e0634e6ee9cdc0533996db289ce4b430177/httpx/_client.py#L827-L844
And below `_sync.filesystem.py` is using aiter_bytes(an async func) in a sync function, it should be iter_bytes instead.
> fix(fs): wrong httpx stream param invoked

- apps/api/src/docker-registry/services/docker-registry.service.ts
This PR fixes an error that occurs when propagating snapshots to runner nodes in environments where both the transient and internal registries share the same domain.
Previously, findOneBySnapshotImageName could incorrectly match the transient registry, causing snapshot propagation to fail.
With this fix, the method now ignores the transient registry when searching by image name, ensuring the correct registry is used even if both registries are on the same domain.
> Fix findOneBySnapshotImageName to ignore transient registry

- apps/api/src/sandbox/managers/sandbox.manager.ts
Added missing step that sets sandbox as pending for a state change when setting a new desired state in auto-stop and auto-archive checks.
> fix(api): set pending on auto-stop and auto-archive

- apps/api/src/sandbox/managers/sandbox.manager.ts
Increases the timeout for archiving from 30 to 120 minutes. This isn't the actual duration timeout and instead includes the time while the sandbox is "waiting in line" for other sandboxes to finish archiving in very high load situations.
> fix: increase archiving timeout

- apps/docs/astro.config.mjs
- apps/docs/src/assets/themes/daytona-code-light.json
- apps/docs/src/styles/_color.scss
This fixes two issues which made the text in the documentation site hard to read in light mode.
| Before | After |
|--------|-------|
| <img width="750" height="434" alt="Screenshot 2025-07-10 at 6 05 17 PM" src="https://github.com/user-attachments/assets/63e2870b-68bd-443b-8c9a-89eab5f67d20" /> | <img width="739" height="443" alt="Screenshot 2025-07-10 at 6 07 15 PM" src="https://github.com/user-attachments/assets/4203cf05-dad2-487e-879e-d8239211827a" /> |
| Before | After |
|--------|-------|
| <img width="291" height="224" alt="Screenshot 2025-07-10 at 6 05 37 PM" src="https://github.com/user-attachments/assets/5e4a22c8-2787-4517-b2ed-72572d9ae3e9" /> | <img width="293" height="232" alt="Screenshot 2025-07-10 at 6 05 47 PM" src="https://github.com/user-attachments/assets/d7ba1ea4-da11-4 …
> Fix docs readability in light mode

- apps/api/src/sandbox/controllers/toolbox.controller.ts
- apps/daemon/pkg/toolbox/proxy/proxy.go
- apps/proxy/pkg/proxy/get_target.go
- apps/runner/pkg/api/controllers/command_logs.go
- apps/runner/pkg/api/controllers/proxy.go
- apps/runner/pkg/api/middlewares/auth.go
- libs/common-go/pkg/proxy/proxy.go
Fix proxy websocket handling and simplify implementation.
Additionally, rolled back proxy auth protection for port 6080
> fix(proxy): websocket connections and simplify implementation

- apps/docs/src/content/config.ts
This fixes confusing behavior of the docs sidebar:
Previously the subpages looked like top-level pages, due to having no Home link. Additionally, the API Reference and CLI Reference pages showed subpages when they have none.
Screenshots of the fixed sidebar:
<p float="left">
</p>
> Improve docs navigation

- apps/api/src/sandbox/managers/sandbox.manager.ts
Fixed a critical bug in `SandboxManager.handleRunnerSandboxStoppedOrArchivedStateOnDesiredStateStart` that caused load balancing logic to fail when migrating sandboxes from unschedulable runners.
The issue occurred due to improper state management in sequential condition blocks:
1. **First condition block**: When a runner becomes unschedulable and backup is completed, the code sets `sandbox.runnerId = null` but incorrectly assigns `prevRunnerId = null` instead of the original runner ID
2. **Second condition block**: Load balancing logic uses the modified `sandbox.runnerId` (now null) for database queries, causing incorrect load calculations
- ❌ Load balancing completely fails for unschedulable runners
- ❌ Sandbox migration logic is broken due to lost `prevRunnerId` information  
- ❌ …
> fix(api): resolve runner assignment and load balancing bug in SandboxManager

- apps/cli/mcp/tools/create_folder.go
- apps/cli/mcp/tools/create_sandbox.go
- apps/cli/mcp/tools/delete_file.go
- apps/cli/mcp/tools/download_file.go
- apps/cli/mcp/tools/execute_command.go
- apps/cli/mcp/tools/file_info.go
- apps/cli/mcp/tools/git_clone.go
- apps/cli/mcp/tools/move_file.go
- apps/cli/mcp/tools/preview_link.go
- apps/cli/mcp/tools/upload_file.go
This PR aligns JSON namings as well as introduces some domain rules for sandbox creation
> fix(mcp): align json namings

- apps/docs/public/llms-full.txt
- apps/docs/public/llms.txt
- apps/docs/src/content/docs/configuration.mdx
- apps/docs/src/content/docs/declarative-builder.mdx
- apps/docs/src/content/docs/file-system-operations.mdx
- apps/docs/src/content/docs/getting-started.mdx
- apps/docs/src/content/docs/git-operations.mdx
- apps/docs/src/content/docs/index.mdx
- apps/docs/src/content/docs/language-server-protocol.mdx
- apps/docs/src/content/docs/log-streaming.mdx
- apps/docs/src/content/docs/process-code-execution.mdx
- apps/docs/src/content/docs/regions.mdx
- apps/docs/src/content/docs/sandbox-management.mdx
- apps/docs/src/content/docs/snapshots.mdx
- apps/docs/src/content/docs/volumes.mdx
This fixes broken example code in the docs:
1. When the docs were moved to the monorepo, they were formatted, breaking code inside of Markdown code blocks. I reviewed the changes between edb94d37e792afb0935787d7bebb32a75160a642 and [daytonaio/docs](https://github.com/daytonaio/docs) and reverted only sections inside of Markdown code blocks.
2. The **Git operations** page contained incorrect/out-of-date examples, which are now fixed.
3. The **Language Server Protocol** page contained an incorrect TypeScript example, which is now fixed.
4. The Python **log streaming** example had a small bug, which is fixed.
> Fix broken example code in docs

- apps/dashboard/src/components/LoadingFallback.tsx
Increased size of top-level spinner.
> fix(dashboard): increase size of top-level spinner

- apps/daemon/pkg/terminal/decoder.go
- apps/daemon/pkg/terminal/server.go
Sandbox web terminal would close the websocket connection when multi-byte UTF-8 characters were split across buffer reads, causing the browser websocket to close with the following error:
`Could not decode a text frame as UTF-8`
Added a UTF8Decoder that buffers incomplete UTF-8 byte sequences across reads, ensuring only valid UTF-8 strings are sent over the websocket.
> fix(daemon): terminal connection issues

- apps/api/src/sandbox/controllers/sandbox.controller.ts
- apps/api/src/sandbox/services/runner.service.ts
Fetch all runners in a single query via runnerService.findByIds() instead of querying runner per sandbox.
> fix(api): resolve N+1 query in listSandboxes

- apps/api/src/sandbox/controllers/runner.controller.ts
- apps/api/src/sandbox/services/runner.service.ts
- libs/api-client-go/api/openapi.yaml
- libs/api-client-go/api_runners.go
- libs/api-client-python-async/daytona_api_client_async/api/runners_api.py
- libs/api-client-python/daytona_api_client/api/runners_api.py
- libs/api-client/src/api/runners-api.ts
Changes the logic to focus only on the `snapshot_runners` table as the source of truth - it is maintained to communicate which snapshots the API expects each runner to have. Fixes declarative ad-hoc builds missing in the response
> fix: return runners by snapshot ref

- apps/api/src/common/utils/email.util.ts
- apps/api/src/organization/controllers/organization.controller.ts
- apps/api/src/organization/services/organization-invitation.service.ts
- apps/api/src/user/user.service.ts
Introduced case-insensitive email handling for organization invitations. 
For example, user with email address `john.doe@acme.org` would be able to accept organization invitations sent to following emails:
- `John.Doe@acme.org`
- `JOHN.doe@acme.org`
- ...
This will resolve issues where users would not be able to accept invitations even though they receive it in their email inbox.
> refactor(api): ignore case for organization invitation email address

- apps/api/src/migrations/1753100751731-migration.ts
Renamed the 'Images Admin' organization role to 'Snapshots Admin' in accordance with #1938
> fix(api): correct name and description for snapshots admin organization role

- apps/api/src/migrations/1753430929609-migration.ts
- apps/api/src/user/dto/user.dto.ts
- apps/api/src/user/user.entity.ts
- libs/api-client-go/api/openapi.yaml
- libs/api-client-go/model_user.go
- libs/api-client-python-async/daytona_api_client_async/models/user.py
- libs/api-client-python/daytona_api_client/models/user.py
- libs/api-client/src/models/user.ts
Added `createdAt` property to the User entity. For existing users, this value will be set to match their personal organization's creation timestamp.
> feat(api): user creation timestamp

- apps/api/src/sandbox/controllers/sandbox.controller.ts
- libs/sdk-python/src/daytona/_async/daytona.py
- libs/sdk-python/src/daytona/_async/sandbox.py
- libs/sdk-python/src/daytona/_sync/daytona.py
- libs/sdk-python/src/daytona/_sync/sandbox.py
- libs/sdk-typescript/src/Daytona.ts
- libs/sdk-typescript/src/Sandbox.ts
Currently, on the server side, the sandbox start operation waits up to 30 seconds for the sandbox to reach the `STARTED` state before throwing a `BadRequestException` on timeout. This design eliminates the need for client-side polling and improves perceived responsiveness in typical scenarios.
However, when starting a sandbox from the `ARCHIVED` state, the operation can take significantly longer, depending on factors like archive size. In such cases, the 30-second limit is often exceeded, resulting in a timeout exception that the client does not handle properly.
This PR addresses that by returning the API response immediately (without throwing an exception) if the sandbox is being started from the `ARCHIVED` state. The SDK then takes over, polling the sandbox state until it transitions to …
> fix: return immediately from api if the sandbox is starting from an archived state

- apps/api/src/config/configuration.ts
- apps/api/src/sandbox/managers/backup.manager.ts
- apps/api/src/sandbox/managers/sandbox-actions/sandbox-archive.action.ts
- apps/api/src/sandbox/managers/sandbox.manager.ts
- apps/api/src/sandbox/managers/snapshot.manager.ts
#Several Archival Improvements
- increase per-runner concurrency limit and allow for env var override
- fix issue where a backup wasn't being created when a sandbox was archived
- fix issue for sorting archived sandboxes when fetching from db
> fix(api): several archival improvements

- apps/api/src/organization/guards/organization-access.guard.ts
Resolves an issue where a user with system admin permissions was unable to perform org-level actions guarded by `OrganizationAccessGuard`.
> fix(api): add missing system admin condition in org access guard

- apps/dashboard/src/components/Sidebar.tsx
- apps/dashboard/src/providers/BillingProvider.tsx
Currently, billing info is fetched for all organization users but only the owner can access it in the billing API.
Now the info will only be fetched if the current user is an owner of the organization.
> fix(dashboard): fetch billing info only when owner

- apps/api/src/sandbox/managers/backup.manager.ts
If registry url has a scheme (http/https), backups fail to create because of an invalid reference format
> fix(api): strip scheme from registry on backup create

- apps/cli/views/snapshot/info.go
Fixes the CLI sometimes having a pointer dereference error for snapshot size on small terminal widths
> fix: cli snapshot size pointer

- apps/cli/cmd/snapshot/push.go
Adds timestamp tag to transient images to prevent the wrong version being served in cases of frequent image name + tag reusing
> fix: add timestamp tag to transient images

- apps/daemon/pkg/git/push.go
Removed the `+` from the push refspec that caused force push to be by default. We should add force as an option in the push api call.
> fix(daemon): remove default force push

- apps/api/src/sandbox/managers/sandbox.manager.ts
- apps/api/src/sandbox/services/runner.service.ts
Added a check to only start archiving sandboxes on runners that are below the threshold.
> fix(api): limit auto-archive operations per runner

- apps/api/src/sandbox/managers/sandbox.manager.ts
- package.json
- yarn.lock
Replaces the existing polling mechanism with query streaming. The current polling mechanism is inefficient and can cause some sandboxes to wait for the state change for a long time (possibly indefinitely).
Query streaming ensures that all pending state changes will be processed.
> Sync items stream

- apps/api/src/sandbox/managers/sandbox.manager.ts
Limit the sync items batch size and process all the items in smaller batches.
> fix: limit sync items batch

- apps/api/src/sandbox/managers/snapshot.manager.ts
Remove snapshot from DB after cleanup job. If other snapshot runners depend on the internal image, their cleanup is skipped and the snapshot is still removed from the db.
> fix(api): always remove snapshot after cleanup

- apps/api/src/sandbox/entities/sandbox.entity.ts
Sandbox archived state will be set earlier now. This will prevent unnecessary job iterations for sandboxes that have completed archives.
> fix(api): set archived state on backup state completed

- apps/api/src/sandbox/entities/sandbox.entity.ts
Fixes a small regression where the runnerId wouldn't be removed from an archived sandbox.
> fix(api): remove runnerId on archive

- apps/docs/gt.config.json
Remove outdated gt.config.json "baseUrl" pointing to old version of GT API
GT was alerted of translation upload issues by the Daytona team. These were caused by the gt.config.json pointing to an outdated API via the "baseUrl" field. The config no longer requires a "baseUrl" field and will pick up the current API automatically. Translations are already completed and stored, so re-running the translate command will now fetch an update them immediately.
> gt: updating gt.config.json API routing

- apps/api/src/sandbox/services/sandbox.service.ts
`stopped | archived` sandboxes should be able to start as well. Previously, only `archiving | archived` sandboxes could be started.
> fix(api): allow start from stopped archiving sandboxes

- apps/docs/astro.config.mjs
- apps/docs/src/assets/sidebar/proxy-link.svg
- apps/docs/src/content/config.ts
- apps/docs/src/content/docs/en/custom-preview-proxy.mdx
- apps/docs/src/content/i18n/en.json
Added a custom preview proxy page to the docs that elaborates on what a custom proxy can do and to point to example implementations.
> feat(docs): custom preview proxy page

- apps/proxy/pkg/proxy/warning_page.go
Warning page is not necessary for websocket requests so we skip it always.
> fix(proxy): skip warning page on websocket request

- apps/api/src/sandbox/managers/backup.manager.ts
- apps/api/src/sandbox/services/sandbox.service.ts
- apps/docs/src/content/docs/en/python-sdk/async/async-daytona.mdx
- apps/docs/src/content/docs/en/python-sdk/async/async-sandbox.mdx
- apps/docs/src/content/docs/en/python-sdk/sync/daytona.mdx
- apps/docs/src/content/docs/en/python-sdk/sync/sandbox.mdx
- apps/docs/src/content/docs/en/sandbox-management.mdx
- apps/docs/src/content/docs/en/typescript-sdk/daytona.mdx
- libs/sdk-python/src/daytona/_async/sandbox.py
- libs/sdk-python/src/daytona/_sync/sandbox.py
- libs/sdk-python/src/daytona/common/daytona.py
- libs/sdk-typescript/src/Daytona.ts
- libs/sdk-typescript/src/Sandbox.ts
Added an `ephemeral` param when creating a sandbox.
The parameter sets the `autoDeleteInterval` to 0 on the API.
> feat(sdk,docs): ephemeral sandboxes

- apps/dashboard/src/pages/Dashboard.tsx
This PR resolves an issue where sometimes the user was redirected to the wallet page due to insufficient funds even in situations where we would not want to do that (e.g. accepting an invitation to join another organization).
The redirect logic now includes a list of excluded routes that can be updated as we go for any new cases we encounter.
> fix(dashboard): exclude some routes from empty wallet redirect

- apps/proxy/pkg/proxy/get_target.go
Caches the proxy auth key with the sandbox id as the cache key. This prevents unauthorized access for cached auth keys.
> fix(proxy): cache auth key with sandbox id

- apps/proxy/pkg/proxy/warning_page.go
Added a list of browsers that should be detected.
Fixes an issue where client libraries (e.g. `axios` or `requests`) were detected as browsers.
> fix(proxy): browser detection

- apps/api/src/api-key/api-key.controller.ts
- apps/api/src/api-key/api-key.service.ts
- apps/api/src/api-key/dto/api-key-list.dto.ts
- apps/dashboard/src/components/ApiKeyTable.tsx
- apps/dashboard/src/pages/Keys.tsx
- libs/api-client-go/api/openapi.yaml
- libs/api-client-go/api_api_keys.go
- libs/api-client-go/model_api_key_list.go
- libs/api-client-python-async/daytona_api_client_async/api/api_keys_api.py
- libs/api-client-python-async/daytona_api_client_async/models/api_key_list.py
- libs/api-client-python/daytona_api_client/api/api_keys_api.py
- libs/api-client-python/daytona_api_client/models/api_key_list.py
- libs/api-client/src/api/api-keys-api.ts
- libs/api-client/src/models/api-key-list.ts
This PR introduces support for system admins and organization owners to manage (list, revoke) all keys  within an organization.
> refactor(api,dashboard): org owners can manage all api keys within organization

- .github/workflows/build_devcontainer.yaml
Use GITHUB_TOKEN instead of GITHUBBOT_TOKEN
> chore: update ghcr.io secret value

- .github/workflows/release.yaml
- apps/docs/astro.config.mjs
- nx.json
- package.json
Added a release pipeline that can be manually triggered from our repo.
The release pipeline will do the following:
- Build all projects to ensure integrity
- Run `nx release` that will create a github release with an appropriate changelog
- Publish all projects (currently that includes publishing our SDKs to NPM and PyPi)
> chore: add release pipeline

- apps/api/src/sandbox/controllers/sandbox.controller.ts
Make sure the update event belongs to the target sandbox before applying the sandbox update.
> fix(api): update sandbox only upon belonging events

- apps/runner/pkg/api/controllers/sandbox.go
- apps/runner/pkg/docker/container_configs.go
- apps/runner/pkg/docker/create.go
- apps/runner/pkg/docker/start.go
Previously, we inspected the image to determine the `WorkingDir`, which could fail when the image hadn’t been pulled yet. This change reads the `WorkingDir` from the container config instead, providing the same `WorkingDir` value while avoiding pre-pull inspect failures and improving safety.
> fix(runner): get WorkingDir from container config to avoid inspecting unpulled images

- README.md
Makes the TypeScript example more consistent by actually using a TypeScript sandbox. Aligns with the official documentation at https://www.daytona.io/docs/en/typescript-sdk/
- Changed `language: 'python'` to `language: 'typescript'` in TypeScript example.
- Updated code sample from `print("Sum of 3 and 4 is " + str(3 + 4))` to `console.log("Sum of 3 and 4 is " + (3 + 4))`
> docs(Readme): Update TypeScript example to use typescript sandbox

- apps/api/src/docker-registry/entities/docker-registry.entity.ts
- apps/api/src/docker-registry/services/docker-registry.service.ts
- apps/api/src/migrations/1757513754038-migration.ts
Adds fallback registry logic for sandboxes that don't have corresponding region in registry
> feat: fallback registry logic

- apps/api/src/sandbox/managers/backup.manager.ts
Updates to the backup action ordering:
1. Manual archive call
2. Auto-archive poller
3. Ad-hoc backup poller
4. Non-existent/old last backup timestamp
5. Oldest sandbox creation timestamp
> fix: optimize backup ordering

- apps/docs/.env
- apps/docs/.env.example
- apps/docs/.gitignore
- fixes default docs builds that require PUBLIC_WEB_URL to be set
> chore: add docs .env to git

- apps/cli/pkg/minio/minio.go
This fixes the creation of incorrect build hashes which would cause directories with different contents to have the same cache and this be incorrectly fetched and reused.
> fix(cli): seek to tar start before hash calculation

- apps/cli/cmd/common/logs.go
The CLI now ignores the stream read error when the context had been cancelled instead of logging it unnecessarily
Closes #2200
> fix(cli): ignore cancelled stream error

- apps/api/src/sandbox/managers/sandbox.manager.ts
Take newer sandboxes first when syncing.
> fix(api): sync newer sandboxes first

- apps/api/src/migrations/1759241690773-migration.ts
This PR fixes missing default values for capacity in auto-generated migration
> fix(api): add default for capacity in migration

- apps/api/src/sandbox/services/runner.service.ts
This PR includes a check for when runner is sending invalid metrics when calculating runner score
> fix(api): add check for handling invalid runner metrics on score calc

- apps/api/src/sandbox/managers/snapshot.manager.ts
Fixes API server error when images for snapshots are pulled from the registry via a custom port. This is useful for development using a local Docker setup where registry is deployed on 6000 port
Closes #2564
> fix(api): allow snapshots creation from images from registries with ports

- apps/runner/Dockerfile
Adds the SERVER_URL env var to the runner dockerfile.
Closes #2568
> chore(runner): add server url to dockerfile

- apps/dashboard/src/pages/Sandboxes.tsx
Added a missing condition for warm pool sandboxes when updating the sandbox list in the dashboard when a sandbox state updated event is received.
> fix(dashboard): add warm pool condition when handling sandbox websocket events

- libs/sdk-typescript/src/Process.ts
> fix(sdk): use websocket protocols for serverless runtime
