README.md
I've added Algora badges to the README and removed some irrelevant entries.
Closes #113
=> Algora badges

pkg/cmd/whoami.go
=> fix: remove legacy whoami info

pkg/views/workspace/info/view.go
- This PR is to improve `daytona info` command in cli
- Added support to display WorkspaceId, Target, RepositoryUrl
Fixes #114 
/claim #114 
This PR addresses issue #114
=> Improve info command

pkg/views/workspace/list/view.go
Adds 'TARGET' column to Daytona list view.
This PR addresses issue #133
/claim #133
=> feat: add TARGET column to daytona list

pkg/server/config/config.go, pkg/server/provisioner/provisioner.go
Deleting workspace logs
Added code to delete workspace logs directory on deleting the workspace
This PR addresses issue #70 
/claim #70
=> delete workspace logs dir on deleting workspace

pkg/os/os.go
This PR addresses #145. With these changes, modified the judgment of uname length and adjusted it to include the three most basic fields according to the judgment logic.
This PR addresses issue #145
=> fix: uname length judgment

.devcontainer/devcontainer.json, go.mod, pkg/cmd/workspace/create.go, pkg/server/api/controllers/workspace/create.go
Updated Go to 1.22.1
Closes #158
=> chore: update Go to 1.22.1

pkg/views/workspace/list/view.go
Added `Branch` to `daytona list` command after `Repository` Column for better purpose
Fixes #84
/claim #84
This PR addresses issue #84
=> feat: add Branch to list command

pkg/cmd/provider/install.go, pkg/cmd/provider/provider.go, pkg/cmd/provider/uninstall.go, pkg/cmd/provider/update.go
This PR contributes the `daytona provider update [--all]` command which will allow the user to choose an installed provider and update it to the latest available version (or update all with the `--all` flag).
Closes #163
=> Provider update

hack/providers/manifest.json
=> chore: add .exe to windows providers in manifest

cmd/daytona/config/const.go, internal/util/workspace.go, pkg/cmd/git_cred.go, pkg/cmd/gitprovider/add.go, pkg/cmd/gitprovider/delete.go, pkg/cmd/workspace/create.go, pkg/gitprovider/git_provider.go, pkg/gitprovider/gitlab.go, pkg/server/api/docs/docs.go, pkg/server/api/docs/swagger.json, pkg/server/api/docs/swagger.yaml, pkg/serverapiclient/api/openapi.yaml, pkg/serverapiclient/docs/GitProvider.md, pkg/serverapiclient/docs/Project.md, pkg/serverapiclient/model_git_provider.go, pkg/serverapiclient/model_project.go, pkg/types/server.go, pkg/views/gitprovider/select.go
Added support for self-managed GitLab installations when running "daytona git-providers add"
This PR addresses issue #119
=> GitLab self managed

pkg/cmd/workspace/code.go
Don't log error if there isn't any in the `code` command.
=> fix: code cmd error log

pkg/cmd/server/server.go, pkg/server/server.go, pkg/views/util/globals.go
This PR contributes a message that the server has started and explains how the user can connect to it remotely. The message can be observed in the screenshots below.
Closes #210
=> feat: server started message

pkg/cmd/profile/add.go
Fixed pre-filled field.
closes #213
/claim #213
=> chore : fix the prefilled field when flag value is passed

README.md
In README besides installation via provided script we set instructions on how to download specific binary according to users OS architecture.
closes https://github.com/daytonaio/daytona/issues/107
N/A
N/A
=> chore: add manual installation instruction

README.md
Added Windows single command installations for PowerShell, separated some bash comments into regular text to properly utilize the command copy button.
=> chore: readme quick start

PREPARING_YOUR_CHANGES.md, README.md
Minor typo fixes from #137, #155.
=> chore: minor typo fixes

.github/workflows/support_stale_and_close.yaml
Prevent actions from running on forks.
This PR addresses issue #232
=> Fix action forks

internal/util/log_reader.go
Logs reader used to invoke "tail" command which is not defined on Windows. Now replaced by implementing a reader which doesn't have the "tail" dependency
This PR addresses issue #204 
Opted for file reader implementation because Windows has no direct "tail" command equivalent
=> fix: logs reader

pkg/views/util/help.go
Update "help" command to reflect the readme instructions - a target is now set instead of adding a provider to get started
=> chore: update help

pkg/cmd/workspace/info.go
Go file imports unused package - fix running and building
=> fix: go fix run build

pkg/server/api/docs/docs.go, pkg/server/api/docs/swagger.json, pkg/server/api/docs/swagger.yaml, pkg/serverapiclient/api/openapi.yaml, pkg/serverapiclient/docs/Project.md, pkg/serverapiclient/docs/ServerConfig.md, pkg/serverapiclient/model_project.go, pkg/serverapiclient/model_server_config.go
Minor fix for syncing the server config in the api client.
=> fix: run swagger to update server config

.github/workflows/lint_pr.yaml
This PR contributes lint and swagger checks for all PRs. This will improve PR review processes.
To be merged after #261 and #262
=> chore: PR lint actions

pkg/cmd/workspace/create.go, pkg/views/workspace/status/view.go
This PR includes a minor fix for workspace creation logging. The issue was related to parsing websocket messages and rendering lines in the terminal.
=> fix: minor fix for workspace creation logging

.github/workflows/support_stale_and_close.yaml
This PR adds `never stale` and `enhancement` as labels that can not go stale.
=> chore: exempt never stale and enhancement labels from going stale

pkg/views/profile/list.go, pkg/views/provider/list.go, pkg/views/server/apikey/list.go, pkg/views/target/list/view.go
Minor table view rendering issue with a missing newline at the end.
This PR addresses issue #307
=> fix: minor table render issue

cmd/daytona/config/ssh_file.go
Creates .ssh folder if doesn't exist
/claim #312 
This PR addresses issue #312
=> fix: create .ssh folder

README.md, pkg/cmd/workspace/create.go
Renamed the `--connect` flag to `--code`.
=> fix: rename --connect to --code

pkg/cmd/target/remove.go, pkg/cmd/target/set.go, pkg/cmd/workspace/create.go, pkg/views/target/select.go, pkg/views/target/view.go, pkg/views/util/globals.go, pkg/views/workspace/selection/view.go
Adds an "Active profile: ..." footer to all selection list TUI views - IDE selection, workspace selection and target selection.
This PR closes #298
=> feat: display active profile in views

.github/workflows/license_check_pr.yaml, .licenserc.yaml
Github Action that will check if any of the processed files are missing license headers.
N/A
N/A
N/A
=> chore: add license check

pkg/server/api/server.go
There should be an option to register public endpoints - Swagger dashboard shouldn't be protected.
=> feat: make swagger endpoints public

README.md
Added PH badges, removed PH banner.
Additionally increased gif for better readability by 10% to 50%.
=> chore: added PH badges, removed banner

.golangci.yaml, .vscode/settings.json, go.mod, go.sum, internal/testing/agent/mocks/apiserver.go, internal/testing/agent/mocks/gitservice.go, internal/testing/agent/mocks/sshserver.go, internal/testing/agent/mocks/tailscaleserver.go, internal/util/apiclient/server/conversion/project.go, pkg/agent/agent_test.go
This PR includes a simple test for the Daytona Agent. Additionally, it introduces a new convention for writing tests into this repo.
- Mocks (implemented with [testify](https://github.com/stretchr/testify?tab=readme-ov-file#mock-package)) should be used to Unit test complex services (such as the Agent)
- Mocks should be implemented in the `internal/testing/PACKAGE_NAME/mocks` package.
=> test: add agent test

pkg/cmd/workspace/delete.go
Workspace removal confirmation have been added to `daytona remove`
This PR addresses issue #360
/claim #360 
https://github.com/daytonaio/daytona/assets/103899034/2c456a5a-aaf3-4abf-9039-6afbe93c8710
=> feat: confirmation on workspace removal

pkg/api/controllers/log/websocket.go, pkg/cmd/server/server.go, pkg/provider/manager/manager.go, pkg/provisioner/provisioner.go, pkg/server/apikeys/service.go, pkg/server/gitproviders/service.go, pkg/server/providertargets/service.go, pkg/server/server.go, pkg/server/workspaces/service.go
Added interfaces for services. Relying on concrete types/structs prevents unit testing of parent components. This refactor was a prerequisite for implementing tests.
=> refactor: service interfaces

internal/testing/logger/logger.go, internal/testing/logger/mocks/logger.go, internal/testing/provider/targets/store.go, internal/testing/server/apikeys/store.go, internal/testing/server/workspaces/mocks/api_key_service.go, internal/testing/server/workspaces/mocks/provisioner.go, internal/testing/server/workspaces/store.go, pkg/server/workspaces/create.go, pkg/server/workspaces/error.go, pkg/server/workspaces/get.go, pkg/server/workspaces/list.go, pkg/server/workspaces/remove.go, pkg/server/workspaces/service_test.go, pkg/server/workspaces/start.go, pkg/server/workspaces/stop.go
This PR adds unit tests for the the workspace service.
=> test: workspace service unit tests

pkg/api/controllers/gitprovider/gitprovider.go
Hide git provider tokens when listing
=> feat: hide token when listing git providers in api

.devcontainer/devcontainer.json
Changed the DevContainer image tag to latest so it gets repulled on every rebuild.
Closes #403
=> chore: change devcontainer image tag to latest

pkg/os/chmod.go
=> fix: close file in the ChmodX func

pkg/server/workspaces/service_test.go
Added container registry store that was not added in #415.
=> test: workspace service fix

internal/util/apiclient/server/conversion/project.go
This PR fixes a regression of the agent test that failed because of a faulty DTO conversion.
=> fix: project DTO conversion

.vscode/launch.json, internal/util/workspace.go, pkg/agent/config/config.go, pkg/cmd/agent/agent.go, pkg/docker/create.go, pkg/ide/browser.go
With this PR, the workspace dir env was removed and now the agent clones the project repo inside the user's home directory.
=> fix: remove workspace dir env

pkg/server/providertargets/service_test.go
This PR adds unit tests for the the providertargets service.
=> test: add providertargets tests

pkg/agent/ssh/server.go
Logs cleanup/refactor leftovers from the initial development.
=> refactor: logs

pkg/server/apikeys/apikeys_test.go, pkg/server/apikeys/service_test.go, pkg/server/apikeys/validate_test.go
This PR adds unit tests for the the api-keys service.
=> test: add apikeys tests

pkg/cmd/server/server.go
This PR adds waiting for the server to start before exiting the `daytona server -d` command.
Closes #446
=> fix: wait for server to start in daemon mode

pkg/views/workspace/create/workspacedata.go
Fixes "workspace name already exists" regression in version v0.13.0-alpha.7
Closes #471
=> fix: workspace exists check

.devcontainer/devcontainer.json
Added `CGO_ENABLED=0` to the Dev Container spec to be in sync with our release requirements.
=> chore: add CGO_ENABLED=0 to the devcontainer spec

pkg/cmd/ports/forward.go, pkg/frpc/frpc.go, pkg/server/server.go
This PR contributes a health check function for FRPC connections. The health check is used when starting the Daytona server to make sure the connection is established. This is part of the solution for #427.
Closes #427.
=> feat: frpc health check

README.md, cmd/daytona/config/config.go, pkg/cmd/cmd.go, pkg/cmd/server/daemon/daemon.go, pkg/cmd/server/serve.go, pkg/cmd/server/server.go, pkg/views/server/confirm_daemon.go
Changes the default state of Daytona Server to daemon (when running `daytona server`)
Adds `daytona serve` which runs the Daytona Server in the current terminal session
Adds `daytona server start` alias for `daytona server`
This PR addresses issue #283
=> feat: serve verb, daemon default

pkg/api/server.go
This PR adds a `/health` route to the API server that is used as part of the health check process.
Closes #499
=> feat: api server health check route

pkg/cmd/cmd.go, pkg/cmd/gitprovider/add.go, pkg/cmd/gitprovider/gitprovider.go, pkg/cmd/target/set.go, pkg/cmd/target/target.go, pkg/views/initial/view.go
Changes/rearranges the commands on the initial `daytona `command screen
Closes #488 
Previous
New
=> feat: initial screen command options

pkg/cmd/workspace/code.go
Changing `daytona code` message from `Opening workspace project` to `Opening project <name> from workspace <name>` to make the action clearer
Closes #491 
=> feat: daytona code message wording

pkg/views/common.go, pkg/views/workspace/create/configuration.go, pkg/views/workspace/create/summary.go
This PR introduces a text input to configure environment variables in the advanced project configuration page.
=> feat: project env variables configuration input

cmd/daytona/main.go, pkg/cmd/cmd.go, pkg/cmd/ports/forward.go, pkg/cmd/workspace/info.go, pkg/cmd/workspace/start.go, pkg/cmd/workspace/stop.go, pkg/cmd/workspacemode/forward.go, pkg/cmd/workspacemode/git_cred.go, pkg/cmd/workspacemode/info.go, pkg/cmd/workspacemode/start.go, pkg/cmd/workspacemode/stop.go, pkg/cmd/workspacemode/workspace_mode.go
Refactors the way commands are added to the "root command" when in workspace mode. This is now in a separate package and the workspace mode check is done only once
=> refactor: workspace mode command

pkg/cmd/target/set.go
Target set command aliases - add edit update register
Closes #514
=> feat: target command aliases

pkg/agent/ssh/config/config.go, pkg/agent/ssh/server.go, pkg/cmd/workspace/create.go, pkg/cmd/workspace/ssh-proxy.go, pkg/ide/jetbrains.go
This PR fixes windows build issues caused by importing the agent ssh server. Now the SSH config is a separate package.
=> fix: separate ssh config

.devcontainer/devcontainer.json, .devcontainer/postcreate.sh, internal/util/workspace.go
This PR enables Daytona development inside a Daytona Workspace. The issue was that the app would always start in the agent mode as it would detect the Workspace environment.
=> Devenv fix

go.mod, go.sum, pkg/cmd/ports/forward.go
Added Qr code for tunnel links
/claim #444
Closes #444
=> feat: add qr code for tunnel links

pkg/cmd/target/remove.go
allow specifying a targetname as an arg to daytona target remove command
Closes #544
/claim #544
=> feat: allow removing target by specifying target name as an arg

pkg/views/gitprovider/select.go
Suggestion to move all Git providers except for GitHub, GitLab and Bitbucket to "Other" when adding new authentication.
This keeps the most used options visible on top as there are three more less common Git providers incoming soon.
Other:
=> feat: git provider adding ux

README.md
Just an update for the Slack invite link.
=> docs: update Slack link

pkg/cmd/provider/install.go, pkg/cmd/provider/update.go, pkg/provider/manager/installer.go, pkg/provider/manager/manifest.go, pkg/server/providers.go
Fix provider install UI so it doesn't show all of the available providers and their versions but only latest version of each provider.
Closes #622
=> fix: Improve provider install UI

pkg/cmd/profile/delete.go
Have repro and tested the changes
/claim #645 
Closes #645
=> fix 'profile rm' command, #645

hack/install.sh
When doing an upgrade to the new version if server will stop and then upgrade will start
Closes #627
/claim #627
This PR addresses issue #627
https://github.com/daytonaio/daytona/assets/103899034/afd42c5d-2234-4a08-9c65-c39c2dbe855f
=> fix: stop server before upgrading

pkg/cmd/workspace/delete.go, pkg/views/workspace/selection/view.go, pkg/views/workspace/selection/workspace.go
/claim #378
Closes #378 
https://github.com/daytonaio/daytona/assets/48802836/2fd9d261-4385-4c34-b08f-e09a2365fd56
The video shows how we can delete multiple workspaces directly from UI as suggested by @idagelic
=> FEAT: Ability to delete  multiple workspaces. Issue #378

pkg/server/defaults.go
Minor fix to the builder image default value.
=> fix: builder image default value

pkg/cmd/workspace/util/creation_data.go
Minor fix for the default project creation flow (without going into the advanced configuration).
=> fix: default project creation

pkg/builder/factory.go
Minor fix on the server for choosing the devcontainer builder explicitly.
=> fix: devcontainer builder choice

pkg/views/logs/display.go
This PR includes some creation logs fixes - mostly regarding multiple "entries" being included in just one JSON log line. Fixes some parts missing a project prefix or it overwriting the current line.
To be merged after #708
=> fix: logging improvements

internal/cmd/tailscale/forward.go, pkg/cmd/ports/forward.go, pkg/cmd/workspacemode/forward.go, pkg/ide/browser.go
This PR fixes a goroutine deadlock when forwarding a port.
=> fix: port forward deadlock

pkg/cmd/workspace/code.go, pkg/cmd/workspace/create.go
update ide opening message
make ide name dynamic in ide opening message
Closes #652
=> feat: update ide opening message

pkg/ide/vscode.go
a little less reading for someone trying out Daytona on OSX for #739
=> Point the user to the OSX specific documentation for (install and) add to PATH

internal/util/cmd.go, pkg/cmd/apikey/api_key.go, pkg/cmd/cmd.go, pkg/cmd/containerregistry/containerregistry.go, pkg/cmd/gitprovider/gitprovider.go, pkg/cmd/ide.go, pkg/cmd/ports/forward.go, pkg/cmd/profile/profile.go, pkg/cmd/profile/use.go, pkg/cmd/profiledata/env/env.go, pkg/cmd/provider/provider.go, pkg/cmd/server/serve.go, pkg/cmd/server/server.go, pkg/cmd/target/target.go, pkg/cmd/whoami.go, pkg/cmd/workspace/code.go, pkg/cmd/workspace/create.go, pkg/cmd/workspace/delete.go, pkg/cmd/workspace/info.go, pkg/cmd/workspace/list.go, pkg/cmd/workspace/ssh.go, pkg/cmd/workspace/start.go, pkg/cmd/workspace/stop.go, pkg/cmd/workspacemode/forward.go, pkg/cmd/workspacemode/info.go, pkg/cmd/workspacemode/start.go, pkg/cmd/workspacemode/stop.go, pkg/cmd/workspacemode/workspace_mode.go
group help menu commands
This PR addresses issue #614
closes #614
/claim #614
=> feat: group help menu commands

pkg/views/server/config.go
Finally added the missing properties in the correct file and in correct way!
Added the following properties:
- Providers Directory
- Registry URL
- Server Download URL
- Logs Path should be renamed to Log File Path
- FRPS Port
- FRPS Protocol
Closes #780 
/closes #780 
/claim #780
=> fix: properties missing from server config view

pkg/cmd/provider/install.go, pkg/cmd/workspace/util/repository_wizard.go, pkg/views/util/spinner.go
Added a loader for provider installation, for some feedback to the user. Added a message parameter to the WithSpinner() function to pass the loader message.
closes #734
claim #734
New Install message 
[Kazam_screencast_00002.webm](https://github.com/user-attachments/assets/71cb4ac5-ca51-4392-84ac-ef7c4fd8158b)
=> feat: added loader for Provider install progress

pkg/cmd/workspace/list.go, pkg/views/common.go, pkg/views/containerregistry/select.go, pkg/views/target/select.go, pkg/views/workspace/list/view.go, pkg/views/workspace/selection/view.go
Show active profile on workspace list similar to info select view
/claim #753
closes #753
=> feat: show active profile on workspace list

pkg/views/profile/create.go, pkg/views/profile/select.go
Fixes 'daytona profile' command.
Closes #778 
/claim #778
=> fix: creation of a new profile through <daytona profile>

docs/daytona_server_logs.md, hack/docs/daytona_server_logs.yaml, internal/util/apiclient/websocket_log_reader.go, internal/util/log_reader.go, pkg/api/controllers/log/websocket.go, pkg/cmd/server/logs.go
Suppresses error for missing log file
Closes #696
/claim #696
=> fix: handle missing log file error in server logs

.github/workflows/update_swagger_push_tag.yaml
Github Action that will update swagger version and also push new tag
=> chore: add swagger update and tag create github-action

pkg/cmd/profile/delete.go, pkg/cmd/profile/edit.go, pkg/cmd/profile/use.go, pkg/views/profile/select.go
fix: quitting the profile TUI results in FATAL error
Fixed this issue with proper handling.
This PR addresses issue #646 
Closes #646 
/claim #646 
https://github.com/user-attachments/assets/f9b56155-be3f-429c-94e0-857edffeead9
> [!NOTE]
> After the new update, `daytona profile use` is used to test the changes.
=> fix: quitting the profile TUI results in FATAL_ERR

pkg/api/middlewares/telemetry.go
This PR removes sending project state update events to the telemetry backend. Additionally, added a `remote_profile` property to API request data that indicates if the user used a remote profile when making the request.
=> fix: do not send state update telemetry events

pkg/docker/create_devcontainer.go
This PR ensures that host env variables are inherited when creating a devcontainer project
Closes #860 
This will require providers to be updated with `daytona provider update`
=> fix: inherit host env vars when creating devcontainer

pkg/docker/README.md
Added a README to the `docker` pkg that explains its purpose and testing procedure.
=> docs: add README to the docker pkg

pkg/docker/create_devcontainer.go
Now the localEnv is correctly overridden by the host env variables. This fixes a bug when running daytona in a non-linux non-daytona-user environment.
Providers will need to be updated with `daytona provider update`
=> fix: devcontainer localEnv override

pkg/cmd/server/configure.go, pkg/views/server/configure.go
Allow the user to submit the long TUI form earlier using the shortcut key [Ctrl + S].
[list of supported keymaps ](https://github.com/charmbracelet/bubbletea/blob/master/key.go#L261)
closes #710 
/claim  #710 
=> fix: allow users to submit the form earlier

pkg/cmd/purge.go, pkg/cmd/server/serve.go, pkg/provider/manager/manager.go, pkg/server/config.go, pkg/server/headscale/server.go, pkg/server/purge.go, pkg/server/registry/service.go, pkg/server/server.go, pkg/server/types.go, pkg/telemetry/server_events.go, pkg/views/purge/default_profile_notice.go
Server should now be stopped when purging. Also added separate purge processes for the tailscale server, provider manager and local container registry.
=> refactor: purge cmd

internal/util/apiclient/websocket_conn.go
Fixes getting creation logs while running Daytona in Daytona
Closes #881
=> fix: daytona creation logs in daytona

internal/util/apiclient/websocket_log_reader.go
This PR resolves TODOs awaiting #696 
Resolved after #696
=> fix: resolve websocket log-reader todos

.vscode/launch.json
Added appropriate dev env variables to vscode launch configurations.
=> chore: add dev env variables to vscode launch configs

internal/constants/get_daytona_script.go
Prefer to use wget instead of curl to download the binary because it automatically handles interruptions. Additionally, add a retry policy if the download fails.
Closes #940
=> fix: handle binary download interruptions

docs/daytona_server_logs.md, hack/docs/daytona_server_logs.yaml, internal/util/apiclient/websocket_log_reader.go, internal/util/log_reader.go, pkg/api/controllers/log/websocket.go, pkg/cmd/server/logs.go
This PR removes retry logs query which caused inconsistency in workspace creation logs.
=> fix: remove log retry

pkg/gitprovider/github.go
Fixes an infinite loop issue that could appear due to an incorrect local variable assignment.
Also refactors the way GitHub Git provider finds the relevant branch for a commit by reducing the number of API calls.
=> fix: commit clone infinite loop

pkg/views/common.go
This PR fixes inability to delete environment variables when setting them.
Closes #906 
https://github.com/user-attachments/assets/c15a1c26-f516-4e02-878c-acaf930aa21f
=> fix: register env var deletion

docs/daytona_code.md, docs/daytona_create.md, hack/docs/daytona_code.yaml, hack/docs/daytona_create.yaml, pkg/cmd/workspace/code.go, pkg/cmd/workspace/create.go
update list of supported ides in daytona code and daytona create
closes #962
/claim #962
=> fix: update list of supported ides in daytona code and create

internal/util/apiclient/websocket_conn.go, internal/util/apiclient/websocket_log_reader.go, pkg/cmd/build/logs.go, pkg/cmd/server/logs.go, pkg/cmd/workspace/create.go
Added contexts to log read for better flow control and cancellation.
Closes #990
=> fix: log read cancellation

docs/daytona_start.md, hack/docs/daytona_start.yaml, pkg/cmd/workspace/create.go, pkg/cmd/workspace/start.go, pkg/cmd/workspace/util/workspace.go, pkg/views/ide/code.go
automatically open ide if --code flag is passed to daytona start 
closes #986
/claim #986
=> feat: add code flag to daytona start cmd

pkg/views/workspace/list/view.go, pkg/views/workspace/selection/workspace.go
Workspace selection prompts are now sorted from newest
Closes #1013
=> fix: ws select sort

pkg/gitprovider/bitbucket.go, pkg/gitprovider/bitbucketserver.go
This PR fixes invalid getting of a default branch for BitBucket git provider.
https://github.com/user-attachments/assets/76032a7e-c212-4b0a-b41c-3270f216efbd
=> fix: bitbucket default branch setting

internal/constants/get_daytona_script.go
Before downloading the binary from the server, now the project will attempt to download it directly from our storage.
This will greatly improve creation times of remote workspaces because the process will not depend on users' upload speed.
=> feat: attempt direct binary download on project create

go.mod, go.sum
This PR resolves the issue of Daytona info incorrectly displaying "(n uncommitted changes)" despite no actual changes in the repository by updating go-git to commit c127d1b. The issue stemmed from go-git not excluding .gitignore paths, which has been fixed in [go-git PR #1114](https://github.com/go-git/go-git/pull/1114).
Steps Taken:
Updated go-git to commit c127d1b355353b41e5610cc4c5c6d561e905118a, which includes the fix for .gitignore handling.
Verified that Daytona info output is now correctly synced with git status inside the container.
/claim #745
Closes #745
`tate": {
"gitStatus": {
"currentBranch": "main",
"fileStatus": [
{
"extra": "",
"name": "node_modules/.pnpm/tailwindcss@3.4.1/node_modules/tailwindcss/stubs/config.simple.js",
"staging": "Untracked",
"worktree": "Untracked"
}, …
=> fix: Daytona Info Uncommitted Changes Warning on first create (#745)

pkg/cmd/ide.go, pkg/ide/jetbrains.go
=> feat: add JetBrains gateway installation check

pkg/api/docs/docs.go, pkg/api/docs/swagger.json, pkg/api/docs/swagger.yaml, pkg/apiclient/api/openapi.yaml, pkg/apiclient/docs/ProviderProviderTargetProperty.md, pkg/apiclient/model_provider_provider_target_property.go, pkg/provider/types.go, pkg/views/target/set.go
Added auto-complete functionality to input fields using the huh library. This enhancement integrates the .WithSuggestions method to dynamically provide suggestions as users type, improving user experience by offering a predefined set of options for input fields.
Incorporates suggestions into the getInput function and integrates with existing input handling for improved UX.
Closes #372
/claim #372 
=> feat: add auto-complete functionality to input fields(#372)

hack/project_image/.devcontainer/devcontainer.json
Adds DotNet, Ruby, Rust, Php, Python and Java languages to the default image.
The new image version should be published to the official image registry.
=> feat: support for popular programming languages

docs/daytona.md, docs/daytona_config.md, hack/docs/daytona.yaml, hack/docs/daytona_config.yaml, pkg/cmd/cmd.go, pkg/cmd/config.go, pkg/cmd/profile/list.go, pkg/views/config/view.go, pkg/views/profile/list.go
This PR introduces a `daytona config` command which outputs current user configuration in human readable format as well as JSON and YAML formats.
Closes #1101
=> feat: add daytona config command

pkg/docker/create.go, pkg/docker/create_image.go
Removes UID:GID mapping fix meant for Linux environments for Windows
Closes #1116
=> fix: windows invalid user id mapping

docs/daytona.md, docs/daytona_restart.md, docs/workspace_mode/daytona.md, docs/workspace_mode/daytona_restart.md, hack/docs/daytona.yaml, hack/docs/daytona_restart.yaml, hack/docs/workspace_mode/daytona.yaml, hack/docs/workspace_mode/daytona_restart.yaml, pkg/cmd/cmd.go, pkg/cmd/workspace/restart.go, pkg/cmd/workspacemode/restart.go, pkg/cmd/workspacemode/workspace_mode.go
This PR adds daytona restart workspace command that stops and restarts a workspace. 
closes #1086
=> feat: add daytona restart workspace cmd

pkg/server/workspaces/list.go
This PR fixes the inconsistency present when requesting a verbose workspace list from the API
Closes #1151
=> fix: verbose list inconsistency

hack/install.sh
This PR fixes stopping the Daytona server on install. It now correctly runs the command as the user who first started the server.
Closes #866 
Closes #867 
Closes #955
=> fix: stop server as user on install

.devcontainer/postcreate.sh
Checks if exists and adds the `dtn` alias to `.bashrc` as well inside the devcontainer
=> chore: add dtn alias for bash

pkg/agent/tailscale/server.go
Instead of using the http client to check the health route, now the tailscale status is checked natively using the local client. This approach is more exact and does not fail if the http request times out because of network latency.
=> refactor: tailscale status check in agent

pkg/views/workspace/info/view.go
This PR displays PR number if workspace is created from PR and working branch has not changed
closes #979
=> feat: add PR number in worspace info

pkg/cmd/target/set.go
Skips the target selection TUI screen when running `daytona target set` and choosing a non-installed provider
=> feat: skip target selection view when installing provider during target set

pkg/cmd/workspace/start.go, pkg/cmd/workspace/stop.go, pkg/views/workspace/selection/view.go, pkg/views/workspace/selection/workspace.go
This PR adds support for marking multiple workspaces/projects in start and stop commands similar to daytona delete.
closes #928
@quest-bot loot #928
=> feat: add support for marking multiple workspaces/project for starting/stopping

pkg/cmd/gitprovider/delete.go, pkg/cmd/gitprovider/update.go, pkg/cmd/workspace/create.go, pkg/cmd/workspace/util/creation_data.go, pkg/views/gitprovider/select.go, pkg/views/workspace/selection/gitproviderconfig.go
Makes the Git provider selection use the same appearance as other TUI selection components
=> feat: improve git provider config selection view

pkg/views/workspace/create/configuration.go, pkg/views/workspace/create/summary.go, pkg/views/workspace/create/view.go
this PR fixes the TUI breaks on daytona create
Closes #665 
/claim #665 
=> fix: redraw on terminal resizing while dtn create

cmd/daytona/config/config.go, pkg/cmd/cmd.go, pkg/cmd/profile/list.go
Minor refactor for active profile error handling when none is set. Removed manual profile exemptions.
=> refactor: active profile error handling

pkg/api/controllers/target/create.go, pkg/api/controllers/target/target.go, pkg/api/controllers/targetconfig/list.go, pkg/api/controllers/targetconfig/set.go, pkg/api/docs/docs.go, pkg/api/docs/swagger.json, pkg/api/docs/swagger.yaml, pkg/api/util/mask-options.go, pkg/apiclient/api/openapi.yaml, pkg/apiclient/docs/CreateTargetDTO.md, pkg/apiclient/docs/TargetAPI.md, pkg/apiclient/model_create_target_dto.go, pkg/cmd/provider/install.go, pkg/cmd/server/serve.go, pkg/cmd/target/create.go, pkg/cmd/workspace/create/cmd.go, pkg/cmd/workspace/create/get_target.go, pkg/server/targets/create.go, pkg/server/targets/dto/target.go, pkg/server/targets/service.go, pkg/server/targets/service_test.go
Adds options masking to the target API.
=> fix: mask target options

pkg/cmd/workspace/restart.go, pkg/views/workspace/selection/view.go
Added both interactive and non-interactive multi selection to `daytona restart` command.
=> feat: add multi-select to restart cmd

pkg/docker/create_devcontainer.go
With this PR, the working dir for running the initialize command for a devcontainer is properly set to the project directory.
Closes https://github.com/daytonaio/daytona/issues/1353
This requires an update in all providers.
=> fix: working dir for running devcontainer initialize command

pkg/docker/create_devcontainer.go
Fixes an issue that would cause the creation of a devcontainer to fail if `'` was present. Additionally, quoted env vars in the initializeCommand are correctly interpolated now.
Closes https://github.com/daytonaio/daytona/issues/1360
=> fix: devcontainer config reading

hack/samples/index.json
A dev environment for Julia was missing
Closes #1364 
This PR needs https://github.com/daytonaio/sample-julia/pull/1 to be merged
=> feat: provide sample-julia

pkg/api/docs/docs.go, pkg/api/docs/swagger.json, pkg/api/docs/swagger.yaml, pkg/apiclient/api/openapi.yaml, pkg/apiclient/docs/PrebuildConfig.md, pkg/apiclient/docs/Target.md, pkg/apiclient/docs/TargetDTO.md, pkg/apiclient/model_prebuild_config.go, pkg/apiclient/model_target.go, pkg/apiclient/model_target_dto.go, pkg/models/api_key.go, pkg/models/build.go, pkg/models/common.go, pkg/models/env.go, pkg/models/git_provider_config.go, pkg/models/job.go, pkg/models/target.go, pkg/models/target_config.go, pkg/models/workspace.go, pkg/models/workspace_template.go
This PR removes unnecessary decorators from foreign keys and adds `gorm:"not null"` decorator to all database models.
=> refactor: update gorm decorators

hack/samples/index.json
Closes #1370 
Linked Sample PR: https://github.com/daytonaio/sample-c/pull/1
=> Provide C sample

hack/samples/index.json
This pull request includes an update to the `hack/samples/index.json` file to add a new sample project.
=> samples: add Next.js - OpenSourceSmith sample

hack/samples/index.json
the format was wrong and caused the samples to not work
=> fix: format sample json

hack/samples/index.json
This pull request includes an update to the `hack/samples/index.json` file to add a new sample project.
=> samples: add Next.js - MindmapCopilot sample

hack/samples/index.json
This pull request includes an update to the hack/samples/index.json file to add a new sample project.
=> samples: add Next.js - Recipe Genie sample

hack/samples/index.json
Added Cropify project to the Daytona sample registry.  
- Included Cropify's name, description, and GitHub URL.
=> samples: add React.js - Image Crop sample

hack/samples/index.json
Add Sample Machine Learning for Crop Growth
Added TerraGrow project to the Daytona sample registry.
Included TerraGrow name, description, and GitHub URL.
=> samples: add React.js - Crops ML sample

CONTRIBUTORS.md
Added myself to the list of contributors
=> docs: add MDzaja to contributors

CONTRIBUTORS.md
=> docs: add LDavidBryant to Contributors

hack/samples/index.json
Added Video Generation AI project to the Daytona sample registry.
- Included Video Generation AI's name, description, and GitHub URL.
=> samples: add Next.js - Video Generation AI sample

README.md
This PR expands the "Contributing" section to the readme with details on how to set up a workspace with a fork of our repository. This will make contributing simpler and perhaps more appealing in general.
This PR addresses issue #138 
=> docs: expanded the contributing to Daytona section on README file

hack/samples/index.json
- Included Text Summaziation and Analysis project's name, description and Github url.
=> sample: add React.js - AI text summarization

CONTRIBUTORS.md
=> docs: add @marijancip123 to contributors

hack/samples/index.json
This pull request includes an update to the `hack/samples/index.json` file to add a new sample project.
=> Add Django - Crisis Monitor sample

CONTRIBUTORS.md
Added myself to the list of contributors.
=> docs: add Saralucijad to contributors

hack/samples/index.json
=> Sample: added NextJS- Festigo

hack/samples/index.json
Of rust Actix, from Daytona team prefered themes
=> samples: rust actix

CONTRIBUTORS.md
added myself to the list of contributors
=> docs: add aprojic to contributors

hack/samples/index.json
- Added cooperword to the index.json
=> samples: added cooperword to index

CONTRIBUTORS.md
Added myself to the list of contributors
=> docs: add inovak to contributors

CONTRIBUTORS.md
Added myself to list of contributors
=> docs: Add radisicc to contributors

CONTRIBUTORS.md
Added myself to the list of contributors.
=> docs: add andrejohnson2 to contributors

hack/samples/index.json
This pull request includes an update to the hack/samples/index.json file to add a new sample project.
=> samples: add Python/Streamlit - Linear Predictor sample

hack/samples/index.json
add sample ai carecaddle 
added carecadle project to the daytona 
included carecadle name description and Github URL.
=> added carecradle in index.json

hack/samples/index.json
add sample job assistant for ex-cons
Added ex-con thrive project to daytona
Included ex-con-thrive name, description and Github URL.
=> add sample react.js job assistant

hack/samples/index.json
This pull request includes an update to the hack/samples/index.json file to add a new sample project.
=> samples: add Streamlit - DocBot sample

hack/samples/index.json
Project Link: https://github.com/daytonaio/sample-django-project-manager
=> samples: updated index.json with django/python project

hack/samples/index.json
@Tpuljak This pull request includes a small change to the `hack/samples/index.json` file. The change adds a new Python/Flask-based application called "CodeChatter" to the list of samples by @yashksaini-coder
* [`hack/samples/index.json`](diffhunk://#diff-9a15f7062e293ffb0f015130d051aa7eee1a19b8a24837e15d588348f72a923fR171-R175): Added a new sample application "Python/Flask - CodeChatter" with its description and GitHub URL.
=> samples: Python/Flask - CodeChatter

hack/samples/index.json
- Updated the index to include the `AstroJS + Sanity CMS Blog`
=> Updated the index to include the `AstroJS + Sanity CMS Blog`

hack/samples/index.json
Added the blogging application in index.json file
=> samples: NextJs/MindsDb - WordWave

hack/samples/index.json
=> samples: add therabot

hack/samples/index.json
Added sample job scrapper to index.json file.
Added job scrapper project to Daytona sample registry.
=> samples: React.js - sample-js-job-scaper

hack/samples/index.json
This PR adds the go-crud-redis project in index.json
=> sample: added go crud redis project

hack/samples/index.json
Sample
- This PR adds the `Sample Bun Web Server` project in index.json
=> Added Sample Bun Web Server in index.json

hack/samples/index.json
=> samples: add sample nextjs-github-user-insights app

hack/samples/index.json
#Adds music player to index.json
=> samples: add music player

hack/samples/index.json
Project url: https://github.com/daytonaio/sample-go-nextjs-sbt-blockchain
=> samples: add Next.js & Go - Certify

hack/samples/index.json
This PR is a part of quest 023 in Quira by Daytona. Added entry to hack/samples/index.json.  
This PR is a part of quest 023 on Quira.
=> update index.json in hack/samples.

pkg/views/apikey/notify.go
This PR addresses #1481
Enhanced the API output as per the issue
=> api-key: Enhance Output Format

hack/samples/index.json
=> Add Python-Lunku AI Repo added

hack/samples/index.json
Updated index.json with Devorbit details.
=> samples: added nextjs-devorbit

hack/samples/index.json
Updated index.json to include Briefly project.
=> samples: add React Briefly

cmd/daytona/config/const.go
clarify github scopes, 
Closes #1513
=> fix: clarify github required scopes

pkg/docker/start.go, pkg/docker/start_test.go, pkg/provider/util/project_start_script.go
This update resolves issues with missing dependencies in custom project images by implementing a script. It includes support for various Linux package managers (`apt-get`, `yum`, `apk`, `dnf`, `pacman`, `brew`) and ensures compatibility with Alpine by adding `libc6-compat`. Missing dependencies are explicitly logged to provide transparency to users.
closes #1418 
All providers will need to be updated
dependencies list
- `sudo`
- `git`
- `curl`
- `bash`
^^ Alpine also needs - libc6-compat (as it lacks support for `glibc`)
=> fix: resolve missing dependencies in some custom project images

hack/samples/index.json
Added HopeChain ([sample-android-blockchain](https://github.com/daytonaio/sample-android-blockchain)) android application with tech-stack "Kotlin/Jetpack-Compose" in index.json file.
=> samples: add Kotlin/JetpackCompose - HopeChain

hack/samples/index.json
added gitUrl of [sample-go-web-server]( https://github.com/daytonaio/sample-go-web-server) in index.json file
=> gitUrl updated

hack/samples/index.json
This application provides real-time weather information, including temperature, descriptions, humidity, and wind speed, based on user input.
=> samples: add copilotkit-weather-bot

hack/samples/index.json
Adds astro restaurant app to index.json
=> samples: add astro restaurant app

hack/samples/index.json
=> samples: add nextjs - book summary

hack/samples/index.json
=> Sample index

hack/samples/index.json
=> samples: add QuoteSmith

hack/samples/index.json
Updated index.json to include devbot project.
=> samples: Devbot project added

hack/samples/index.json
Added Application:
{
"name": "Python - AI Recipe Generator",
"description": "The application allows users to upload image of ingredients, analyzes the image, and provides recipe suggestion.",
"gitUrl": "https://github.com/daytonaio/sample-python-recipe-generator"
},
=> samples: python - ai recipe generator

hack/samples/index.json
=> samples: nextjs nexus framework

hack/samples/index.json
Pull Request Title
Add sample code editor to daytona
Description
Added progify to registry
=> samples: add React.js - Progify

hack/samples/index.json
Add sample nextjs sudoku game to daytona
Added sudoku game to registry.
=> samples: add nextjs sudoku game

hack/samples/index.json
Adding PR Tracker
Adding the sample Github PR tracker in `hack/samples/index.json`
=> samples: adding pr tracker

hack/samples/index.json
added project description in index.json
=> Add sample React calendar app to Daytona's sample index

hack/samples/index.json
Add Sample Astro Pet Pilot
Added sample astro pet pilot to registry
=> add sample-astro-pet-pilot

hack/samples/index.json
Add sample recipe finder to daytona.
Add sample react recipe finder to daytona registry.
=> samples: add recipe finder

hack/samples/index.json
=> samples: add Ecotrack

hack/samples/index.json
sample django courier manager 
added sample django courier manager
=> added sample django courier manager

hack/samples/index.json
Adding Sample Python Rag Slim to Daytona registry.
=> Added Sample Python Rag Slim

hack/samples/index.json
Adding Graphql-API with fine grained access control
added Graphql-API with fine grained access control
=> adding project description in index.json

hack/samples/index.json
=> updated index.json

hack/samples/index.json
=> adds Rust HTTP Server

hack/samples/index.json
Added name, description of opinion panel.
=> Integrated Opinion Panel

hack/samples/index.json
=> samples: add nextjs - story generator

hack/samples/index.json
=> Updated index.json with new samples (+5, -0)

hack/samples/index.json
Added my project title: RAG base Osho chatbot and description in iindex.json file.
=> samples: rag chatbot

hack/samples/index.json
=> samples: laravel url extractor

hack/samples/index.json
=> samoles: JavaScript Restaurant

hack/samples/index.json
=> Add Romanch's Sample

hack/samples/index.json
=> pr raied for index.json

hack/samples/index.json
=> samples: add PHP url shortener

hack/samples/index.json
=> update sample index.json

hack/samples/index.json
=> Sample Added

hack/samples/index.json
=> Added rust actix server Sample

hack/samples/index.json
Add a sample for Python FastAPI generated from [copier-pdm](https://github.com/pawamoy/copier-pdm) with pre-configured features.
=> samples: add python fastapi

hack/samples/index.json
=> Samples: Added smart news flow to index.json

hack/samples/index.json
I have added the name, description and giturl of my sample farmer assistance web app in index.json.
=> Add Krishi Mitra (Farmer assistance Web app) in index.json

hack/samples/index.json
=> Add sample entry to index.json

hack/samples/index.json
This pull request introduces HealthBot AI, an intelligent chatbot designed to provide timely text responses for health practitioners. This feature enhances communication within the healthcare sector. The project utilizes Python-Django for the backend and integrates HTML, CSS, and vanilla JavaScript for the frontend.
This change requires a documentation update
I have made corresponding changes to the documentation
=> HealthBot AI: Initial Pull Request

hack/samples/index.json
=> chore: Added Nextjs Aceternity UI sample

hack/samples/index.json
=>  Updated index.json

hack/samples/index.json
=> added link of store

hack/samples/index.json
=> Add my sample("PathGenX-LearningPath Generator") to the index

hack/samples/index.json
Updated with repo url and proj details.
=> Update index.json with Movies_DB project details.

hack/samples/index.json
Users can add tasks based on their priority, mark tasks as complete, or delete them, either through a form or with AI assistance.
=> Priority based todo-list with Daytona

hack/samples/index.json
**Title:** Add EchoBrain to Daytona Sample Index  
**Description:**  
This PR adds EchoBrain, an AI-powered desktop voice assistant, to Daytona’s sample index. EchoBrain enables users to control desktop applications and automate tasks through voice commands, providing a seamless and efficient user experience.  
Changes made:  
- Added EchoBrain entry to `index.json` at a random position to avoid merge conflicts.  
**Why this is needed:**  
EchoBrain demonstrates advanced integration of speech recognition, app automation and TensorFlow models, aligning well with Daytona’s goal of showcasing diverse and innovative projects.
=> Add EchoBrain project to Daytona sample index

hack/samples/index.json
This pull request adds my project to the `hack/samples/index.json` file in the Daytona repository.
- **Project Title**: [Your project name]
- **Tech Stack**: [e.g., React, Tailwind CSS, Framer Motion, Daytona]
- Added my sample in the correct format and position within `index.json`.
N/A (if there’s no specific issue linked).
- Please let me know if there are any changes required.
=> Add my sample to index.json

hack/samples/index.json
Description
I have added the cricket-quira project to the index.json file under hack/samples. This entry describes an interactive and comprehensive website designed for conducting cricket tournaments, built using Vite, Tailwind CSS, React, and Lucide React. The project offers an engaging experience for cricket enthusiasts.
Key Details
Added the following entry to index.json:
{
"name": "Cricket Quira",
"description": "I developed a comprehensive and interactive website for XYZ Organization, which focuses on conducting cricket 
tournaments in various formats. This project was built using Vite, Tailwind CSS, React, and Lucide React, creating an engaging 
user  experience with a variety of features tailored to cricket enthusiasts.",
"url": "https://github.com/Lavavarshney/cricket-quira.git"
} …
=> FEAT: Add cricket-quira to index.json

hack/samples/index.json
Update entry in index.json
NA
NA
NA
=> chore: update entry in index.json

hack/samples/index.json
=> Added the name , description , gitUrl of my project incentix in the index.json file

hack/samples/index.json
=> sample: hackhound

hack/samples/index.json
**Add Discord Bot with Image Generation sample to Daytona**  
---
This PR adds a new sample to the Daytona repository: **Discord Bot with Image Generation**. The bot is written in Python and integrates with Prodia's API to generate images based on prompts received in Discord messages.  
The sample demonstrates:  
- How to create a Discord bot using Python and the `discord.py` library.  
- Integration with external APIs (Prodia's Image Generation API).  
- The use of `.env` files for managing sensitive credentials securely.  
No additional dependencies or documentation updates are required for this change.  
---
N/A  
---
**Bot in Action**:  
1. Prompting the bot:  
```  
!generate a computer hacker
```  
2. The bot responds with:  
- "Generating image..."  
- An image URL from Prodia's …
=> Add Discord Bot with Image Generation sample

hack/samples/index.json
=> Update in index.json

hack/samples/index.json
Add sample hotel booking project
Description
Added Majestic Hotels project to the Daytona sample registry.
Changes
Included Majestic Hotels's name, description, and GitHub URL.
=> samples: add Next.js - Hotel Booking Site

hack/samples/index.json
Updated the `hack/samples/index.json` file to include the new app configuration for my AI Companion project. This change integrates new JSON data as part of Quira Quest 023.
=> Updated hack/samples/index.json

hack/samples/index.json
=> samples: added python+llmware+tkinter/chatbot

hack/samples/index.json
=> added project info in sample index

hack/samples/index.json
=> add md previewer sample

hack/samples/index.json
=> samples: added orbit-wallet4

hack/samples/index.json
Added my project in index.json.
=> samples: added target

hack/samples/index.json
=> sample:Vashude Builder Ai

hack/samples/index.json
my project for daytona challenge
FemOvaAI is an advanced AI-driven system designed to detect Polycystic Ovarian Syndrome (PCOS) from ultrasound images. Utilizing the power of YOLOv8, a cutting-edge object detection model, our system analyzes images to classify them into two categories: "PCOS" and "No PCOS." This enables healthcare professionals to make informed decisions quickly, enhancing the diagnostic process and potentially improving patient outcomes.
=> FemOvaAI  project-s for daytona challenge

hack/samples/index.json
=> updated json

hack/samples/index.json
Added sample project for Daytona challenge -s
=> Added sample project for Daytona challenge -s

hack/samples/index.json
=> samples: added "sundown-studios"

hack/samples/index.json
=> Add ToDo sample

hack/samples/index.json
[Sample_MailSender](https://github.com/Ronit-afk55/Sample_MailSender) Index.json updated
=> updates index.json

hack/samples/index.json
=> sample: SNAKE-CHAIN5

hack/samples/index.json
=> adding sample: Gemini Chat App with Daytona

hack/samples/index.json
Add sample to Daytona's sample index
Add sample from Take daytona for a spin quest.
=> Add sample to Daytona's sample index

hack/samples/index.json
This PR adds the details of my project, Bank Chor, to index.json. The project is a Spring Boot-based bank application integrated with Daytona, featuring functionalities like account creation, deposits, and withdrawals.
=> Add my project details Bank Chor to index.json

hack/samples/index.json
Sample: Crypto-Tracker
Adding my project Crypto-Tracker.
- [ Y] This change requires a documentation update
- [ Y] I have made corresponding changes to the documentation
=> Sample: Adding project crypto tracker

hack/install.sh
Minor fix to checking the version in the install script
=> fix: check version in install script

hack/samples/index.json
Added MindAly-Daytona
I've added MindAly in index.json.
=> Added MindAly-Daytona

cmd/daytona/config/const.go, docs/daytona_code.md, docs/daytona_create.md, hack/docs/daytona_code.yaml, hack/docs/daytona_create.yaml, pkg/cmd/ide.go, pkg/cmd/workspace/code.go, pkg/ide/windsurf.go
adds support for Windsurf IDE
closes #1566 
=> feat: add support for Windsurf IDE

hack/samples/index.json
This PR add Ada, COBOL, Fortran and R samples
This PR addresses issue #1526
N/A
N/A
=> Add Ada, COBOL, Fortran and R

internal/testing/agent/mocks/docker_cred_helper.go, internal/testing/build/store.go, internal/testing/server/targets/store.go, internal/testing/server/workspaces/store.go, pkg/agent/agent_test.go, pkg/cmd/bootstrap/get_server_instance.go, pkg/cmd/purge.go, pkg/server/apikeys/apikeys_test.go, pkg/server/builds/service.go, pkg/server/builds/service_test.go, pkg/server/env/service_test.go, pkg/server/jobs/service_test.go, pkg/server/targets/get.go, pkg/server/targets/service_test.go, pkg/server/workspaces/service_test.go, pkg/server/workspacetemplates/prebuild_delete.go, pkg/server/workspacetemplates/prebuild_test.go
Fixed all tests and a few minor issues
=> fix: tests and minor issues

pkg/cmd/targetconfig/create.go
This PR fixes target config creation non-interactively through file
=> fix: target config create non-interactive

hack/samples/index.json
cleaned up samples index file to only include samples that work and have sufficient readme.
=> cleaned up samples to have only working ones

apps/api/src/workspace/services/workspace.service.ts
Added Archived and Error state exceptions to counting org workspaces.
=> fix: count active workspaces

apps/runner/internal/util/log_writer.go, apps/runner/pkg/docker/create.go, apps/runner/pkg/docker/image_pull.go, apps/runner/pkg/docker/image_push.go, apps/runner/pkg/docker/util.go, apps/runner/pkg/docker/volumes_mountpaths.go
This PR includes robust logging when mounting volumes
=> fix(runner): add robust logging for mount

apps/api/src/interceptors/metrics.interceptor.ts
Track volume create and delete requests in telemetry
=> telemetry: track volume requests

apps/api/src/workspace/services/workspace.service.ts
=> fix: workspace count

apps/api/src/workspace/managers/workspace.manager.ts
=> fix: remove archived sandbox from node

apps/api/.env, apps/api/project.json, apps/api/src/assets/templates/organization-invitation.template.ejs
Modified the organization invitation email template structure and styling to achieve consistent layouts across different email clients. Also, a couple of config fixes were necessary for the email service to work as expected.
=> refactor(api): organization invitation email template structure and styling

apps/api/src/workspace/managers/workspace.manager.ts
=> fix: limit concurrent archive per node

apps/api/src/workspace/managers/workspace.manager.ts
=> fix: sync state order by last activity

apps/runner/pkg/docker/client.go, apps/runner/pkg/docker/util.go, apps/runner/pkg/docker/volumes_mountpaths.go
This PR removes race conditioning when multiple sandboxes are mounting the same volume on the same runner
=> fix(runner): remove race condition when mounting volumes

apps/dashboard/src/components/WorkspaceTable.tsx, apps/dashboard/src/components/ui/table.tsx, apps/dashboard/src/pages/Images.tsx, apps/dashboard/src/pages/Workspaces.tsx
To improve UX, we will perform an optimistic update to match the expected state of a successfully finished action.
If the action fails, the state will be reverted to its original value.
=> refactor(dashboard): optimistic state management for sandbox and image actions

apps/api/src/workspace/controllers/workspace.controller.ts
Sandbox count quota validation would fail on e.g. 9/10 instead of 10/10
=> fix: sandbox quota validation

apps/api/src/workspace/managers/image.manager.ts
=> refactor: sync node images selector

apps/api/src/workspace/docker/docker-provider.ts, apps/api/src/workspace/subscribers/image.subscriber.ts
Simplified the image pull logic according to https://github.com/apocas/dockerode/issues/647.
We can consider adding an image exist check after the pull to be more robust. We can discuss that in the comments.
=> fix(api): simplify image pull logic

apps/cli/mcp/README.md, apps/cli/mcp/server.go, apps/cli/mcp/tools/common.go, apps/cli/mcp/tools/create_folder.go, apps/cli/mcp/tools/create_sandbox.go, apps/cli/mcp/tools/delete_file.go, apps/cli/mcp/tools/destroy_sandbox.go, apps/cli/mcp/tools/download_file.go, apps/cli/mcp/tools/execute_command.go, apps/cli/mcp/tools/file_info.go, apps/cli/mcp/tools/git_clone.go, apps/cli/mcp/tools/list_files.go, apps/cli/mcp/tools/move_file.go, apps/cli/mcp/tools/preview_link.go, apps/cli/mcp/tools/upload_file.go
This PR introduces sandbox ID update for Daytona MCP Server
=> fix(mcp): fix sandbox ID handling

apps/api/src/workspace/runner-api/runnerApi.ts
This PR adds timeout to axios create to prevent socket hang up issue
=> fix: socket hang up

apps/api/src/app.service.ts, apps/api/src/common/constants/default-organization-quota.ts, apps/api/src/migrations/1746604150910-migration.ts, apps/api/src/organization/dto/create-organization-quota.dto.ts, apps/api/src/organization/dto/overview.dto.ts, apps/api/src/organization/dto/update-organization-quota.dto.ts, apps/api/src/organization/entities/organization.entity.ts, apps/api/src/organization/organization.module.ts, apps/api/src/organization/services/organization.service.ts, apps/api/src/workspace/controllers/volume.controller.ts, apps/api/src/workspace/services/volume.service.ts, apps/dashboard/src/pages/Usage.tsx, libs/api-client-go/api/openapi.yaml, libs/api-client-go/model_create_organization_quota.go, libs/api-client-go/model_update_organization_quota.go, libs/api-client-go/model_usage_overview.go, libs/api-client-python/daytona_api_client/models/create_organization_quota.py, libs/api-client-python/daytona_api_client/models/update_organization_quota.py, libs/api-client-python/daytona_api_client/models/usage_overview.py, libs/api-client/src/models/create-organization-quota.ts, libs/api-client/src/models/update-organization-quota.ts, libs/api-client/src/models/usage-overview.ts
Introduces a quota for the total number of active volumes in an organization.
=> feat(api,dashboard): volumes quota

apps/daemon/pkg/toolbox/process/execute.go, apps/daemon/pkg/toolbox/process/types.go
This PR includes fix for running exec cmd with cwd
=> fix(daemon): add cwd to daemon exec

apps/api/src/workspace/managers/workspace.manager.ts, apps/api/src/workspace/services/node.service.ts
=> feat: redistribute sandboxes on start

apps/api/src/workspace/services/workspace.service.ts
=> fix: destroy state check

apps/cli/apiclient/api_client.go, apps/cli/mcp/tools/common.go
Add X-Daytona-Source header to cli request
Add X-Daytona-Source header to cli request
https://github.com/daytonaio/daytona/issues/1780
=> Add X-Daytona-Source header to cli request

apps/api/src/workspace/services/workspace.service.ts
=> refactor: validate workspace quota

apps/api/src/organization/organization.module.ts, apps/api/src/organization/services/organization.service.ts, apps/api/src/workspace/common/redis-lock.provider.ts, apps/api/src/workspace/managers/image.manager.ts, apps/api/src/workspace/managers/snapshot.manager.ts, apps/api/src/workspace/managers/volume.manager.ts, apps/api/src/workspace/managers/workspace.manager.ts, apps/api/src/workspace/runner-api/runnerApi.ts, apps/api/src/workspace/services/workspace-warm-pool.service.ts, apps/api/src/workspace/services/workspace.service.ts
Set and acquire redis lock only if not already set.
=> fix(api): redis lock set only if not set

apps/api/src/workspace/services/node.service.ts
Sort nodes by used capacity and then choose between 10 with lowest.
=> feat(api): optimize random node choice

apps/api/src/workspace/managers/workspace.manager.ts
=> fix(api): add missing redis unlock

apps/runner/pkg/daemon/util.go
This PR fixes an issue with runner when in debug mode
=> fix(runner): fix runner in local debug mode

apps/api/src/workspace/services/workspace-warm-pool.service.ts, apps/api/src/workspace/services/workspace.service.ts
Improves the error message for "Image not found" error
=> fix: improve error message for image not found

apps/api/src/workspace/services/node.service.ts
Small refactor of the `findAvailableNodes` function
=> fix: avoid too many imagenode params in query

apps/dashboard/src/pages/Onboarding.tsx
Modifies the onboarding snippet to grant all Sandbox permissions (only those that the user has) to the generated API key.
=> refactor(dashboard): onboarding API key permissions

apps/api/src/main.ts, apps/dashboard/src/pages/Billing.tsx
Fixes the CORS config for production builds. `cors: true` does not work after the app is built for production.
=> fix(api): fix cors config for production

apps/dashboard/src/components/ErrorBoundaryFallback.tsx, apps/dashboard/src/components/LoadingFallback.tsx, apps/dashboard/src/main.tsx, apps/dashboard/src/providers/OrganizationsProvider.tsx, apps/dashboard/src/providers/SelectedOrganizationProvider.tsx, package.json, yarn.lock
Introduces an error boundary to the dashboard application which displays a dialog component with the relevant message and stack trace of the error.
=> feat(dashboard): error boundary

apps/api/src/workspace/dto/toolbox.dto.ts, libs/api-client-go/api/openapi.yaml, libs/api-client-go/model_git_status.go, libs/api-client-python-async/daytona_api_client_async/models/git_status.py, libs/api-client-python/daytona_api_client/models/git_status.py, libs/api-client/src/models/git-status.ts
Changed property name from FileStatus[] to fileStatus
https://github.com/daytonaio/daytona/issues/1935
=> Fix GitStatus property name

apps/cli/cmd/snapshot/create.go, apps/cli/cmd/snapshot/push.go
Adds missing CLI snapshot command resource flags
Closes #2026
=> fix: cli add missing resource flags to snapshot

apps/docs/content/sdk-python/async/async-daytona.mdx, apps/docs/content/sdk-python/async/async-sandbox.mdx, apps/docs/content/sdk-python/sync/daytona.mdx, apps/docs/content/sdk-python/sync/sandbox.mdx, apps/docs/content/sdk-typescript/sandbox.mdx, examples/python/lifecycle/_async/lifecycle.py, libs/sdk-python/README.md, libs/sdk-python/pyproject.toml, libs/sdk-python/scripts/sync_generator.py, libs/sdk-python/src/daytona/_async/daytona.py, libs/sdk-python/src/daytona/_async/filesystem.py, libs/sdk-python/src/daytona/_async/object_storage.py, libs/sdk-python/src/daytona/_async/sandbox.py, libs/sdk-python/src/daytona/_async/snapshot.py, libs/sdk-python/src/daytona/_sync/daytona.py, libs/sdk-python/src/daytona/_sync/object_storage.py, libs/sdk-python/src/daytona/_sync/sandbox.py, libs/sdk-python/src/daytona/_sync/snapshot.py, libs/sdk-python/src/daytona/_utils/stream.py, libs/sdk-python/src/daytona/common/daytona.py, libs/sdk-python/src/daytona/common/sandbox.py, libs/sdk-python/src/daytona/common/snapshot.py, libs/sdk-typescript/README.md, libs/sdk-typescript/package.json, libs/sdk-typescript/project.json, libs/sdk-typescript/src/Daytona.ts, libs/sdk-typescript/src/Sandbox.ts, pyproject.toml
=> fix(sdk): packages metadata, async python actions, sbx state updates

apps/api/src/sandbox/managers/sandbox.manager.ts
Use string type constants instead of booleans to avoid potential misuse.
=> refactor: sync state return type

libs/sdk-python/src/daytona/_async/daytona.py, libs/sdk-python/src/daytona/_sync/daytona.py
Regression from https://github.com/daytonaio/daytona/pull/1942/files#diff-dd9205d356d655d9d25ab25d43d3af9435de97268c12f3deb593a02777e30f7dR132-R134
=> fix: improve handling of API key, JWT token, and organization ID

apps/api/src/sandbox/managers/sandbox.manager.ts
Allows restoring sandboxes whose underlying snapshot had been deleted because only the backup is relevant in this case
Relevant only for cases where redistribution is necessary
Minor fixes to variable names
=> fix: allow restoring sandboxes with deleted underlying snapshots

images/sandbox/Dockerfile
Disables this prompt for default image
=> fix: suppress zsh-new-user

apps/api/src/docker-registry/services/docker-registry.service.ts, apps/api/src/sandbox/managers/snapshot.manager.ts
=> fix: use proper registry when re-propagating

apps/api/src/sandbox/services/sandbox.service.ts
Fix warm pool response DTOs to have the correct runner domain value
=> fix: warm pool runner domain property

libs/sdk-typescript/src/Daytona.ts
This PR addresses issue #2088 2088
=> Use the modified label in Daytona creation in typescript

apps/api/src/main.ts, apps/api/src/sandbox/controllers/sandbox.controller.ts, apps/cli/cmd/sandbox/start.go, apps/daemon/pkg/toolbox/toolbox.go, apps/runner/pkg/docker/container_exec.go, apps/runner/pkg/docker/create.go, apps/runner/pkg/docker/image_pull.go, apps/runner/pkg/docker/start.go, apps/runner/pkg/docker/start_daemon.go, libs/api-client-go/api/openapi.yaml, libs/api-client-go/api_sandbox.go, libs/api-client-python-async/daytona_api_client_async/api/sandbox_api.py, libs/api-client-python/daytona_api_client/api/sandbox_api.py, libs/api-client/src/api/sandbox-api.ts, libs/common-go/pkg/timer/timer.go, libs/sdk-python/src/daytona/_async/sandbox.py, libs/sdk-python/src/daytona/_sync/sandbox.py, libs/sdk-typescript/src/Sandbox.ts
- waiting for daemon to start optimized
- removed unecessary 100ms wait in SDK
- optimized waiting for sandbox in the API
=> feat(api,runner,sdk): performance improvements

libs/sdk-typescript/src/Daytona.ts
=> fix(ts-sdk): suppress dotenv logs

apps/api/src/notification/gateways/notification.gateway.ts, apps/dashboard/src/App.tsx, apps/dashboard/src/contexts/NotificationSocketContext.tsx, apps/dashboard/src/pages/Sandboxes.tsx, apps/dashboard/src/pages/Snapshots.tsx, apps/dashboard/src/pages/Volumes.tsx, apps/dashboard/src/providers/NotificationSocketProvider.tsx
Fixes organization-scoped WebSocket events. Previously, events from all organizations that the user was a member of were showing up as real-time updates in the dashboard.
=> fix(api,dashboard): organization-scoped websocket events

apps/api/src/sandbox/managers/snapshot.manager.ts
Removed obsolete early-exit check in cron job for propagating snapshots to runners.
=> fix(api): remove obsolete check before propagating snapshots to runners

apps/cli/cmd/common/state.go
CLI snapshot poll use get instead of list
=> fix: cli snapshot poll use get instead of list

apps/api/src/sandbox/services/sandbox.service.ts
=> fix: skip warm pool if there are volumes in CreateSandboxDto

apps/api/src/sandbox/managers/sandbox.manager.ts
We process sandboxes with backups completed first when archiving to prevent pileups.
=> fix(api): process backups completed first when archiving sandboxes

apps/dashboard/src/App.tsx, apps/dashboard/src/components/Organizations/CreateOrganizationDialog.tsx, apps/dashboard/src/components/Organizations/OrganizationPicker.tsx, apps/dashboard/src/components/TierTable.tsx, apps/dashboard/src/contexts/BillingContext.tsx, apps/dashboard/src/contexts/OrganizationsContext.tsx, apps/dashboard/src/hooks/useBilling.tsx, apps/dashboard/src/pages/Dashboard.tsx, apps/dashboard/src/pages/Limits.tsx, apps/dashboard/src/pages/UserOrganizationInvitations.tsx, apps/dashboard/src/pages/Wallet.tsx, apps/dashboard/src/providers/BillingProvider.tsx, apps/dashboard/src/providers/OrganizationsProvider.tsx, eslint.config.mjs
Fixed some various issues with handling wallet and organization state.
Temporarily makes the dashboard do a full-page reload after creating a new org. Will come back to this asap.
Added a Contact sales button on the limits page.
Users with <= $0 balance in their wallet are now redirected to the wallet page.
=> fix(dashobard): billing-related states and limit labels

apps/api/src/audit/services/audit.service.ts
As mentioned in the commit message, the minimum retention period for audit logs (if configured) should be 365 days.
=> fix(api): increase audit log retention period minumum to 365 days

apps/api/src/sandbox/managers/sandbox.manager.ts
Added a 10-second timeout for sync state to prevent infinite loops.
=> fix(api): add exit condition for sync state

apps/api/src/organization/guards/organization-access.guard.ts
Implemented cache to reduce the DB pressure.
=> refactor: organization access guard cache

apps/docs/public/llms-full.txt, apps/docs/public/llms.txt, apps/docs/src/content/docs/en/preview-and-authentication.mdx
=> feat(docs): add DAYTONA_SANDBOX_AUTH_KEY query param for sandbox auth

apps/docs/src/content/docs/en/preview-and-authentication.mdx, apps/proxy/pkg/proxy/warning_page.go
Added a tip on how to disable the warning for an organization and a link to docs in the warning page
=> docs: preview warning

SECURITY.md
=> chore: update email in SECURITY.md

apps/proxy/pkg/proxy/proxy.go, apps/proxy/pkg/proxy/warning_page.go
Enables acceptance cookie to be set trough an iframe - setting it with SameSite: None.
=> Fix preview warning page when inside iframe

apps/runner/pkg/services/metrics.go
This PR introduces change to how CPU, memory and disk are allocated on each runner so that metrics are more precise in calculation
=> fix(runner): change allocated metrics calc

.devcontainer/devcontainer.build.json, .github/workflows/build_devcontainer.yaml
Fix devcontainer build to swap docker compose ref
=> chore: fix devcontainer build

apps/api/src/sandbox/managers/sandbox-actions/sandbox-start.action.ts
=> fix(api): missing org null check

.github/workflows/release.yaml
Sources the venv before publishing
=> chore: source venv in release pipeline

libs/sdk-python/src/daytona/_async/sandbox.py, libs/sdk-python/src/daytona/_sync/sandbox.py
Fix data extraction from API response for ssh access
=> fix(sdk): ssh access api response

apps/cli/project.json
Update output path of CLI build to apps/dist/cli/cli.
=> chore(cli): update output path
